//
//  IZBasement.swift
//  InfozentrumGuide
//
//  Created by RWTH on 18.01.18.
//  Copyright © 2018 RWTH. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//
//  This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
//



import UIKit

public class IZBasement : NSObject {

    //// Cache

    private struct Cache {
        static var imageOfCanvas1: UIImage?
        static var canvas1Targets: [AnyObject]?
    }

    //// Drawing Methods

    @objc dynamic public class func drawCanvas1(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 1343, height: 1308), resizing: ResizingBehavior = .aspectFit) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        //// Resize to Target Frame
        context.saveGState()
        let resizedFrame: CGRect = resizing.apply(rect: CGRect(x: 0, y: 0, width: 1343, height: 1308), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 1343, y: resizedFrame.height / 1308)


        //// Color Declarations
        let grass = UIColor(red: 0.706, green: 0.876, blue: 0.613, alpha: 1.000)
        let background = UIColor(red: 0.945, green: 0.945, blue: 0.945, alpha: 1.000)
        let greyedOutBackground = UIColor(red: 0.627, green: 0.627, blue: 0.627, alpha: 1.000)

        //// pool_bg Drawing
        let pool_bgPath = UIBezierPath()
        pool_bgPath.move(to: CGPoint(x: 365, y: 309))
        pool_bgPath.addLine(to: CGPoint(x: 385, y: 367))
        pool_bgPath.addLine(to: CGPoint(x: 279, y: 404))
        pool_bgPath.addLine(to: CGPoint(x: 346, y: 596))
        pool_bgPath.addLine(to: CGPoint(x: 291, y: 615))
        pool_bgPath.addLine(to: CGPoint(x: 324, y: 710))
        pool_bgPath.addLine(to: CGPoint(x: 379.03, y: 691.3))
        pool_bgPath.addLine(to: CGPoint(x: 412, y: 786))
        pool_bgPath.addLine(to: CGPoint(x: 399, y: 791))
        pool_bgPath.addLine(to: CGPoint(x: 405, y: 806))
        pool_bgPath.addLine(to: CGPoint(x: 444, y: 792))
        pool_bgPath.addLine(to: CGPoint(x: 467, y: 860))
        pool_bgPath.addLine(to: CGPoint(x: 561, y: 826))
        pool_bgPath.addLine(to: CGPoint(x: 538, y: 758))
        pool_bgPath.addLine(to: CGPoint(x: 522, y: 764))
        pool_bgPath.addLine(to: CGPoint(x: 387, y: 374))
        pool_bgPath.addLine(to: CGPoint(x: 400, y: 370))
        pool_bgPath.addLine(to: CGPoint(x: 377, y: 305))
        pool_bgPath.addLine(to: CGPoint(x: 365, y: 309))
        pool_bgPath.close()
        background.setFill()
        pool_bgPath.fill()


        //// mvdr_bg Drawing
        let mvdr_bgPath = UIBezierPath()
        mvdr_bgPath.move(to: CGPoint(x: 777.5, y: 1167.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 780.5, y: 1176.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 846.5, y: 1153.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 860.5, y: 1195.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 889.5, y: 1285.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 901.5, y: 1288.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 924.5, y: 1287.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 937.5, y: 1284.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 957.5, y: 1275.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 974.5, y: 1263.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 986.5, y: 1250.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 985.5, y: 1246.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 999.5, y: 1241.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 1010.5, y: 1273.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 1080.5, y: 1248.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 1042.5, y: 1141.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 1161.5, y: 1100.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 1215.5, y: 1254.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 1299.5, y: 1224.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 1221.5, y: 1002.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 1175.5, y: 1018.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 1129.5, y: 886.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 1043.5, y: 915.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 1090.5, y: 1048.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 1025.5, y: 1071.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 1005.5, y: 1079.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 841.5, y: 1137.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 843.5, y: 1144.5))
        mvdr_bgPath.addLine(to: CGPoint(x: 777.5, y: 1167.5))
        mvdr_bgPath.close()
        background.setFill()
        mvdr_bgPath.fill()


        //// rbi_bg Drawing
        let rbi_bgPath = UIBezierPath()
        rbi_bgPath.move(to: CGPoint(x: 752.5, y: 1067.5))
        rbi_bgPath.addLine(to: CGPoint(x: 665.5, y: 832.5))
        rbi_bgPath.addLine(to: CGPoint(x: 713.5, y: 814.5))
        rbi_bgPath.addLine(to: CGPoint(x: 672.5, y: 701.5))
        rbi_bgPath.addLine(to: CGPoint(x: 724.5, y: 682.5))
        rbi_bgPath.addLine(to: CGPoint(x: 719.5, y: 668.5))
        rbi_bgPath.addLine(to: CGPoint(x: 757.5, y: 654.5))
        rbi_bgPath.addLine(to: CGPoint(x: 835.5, y: 876.5))
        rbi_bgPath.addLine(to: CGPoint(x: 787.5, y: 893.5))
        rbi_bgPath.addLine(to: CGPoint(x: 834.5, y: 1024.5))
        rbi_bgPath.addLine(to: CGPoint(x: 780.5, y: 1042.5))
        rbi_bgPath.addLine(to: CGPoint(x: 784.5, y: 1055.5))
        rbi_bgPath.addLine(to: CGPoint(x: 752.5, y: 1067.5))
        rbi_bgPath.close()
        background.setFill()
        rbi_bgPath.fill()


        //// Greyed out Drawing
        let greyedOutPath = UIBezierPath()
        greyedOutPath.move(to: CGPoint(x: 376.5, y: 304.5))
        greyedOutPath.addLine(to: CGPoint(x: 397.5, y: 361.5))
        greyedOutPath.addLine(to: CGPoint(x: 646.5, y: 272.5))
        greyedOutPath.addLine(to: CGPoint(x: 606.5, y: 157.5))
        greyedOutPath.addLine(to: CGPoint(x: 627.5, y: 149.5))
        greyedOutPath.addLine(to: CGPoint(x: 578.5, y: 13.5))
        greyedOutPath.addLine(to: CGPoint(x: 479.5, y: 47.5))
        greyedOutPath.addLine(to: CGPoint(x: 508.5, y: 127.5))
        greyedOutPath.addLine(to: CGPoint(x: 416.5, y: 160.5))
        greyedOutPath.addLine(to: CGPoint(x: 416.5, y: 97.5))
        greyedOutPath.addLine(to: CGPoint(x: 382.5, y: 100.5))
        greyedOutPath.addLine(to: CGPoint(x: 349.5, y: 108.5))
        greyedOutPath.addLine(to: CGPoint(x: 317.5, y: 123.5))
        greyedOutPath.addLine(to: CGPoint(x: 293.5, y: 140.5))
        greyedOutPath.addLine(to: CGPoint(x: 329.5, y: 188.5))
        greyedOutPath.addLine(to: CGPoint(x: 152.5, y: 249.5))
        greyedOutPath.addLine(to: CGPoint(x: 136.5, y: 201.5))
        greyedOutPath.addLine(to: CGPoint(x: 16.5, y: 242.5))
        greyedOutPath.addLine(to: CGPoint(x: 81.5, y: 440.5))
        greyedOutPath.addLine(to: CGPoint(x: 103.5, y: 432.5))
        greyedOutPath.addLine(to: CGPoint(x: 117.5, y: 472.5))
        greyedOutPath.addLine(to: CGPoint(x: 287.5, y: 428.5))
        greyedOutPath.addLine(to: CGPoint(x: 278.5, y: 403.5))
        greyedOutPath.addLine(to: CGPoint(x: 384.5, y: 366.5))
        greyedOutPath.addLine(to: CGPoint(x: 364.5, y: 309.5))
        greyedOutPath.addLine(to: CGPoint(x: 376.5, y: 304.5))
        greyedOutPath.close()
        greyedOutBackground.setFill()
        greyedOutPath.fill()


        //// Greyed out 2 Drawing
        let greyedOut2Path = UIBezierPath()
        greyedOut2Path.move(to: CGPoint(x: 444.5, y: 791.5))
        greyedOut2Path.addLine(to: CGPoint(x: 404.5, y: 806.5))
        greyedOut2Path.addLine(to: CGPoint(x: 403.5, y: 991.5))
        greyedOut2Path.addLine(to: CGPoint(x: 354.5, y: 991.5))
        greyedOut2Path.addLine(to: CGPoint(x: 355.5, y: 1109.5))
        greyedOut2Path.addLine(to: CGPoint(x: 512.5, y: 1112.5))
        greyedOut2Path.addLine(to: CGPoint(x: 512.5, y: 1029.5))
        greyedOut2Path.addLine(to: CGPoint(x: 483.5, y: 1029.5))
        greyedOut2Path.addLine(to: CGPoint(x: 483.5, y: 888.5))
        greyedOut2Path.addLine(to: CGPoint(x: 594.5, y: 888.5))
        greyedOut2Path.addLine(to: CGPoint(x: 649.5, y: 1053.5))
        greyedOut2Path.addLine(to: CGPoint(x: 629.5, y: 1060.5))
        greyedOut2Path.addLine(to: CGPoint(x: 651.5, y: 1125.5))
        greyedOut2Path.addLine(to: CGPoint(x: 740.5, y: 1094.5))
        greyedOut2Path.addLine(to: CGPoint(x: 794.5, y: 1256.5))
        greyedOut2Path.addLine(to: CGPoint(x: 854.5, y: 1235.5))
        greyedOut2Path.addLine(to: CGPoint(x: 845.5, y: 1209.5))
        greyedOut2Path.addLine(to: CGPoint(x: 863, y: 1203))
        greyedOut2Path.addLine(to: CGPoint(x: 846, y: 1154))
        greyedOut2Path.addLine(to: CGPoint(x: 780, y: 1177))
        greyedOut2Path.addLine(to: CGPoint(x: 777, y: 1168))
        greyedOut2Path.addLine(to: CGPoint(x: 844, y: 1145))
        greyedOut2Path.addLine(to: CGPoint(x: 841, y: 1137))
        greyedOut2Path.addLine(to: CGPoint(x: 1089.5, y: 1049.5))
        greyedOut2Path.addLine(to: CGPoint(x: 1075.5, y: 1007.5))
        greyedOut2Path.addLine(to: CGPoint(x: 990.5, y: 1036.5))
        greyedOut2Path.addLine(to: CGPoint(x: 971.5, y: 978.5))
        greyedOut2Path.addLine(to: CGPoint(x: 834.5, y: 1024.5))
        greyedOut2Path.addLine(to: CGPoint(x: 780.5, y: 1042.5))
        greyedOut2Path.addLine(to: CGPoint(x: 784.5, y: 1055.5))
        greyedOut2Path.addLine(to: CGPoint(x: 752.5, y: 1067.5))
        greyedOut2Path.addLine(to: CGPoint(x: 679.5, y: 869.5))
        greyedOut2Path.addLine(to: CGPoint(x: 550.5, y: 872.5))
        greyedOut2Path.addLine(to: CGPoint(x: 537.5, y: 834.5))
        greyedOut2Path.addLine(to: CGPoint(x: 467.5, y: 859.5))
        greyedOut2Path.addLine(to: CGPoint(x: 444.5, y: 791.5))
        greyedOut2Path.close()
        greyedOutBackground.setFill()
        greyedOut2Path.fill()


        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: 16.5, y: 242.5))
        bezierPath.addCurve(to: CGPoint(x: 136.5, y: 201.5), controlPoint1: CGPoint(x: 119.5, y: 207.5), controlPoint2: CGPoint(x: 136.5, y: 201.5))
        bezierPath.addLine(to: CGPoint(x: 152.5, y: 249.5))
        bezierPath.addLine(to: CGPoint(x: 330, y: 189))
        bezierPath.addLine(to: CGPoint(x: 293.5, y: 140.5))
        bezierPath.addLine(to: CGPoint(x: 317.5, y: 123.5))
        bezierPath.addLine(to: CGPoint(x: 349.5, y: 108.5))
        bezierPath.addLine(to: CGPoint(x: 382.5, y: 100.5))
        bezierPath.addLine(to: CGPoint(x: 416.5, y: 97.5))
        bezierPath.addLine(to: CGPoint(x: 417, y: 160))
        bezierPath.addLine(to: CGPoint(x: 508, y: 128))
        bezierPath.addLine(to: CGPoint(x: 479.5, y: 47.5))
        bezierPath.addLine(to: CGPoint(x: 578.5, y: 13.5))
        bezierPath.addLine(to: CGPoint(x: 627.5, y: 149.5))
        bezierPath.addLine(to: CGPoint(x: 606.5, y: 157.5))
        bezierPath.addLine(to: CGPoint(x: 646.5, y: 272.5))
        bezierPath.addLine(to: CGPoint(x: 397, y: 361))
        bezierPath.addLine(to: CGPoint(x: 400, y: 370))
        bezierPath.addLine(to: CGPoint(x: 387.5, y: 374.22))
        bezierPath.addLine(to: CGPoint(x: 521.5, y: 764.5))
        bezierPath.addLine(to: CGPoint(x: 537.5, y: 758.5))
        bezierPath.addLine(to: CGPoint(x: 561, y: 826))
        bezierPath.addLine(to: CGPoint(x: 537, y: 835))
        bezierPath.addLine(to: CGPoint(x: 550.5, y: 872.5))
        bezierPath.addLine(to: CGPoint(x: 679.5, y: 869.5))
        bezierPath.addLine(to: CGPoint(x: 665.5, y: 832.5))
        bezierPath.addLine(to: CGPoint(x: 713.5, y: 814.5))
        bezierPath.addLine(to: CGPoint(x: 672, y: 701.5))
        bezierPath.addLine(to: CGPoint(x: 724.5, y: 682.5))
        bezierPath.addLine(to: CGPoint(x: 719.5, y: 668.5))
        bezierPath.addLine(to: CGPoint(x: 757.5, y: 654.5))
        bezierPath.addLine(to: CGPoint(x: 835.5, y: 876.5))
        bezierPath.addLine(to: CGPoint(x: 787.5, y: 893.5))
        bezierPath.addLine(to: CGPoint(x: 834.5, y: 1024.5))
        bezierPath.addLine(to: CGPoint(x: 879.56, y: 1009.37))
        bezierPath.addLine(to: CGPoint(x: 971.5, y: 978.5))
        bezierPath.addLine(to: CGPoint(x: 990.5, y: 1036.5))
        bezierPath.addLine(to: CGPoint(x: 1075.5, y: 1007.5))
        bezierPath.addLine(to: CGPoint(x: 1052.18, y: 940.44))
        bezierPath.addLine(to: CGPoint(x: 1043.5, y: 915.5))
        bezierPath.addLine(to: CGPoint(x: 1129, y: 887))
        bezierPath.addLine(to: CGPoint(x: 1175, y: 1019))
        bezierPath.addLine(to: CGPoint(x: 1221.5, y: 1002.5))
        bezierPath.addLine(to: CGPoint(x: 1299.5, y: 1224.5))
        bezierPath.addLine(to: CGPoint(x: 1215.5, y: 1254.5))
        bezierPath.addLine(to: CGPoint(x: 1161.5, y: 1100.5))
        bezierPath.addLine(to: CGPoint(x: 1033.5, y: 1144.5))
        bezierPath.addLine(to: CGPoint(x: 1053.5, y: 1203.5))
        bezierPath.addLine(to: CGPoint(x: 1040.5, y: 1215.5))
        bezierPath.addLine(to: CGPoint(x: 1025.5, y: 1223.5))
        bezierPath.addLine(to: CGPoint(x: 1010.5, y: 1228.5))
        bezierPath.addLine(to: CGPoint(x: 994.5, y: 1230.5))
        bezierPath.addLine(to: CGPoint(x: 979.5, y: 1230.5))
        bezierPath.addLine(to: CGPoint(x: 986.5, y: 1250.5))
        bezierPath.addLine(to: CGPoint(x: 974.5, y: 1263.5))
        bezierPath.addLine(to: CGPoint(x: 957.5, y: 1275.5))
        bezierPath.addLine(to: CGPoint(x: 937.5, y: 1284.5))
        bezierPath.addLine(to: CGPoint(x: 924.82, y: 1287.49))
        bezierPath.addLine(to: CGPoint(x: 912.01, y: 1288.5))
        bezierPath.addLine(to: CGPoint(x: 901.37, y: 1288.08))
        bezierPath.addLine(to: CGPoint(x: 889.5, y: 1285.5))
        bezierPath.addLine(to: CGPoint(x: 862.5, y: 1203.5))
        bezierPath.addLine(to: CGPoint(x: 845.5, y: 1209.5))
        bezierPath.addLine(to: CGPoint(x: 854.5, y: 1235.5))
        bezierPath.addLine(to: CGPoint(x: 794.5, y: 1257))
        bezierPath.addLine(to: CGPoint(x: 740.5, y: 1094.5))
        bezierPath.addLine(to: CGPoint(x: 651.5, y: 1125.5))
        bezierPath.addLine(to: CGPoint(x: 629.5, y: 1060.5))
        bezierPath.addLine(to: CGPoint(x: 649, y: 1054))
        bezierPath.addLine(to: CGPoint(x: 594.5, y: 888.5))
        bezierPath.addLine(to: CGPoint(x: 483, y: 889))
        bezierPath.addLine(to: CGPoint(x: 483.5, y: 1029.5))
        bezierPath.addLine(to: CGPoint(x: 512, y: 1030))
        bezierPath.addLine(to: CGPoint(x: 512.5, y: 1112.5))
        bezierPath.addLine(to: CGPoint(x: 355.5, y: 1109.5))
        bezierPath.addLine(to: CGPoint(x: 354.5, y: 991.5))
        bezierPath.addLine(to: CGPoint(x: 403.5, y: 991.5))
        bezierPath.addLine(to: CGPoint(x: 404.5, y: 806.5))
        bezierPath.addLine(to: CGPoint(x: 399, y: 791))
        bezierPath.addLine(to: CGPoint(x: 411.5, y: 786.5))
        bezierPath.addLine(to: CGPoint(x: 378.97, y: 691.77))
        bezierPath.addLine(to: CGPoint(x: 287.5, y: 428.5))
        bezierPath.addLine(to: CGPoint(x: 117.5, y: 472.5))
        bezierPath.addLine(to: CGPoint(x: 103.5, y: 432.5))
        bezierPath.addLine(to: CGPoint(x: 81.5, y: 440.5))
        bezierPath.addLine(to: CGPoint(x: 16.5, y: 242.5))
        UIColor.darkGray.setStroke()
        bezierPath.lineWidth = 2
        bezierPath.lineCapStyle = .round
        bezierPath.lineJoinStyle = .round
        bezierPath.stroke()


        //// Bezier 94 Drawing
        let bezier94Path = UIBezierPath()
        bezier94Path.move(to: CGPoint(x: 686, y: 1091))
        bezier94Path.addLine(to: CGPoint(x: 617.5, y: 886.5))
        bezier94Path.addLine(to: CGPoint(x: 684.5, y: 886.5))
        bezier94Path.addLine(to: CGPoint(x: 752, y: 1067.5))
        bezier94Path.addLine(to: CGPoint(x: 686, y: 1091))
        bezier94Path.close()
        grass.setFill()
        bezier94Path.fill()


        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.move(to: CGPoint(x: 707.5, y: 384.5))
        bezier2Path.addLine(to: CGPoint(x: 802.5, y: 648))
        bezier2Path.addLine(to: CGPoint(x: 894.5, y: 614.5))
        bezier2Path.addLine(to: CGPoint(x: 831.14, y: 440.26))
        bezier2Path.addLine(to: CGPoint(x: 798.5, y: 350.5))
        bezier2Path.addLine(to: CGPoint(x: 707.5, y: 384.5))
        bezier2Path.close()
        greyedOutBackground.setFill()
        bezier2Path.fill()
        UIColor.darkGray.setStroke()
        bezier2Path.lineWidth = 2
        bezier2Path.lineCapStyle = .round
        bezier2Path.lineJoinStyle = .round
        bezier2Path.stroke()


        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.move(to: CGPoint(x: 397, y: 361))
        bezier3Path.addLine(to: CGPoint(x: 377, y: 305))
        bezier3Path.addLine(to: CGPoint(x: 561, y: 240))
        bezier3Path.addLine(to: CGPoint(x: 520, y: 124))
        bezier3Path.addLine(to: CGPoint(x: 508, y: 128))
        UIColor.darkGray.setStroke()
        bezier3Path.lineWidth = 2
        bezier3Path.lineCapStyle = .round
        bezier3Path.lineJoinStyle = .round
        bezier3Path.stroke()


        //// Bezier 4 Drawing
        let bezier4Path = UIBezierPath()
        bezier4Path.move(to: CGPoint(x: 277.5, y: 229))
        bezier4Path.addLine(to: CGPoint(x: 344, y: 206))
        bezier4Path.addLine(to: CGPoint(x: 354, y: 235))
        bezier4Path.addLine(to: CGPoint(x: 430, y: 209))
        bezier4Path.addLine(to: CGPoint(x: 420, y: 180))
        bezier4Path.addLine(to: CGPoint(x: 487, y: 156))
        bezier4Path.addLine(to: CGPoint(x: 515, y: 235))
        bezier4Path.addLine(to: CGPoint(x: 320, y: 304))
        bezier4Path.addLine(to: CGPoint(x: 277.5, y: 229))
        bezier4Path.close()
        grass.setFill()
        bezier4Path.fill()
        UIColor.darkGray.setStroke()
        bezier4Path.lineWidth = 2
        bezier4Path.lineCapStyle = .round
        bezier4Path.lineJoinStyle = .round
        bezier4Path.stroke()


        //// Bezier 5 Drawing
        let bezier5Path = UIBezierPath()
        bezier5Path.move(to: CGPoint(x: 102, y: 433))
        bezier5Path.addLine(to: CGPoint(x: 203, y: 397))
        bezier5Path.addLine(to: CGPoint(x: 220, y: 446))
        UIColor.darkGray.setStroke()
        bezier5Path.lineWidth = 2
        bezier5Path.lineCapStyle = .round
        bezier5Path.lineJoinStyle = .round
        bezier5Path.stroke()


        //// Bezier 6 Drawing
        let bezier6Path = UIBezierPath()
        bezier6Path.move(to: CGPoint(x: 203, y: 397))
        bezier6Path.addLine(to: CGPoint(x: 152, y: 248))
        UIColor.darkGray.setStroke()
        bezier6Path.lineWidth = 2
        bezier6Path.lineCapStyle = .round
        bezier6Path.lineJoinStyle = .round
        bezier6Path.stroke()


        //// Bezier 7 Drawing
        let bezier7Path = UIBezierPath()
        bezier7Path.move(to: CGPoint(x: 344, y: 206))
        bezier7Path.addLine(to: CGPoint(x: 330, y: 189))
        UIColor.darkGray.setStroke()
        bezier7Path.lineWidth = 2
        bezier7Path.lineCapStyle = .round
        bezier7Path.lineJoinStyle = .round
        bezier7Path.stroke()


        //// Bezier 8 Drawing
        let bezier8Path = UIBezierPath()
        bezier8Path.move(to: CGPoint(x: 420, y: 180))
        bezier8Path.addLine(to: CGPoint(x: 417, y: 160))
        UIColor.red.setFill()
        bezier8Path.fill()
        UIColor.darkGray.setStroke()
        bezier8Path.lineWidth = 2
        bezier8Path.lineCapStyle = .round
        bezier8Path.lineJoinStyle = .round
        bezier8Path.stroke()


        //// Bezier 9 Drawing
        let bezier9Path = UIBezierPath()
        bezier9Path.move(to: CGPoint(x: 384.5, y: 366.8))
        bezier9Path.addLine(to: CGPoint(x: 358, y: 291))
        UIColor.darkGray.setStroke()
        bezier9Path.lineWidth = 2
        bezier9Path.lineCapStyle = .round
        bezier9Path.lineJoinStyle = .round
        bezier9Path.stroke()


        //// Bezier 10 Drawing
        let bezier10Path = UIBezierPath()
        bezier10Path.move(to: CGPoint(x: 212, y: 421))
        bezier10Path.addLine(to: CGPoint(x: 264.51, y: 407.42))
        bezier10Path.addLine(to: CGPoint(x: 281.6, y: 403))
        bezier10Path.addLine(to: CGPoint(x: 384, y: 367))
        UIColor.darkGray.setStroke()
        bezier10Path.lineWidth = 2
        bezier10Path.lineCapStyle = .round
        bezier10Path.lineJoinStyle = .round
        bezier10Path.stroke()


        //// Bezier 11 Drawing
        let bezier11Path = UIBezierPath()
        bezier11Path.move(to: CGPoint(x: 264, y: 408))
        bezier11Path.addLine(to: CGPoint(x: 270, y: 432))
        UIColor.darkGray.setStroke()
        bezier11Path.lineWidth = 2
        bezier11Path.lineCapStyle = .round
        bezier11Path.lineJoinStyle = .round
        bezier11Path.stroke()


        //// Bezier 12 Drawing
        let bezier12Path = UIBezierPath()
        bezier12Path.move(to: CGPoint(x: 278, y: 230))
        bezier12Path.addLine(to: CGPoint(x: 267, y: 211))
        UIColor.red.setFill()
        bezier12Path.fill()
        UIColor.darkGray.setStroke()
        bezier12Path.lineWidth = 2
        bezier12Path.lineCapStyle = .round
        bezier12Path.lineJoinStyle = .round
        bezier12Path.stroke()


        //// Bezier 13 Drawing
        let bezier13Path = UIBezierPath()
        bezier13Path.move(to: CGPoint(x: 526, y: 142))
        bezier13Path.addLine(to: CGPoint(x: 487, y: 156))
        bezier13Path.addLine(to: CGPoint(x: 481, y: 138))
        UIColor.darkGray.setStroke()
        bezier13Path.lineWidth = 2
        bezier13Path.lineCapStyle = .round
        bezier13Path.lineJoinStyle = .round
        bezier13Path.stroke()


        //// Bezier 14 Drawing
        let bezier14Path = UIBezierPath()
        bezier14Path.move(to: CGPoint(x: 533, y: 157))
        bezier14Path.addLine(to: CGPoint(x: 598, y: 134))
        bezier14Path.addLine(to: CGPoint(x: 607, y: 159))
        UIColor.darkGray.setStroke()
        bezier14Path.lineWidth = 2
        bezier14Path.lineCapStyle = .round
        bezier14Path.lineJoinStyle = .round
        bezier14Path.stroke()


        //// Bezier 15 Drawing
        let bezier15Path = UIBezierPath()
        bezier15Path.move(to: CGPoint(x: 170, y: 458))
        bezier15Path.addLine(to: CGPoint(x: 155, y: 414))
        UIColor.darkGray.setStroke()
        bezier15Path.lineWidth = 2
        bezier15Path.lineCapStyle = .round
        bezier15Path.lineJoinStyle = .round
        bezier15Path.stroke()


        //// Bezier 16 Drawing
        let bezier16Path = UIBezierPath()
        bezier16Path.move(to: CGPoint(x: 319, y: 390))
        bezier16Path.addLine(to: CGPoint(x: 402, y: 630))
        bezier16Path.addLine(to: CGPoint(x: 363, y: 644))
        UIColor.darkGray.setStroke()
        bezier16Path.lineWidth = 2
        bezier16Path.lineCapStyle = .round
        bezier16Path.lineJoinStyle = .round
        bezier16Path.stroke()


        //// Bezier 17 Drawing
        let bezier17Path = UIBezierPath()
        bezier17Path.move(to: CGPoint(x: 396, y: 399))
        bezier17Path.addLine(to: CGPoint(x: 355, y: 413))
        bezier17Path.addLine(to: CGPoint(x: 419.32, y: 599.22))
        bezier17Path.addLine(to: CGPoint(x: 442.72, y: 669.61))
        bezier17Path.addLine(to: CGPoint(x: 459.5, y: 717))
        bezier17Path.addLine(to: CGPoint(x: 395, y: 739))
        UIColor.darkGray.setStroke()
        bezier17Path.lineWidth = 2
        bezier17Path.lineCapStyle = .round
        bezier17Path.lineJoinStyle = .round
        bezier17Path.stroke()


        //// Bezier 18 Drawing
        let bezier18Path = UIBezierPath()
        bezier18Path.move(to: CGPoint(x: 346, y: 596))
        bezier18Path.addLine(to: CGPoint(x: 290.5, y: 615.5))
        bezier18Path.addLine(to: CGPoint(x: 324, y: 710))
        bezier18Path.addLine(to: CGPoint(x: 379, y: 691))
        bezier18Path.addLine(to: CGPoint(x: 418.5, y: 677.5))
        bezier18Path.addLine(to: CGPoint(x: 435, y: 724))
        UIColor.darkGray.setStroke()
        bezier18Path.lineWidth = 2
        bezier18Path.lineCapStyle = .round
        bezier18Path.lineJoinStyle = .round
        bezier18Path.stroke()


        //// Bezier 21 Drawing
        let bezier21Path = UIBezierPath()
        bezier21Path.move(to: CGPoint(x: 313, y: 504))
        bezier21Path.addLine(to: CGPoint(x: 354, y: 490))
        UIColor.darkGray.setStroke()
        bezier21Path.lineWidth = 2
        bezier21Path.stroke()


        //// Bezier 22 Drawing
        context.saveGState()
        context.translateBy(x: 326, y: 526)
        context.scaleBy(x: 0.97, y: 0.97)

        let bezier22Path = UIBezierPath()
        bezier22Path.move(to: CGPoint(x: 0, y: 14))
        bezier22Path.addLine(to: CGPoint(x: 41, y: 0))
        UIColor.darkGray.setStroke()
        bezier22Path.lineWidth = 2
        bezier22Path.stroke()

        context.restoreGState()


        //// Bezier 24 Drawing
        context.saveGState()
        context.translateBy(x: 346, y: 582.3)
        context.scaleBy(x: 0.98, y: 0.98)

        let bezier24Path = UIBezierPath()
        bezier24Path.move(to: CGPoint(x: 0, y: 14))
        bezier24Path.addLine(to: CGPoint(x: 40, y: 0))
        UIColor.darkGray.setStroke()
        bezier24Path.lineWidth = 2
        bezier24Path.lineCapStyle = .round
        bezier24Path.stroke()

        context.restoreGState()


        //// Bezier 26 Drawing
        let bezier26Path = UIBezierPath()
        bezier26Path.move(to: CGPoint(x: 411, y: 574))
        bezier26Path.addLine(to: CGPoint(x: 452, y: 560))
        UIColor.darkGray.setStroke()
        bezier26Path.lineWidth = 2
        bezier26Path.stroke()


        //// Bezier 27 Drawing
        let bezier27Path = UIBezierPath()
        bezier27Path.move(to: CGPoint(x: 402, y: 550))
        bezier27Path.addLine(to: CGPoint(x: 443, y: 536))
        UIColor.darkGray.setStroke()
        bezier27Path.lineWidth = 2
        bezier27Path.stroke()


        //// Bezier 28 Drawing
        let bezier28Path = UIBezierPath()
        bezier28Path.move(to: CGPoint(x: 394, y: 526))
        bezier28Path.addLine(to: CGPoint(x: 435, y: 512))
        UIColor.darkGray.setStroke()
        bezier28Path.lineWidth = 2
        bezier28Path.stroke()


        //// Bezier 29 Drawing
        let bezier29Path = UIBezierPath()
        bezier29Path.move(to: CGPoint(x: 386, y: 505))
        bezier29Path.addLine(to: CGPoint(x: 427, y: 491))
        UIColor.darkGray.setStroke()
        bezier29Path.lineWidth = 2
        bezier29Path.stroke()


        //// Bezier 30 Drawing
        let bezier30Path = UIBezierPath()
        bezier30Path.move(to: CGPoint(x: 363, y: 437))
        bezier30Path.addLine(to: CGPoint(x: 404, y: 423))
        UIColor.darkGray.setStroke()
        bezier30Path.lineWidth = 2
        bezier30Path.stroke()


        //// Bezier 34 Drawing
        let bezier34Path = UIBezierPath()
        bezier34Path.move(to: CGPoint(x: 523, y: 764))
        bezier34Path.addLine(to: CGPoint(x: 444, y: 792))
        bezier34Path.addLine(to: CGPoint(x: 467, y: 860))
        bezier34Path.addLine(to: CGPoint(x: 537, y: 835))
        UIColor.darkGray.setStroke()
        bezier34Path.lineWidth = 2
        bezier34Path.lineCapStyle = .round
        bezier34Path.stroke()


        //// Bezier 35 Drawing
        let bezier35Path = UIBezierPath()
        bezier35Path.move(to: CGPoint(x: 405, y: 806))
        bezier35Path.addLine(to: CGPoint(x: 444, y: 792))
        UIColor.darkGray.setStroke()
        bezier35Path.lineWidth = 2
        bezier35Path.stroke()


        //// Bezier 36 Drawing
        let bezier36Path = UIBezierPath()
        bezier36Path.move(to: CGPoint(x: 459.5, y: 717))
        bezier36Path.addLine(to: CGPoint(x: 481, y: 779))
        UIColor.darkGray.setStroke()
        bezier36Path.lineWidth = 2
        bezier36Path.stroke()


        //// Bezier 38 Drawing
        let bezier38Path = UIBezierPath()
        bezier38Path.move(to: CGPoint(x: 482, y: 947))
        bezier38Path.addLine(to: CGPoint(x: 428, y: 947))
        bezier38Path.addLine(to: CGPoint(x: 428, y: 874))
        bezier38Path.addLine(to: CGPoint(x: 467, y: 860))
        UIColor.darkGray.setStroke()
        bezier38Path.lineWidth = 2
        bezier38Path.lineCapStyle = .round
        bezier38Path.lineJoinStyle = .round
        bezier38Path.stroke()


        //// Bezier 40 Drawing
        let bezier40Path = UIBezierPath()
        bezier40Path.move(to: CGPoint(x: 483, y: 904))
        bezier40Path.addLine(to: CGPoint(x: 483, y: 889))
        bezier40Path.addLine(to: CGPoint(x: 428, y: 889))
        UIColor.darkGray.setStroke()
        bezier40Path.lineWidth = 2
        bezier40Path.stroke()


        //// Bezier 41 Drawing
        let bezier41Path = UIBezierPath()
        bezier41Path.move(to: CGPoint(x: 427, y: 881))
        bezier41Path.addLine(to: CGPoint(x: 404, y: 881))
        UIColor.darkGray.setStroke()
        bezier41Path.lineWidth = 2
        bezier41Path.lineCapStyle = .round
        bezier41Path.lineJoinStyle = .round
        bezier41Path.stroke()


        //// Bezier 42 Drawing
        let bezier42Path = UIBezierPath()
        bezier42Path.move(to: CGPoint(x: 427, y: 907))
        bezier42Path.addLine(to: CGPoint(x: 404, y: 907))
        UIColor.darkGray.setStroke()
        bezier42Path.lineWidth = 2
        bezier42Path.lineCapStyle = .round
        bezier42Path.lineJoinStyle = .round
        bezier42Path.stroke()


        //// Bezier 39 Drawing
        let bezier39Path = UIBezierPath()
        bezier39Path.move(to: CGPoint(x: 752, y: 1068))
        bezier39Path.addLine(to: CGPoint(x: 686, y: 1091))
        bezier39Path.addLine(to: CGPoint(x: 617, y: 887))
        bezier39Path.addLine(to: CGPoint(x: 685, y: 886))
        bezier39Path.addLine(to: CGPoint(x: 752, y: 1068))
        bezier39Path.addLine(to: CGPoint(x: 815, y: 1046))
        bezier39Path.addLine(to: CGPoint(x: 846, y: 1136))
        bezier39Path.addLine(to: CGPoint(x: 1005, y: 1080))
        bezier39Path.addLine(to: CGPoint(x: 990, y: 1035))
        UIColor.darkGray.setStroke()
        bezier39Path.lineWidth = 2
        bezier39Path.lineCapStyle = .round
        bezier39Path.lineJoinStyle = .round
        bezier39Path.stroke()


        //// Bezier 43 Drawing
        let bezier43Path = UIBezierPath()
        bezier43Path.move(to: CGPoint(x: 736, y: 1096))
        bezier43Path.addLine(to: CGPoint(x: 800, y: 1074))
        bezier43Path.addLine(to: CGPoint(x: 816, y: 1121))
        bezier43Path.addLine(to: CGPoint(x: 756, y: 1142))
        bezier43Path.addLine(to: CGPoint(x: 771, y: 1187))
        bezier43Path.addLine(to: CGPoint(x: 831, y: 1166))
        bezier43Path.addLine(to: CGPoint(x: 847, y: 1214))
        UIColor.darkGray.setStroke()
        bezier43Path.lineWidth = 2
        bezier43Path.lineCapStyle = .round
        bezier43Path.lineJoinStyle = .round
        bezier43Path.stroke()


        //// Bezier 45 Drawing
        let bezier45Path = UIBezierPath()
        bezier45Path.move(to: CGPoint(x: 771, y: 1187))
        bezier45Path.addLine(to: CGPoint(x: 831, y: 1166))
        UIColor.darkGray.setStroke()
        bezier45Path.lineWidth = 2
        bezier45Path.stroke()


        //// Bezier 44 Drawing
        let bezier44Path = UIBezierPath()
        bezier44Path.move(to: CGPoint(x: 755.5, y: 1142))
        bezier44Path.addLine(to: CGPoint(x: 815.5, y: 1121))
        UIColor.darkGray.setStroke()
        bezier44Path.lineWidth = 2
        bezier44Path.stroke()


        //// Bezier 46 Drawing
        let bezier46Path = UIBezierPath()
        bezier46Path.move(to: CGPoint(x: 980, y: 1232))
        bezier46Path.addLine(to: CGPoint(x: 952, y: 1148))
        bezier46Path.addLine(to: CGPoint(x: 938, y: 1153))
        bezier46Path.addLine(to: CGPoint(x: 966, y: 1143))
        UIColor.darkGray.setStroke()
        bezier46Path.lineWidth = 2
        bezier46Path.lineCapStyle = .round
        bezier46Path.lineJoinStyle = .round
        bezier46Path.stroke()


        //// Bezier 47 Drawing
        let bezier47Path = UIBezierPath()
        bezier47Path.move(to: CGPoint(x: 860, y: 1196))
        bezier47Path.addLine(to: CGPoint(x: 1030, y: 1136))
        UIColor.darkGray.setStroke()
        bezier47Path.lineWidth = 2
        bezier47Path.stroke()


        //// Bezier 48 Drawing
        let bezier48Path = UIBezierPath()
        bezier48Path.move(to: CGPoint(x: 863, y: 1205))
        bezier48Path.addLine(to: CGPoint(x: 856, y: 1183))
        bezier48Path.addLine(to: CGPoint(x: 867, y: 1179))
        UIColor.darkGray.setStroke()
        bezier48Path.lineWidth = 2
        bezier48Path.lineCapStyle = .round
        bezier48Path.lineJoinStyle = .round
        bezier48Path.stroke()


        //// Bezier 49 Drawing
        let bezier49Path = UIBezierPath()
        bezier49Path.move(to: CGPoint(x: 1035, y: 1149))
        bezier49Path.addLine(to: CGPoint(x: 1026, y: 1122))
        bezier49Path.addLine(to: CGPoint(x: 1015, y: 1126))
        UIColor.darkGray.setStroke()
        bezier49Path.lineWidth = 2
        bezier49Path.lineCapStyle = .round
        bezier49Path.lineJoinStyle = .round
        bezier49Path.stroke()


        //// Bezier 50 Drawing
        let bezier50Path = UIBezierPath()
        bezier50Path.move(to: CGPoint(x: 836, y: 1024))
        bezier50Path.addLine(to: CGPoint(x: 780, y: 1043))
        bezier50Path.addLine(to: CGPoint(x: 784.5, y: 1056))
        UIColor.darkGray.setStroke()
        bezier50Path.lineWidth = 2
        bezier50Path.lineCapStyle = .round
        bezier50Path.lineJoinStyle = .round
        bezier50Path.stroke()


        //// Bezier 51 Drawing
        let bezier51Path = UIBezierPath()
        bezier51Path.move(to: CGPoint(x: 989, y: 1035))
        bezier51Path.addLine(to: CGPoint(x: 854.5, y: 1081.5))
        bezier51Path.addLine(to: CGPoint(x: 834, y: 1023))
        UIColor.darkGray.setStroke()
        bezier51Path.lineWidth = 2
        bezier51Path.lineCapStyle = .round
        bezier51Path.lineJoinStyle = .round
        bezier51Path.stroke()


        //// Bezier 52 Drawing
        let bezier52Path = UIBezierPath()
        bezier52Path.move(to: CGPoint(x: 879.5, y: 1009))
        bezier52Path.addLine(to: CGPoint(x: 899, y: 1066))
        UIColor.darkGray.setStroke()
        bezier52Path.lineWidth = 2
        bezier52Path.stroke()


        //// Bezier 53 Drawing
        let bezier53Path = UIBezierPath()
        bezier53Path.move(to: CGPoint(x: 1011, y: 1030))
        bezier53Path.addLine(to: CGPoint(x: 1025, y: 1072))
        bezier53Path.addLine(to: CGPoint(x: 1090, y: 1049))
        bezier53Path.addLine(to: CGPoint(x: 1075, y: 1006))
        UIColor.darkGray.setStroke()
        bezier53Path.lineWidth = 2
        bezier53Path.lineCapStyle = .round
        bezier53Path.lineJoinStyle = .round
        bezier53Path.stroke()


        //// Bezier 54 Drawing
        let bezier54Path = UIBezierPath()
        bezier54Path.move(to: CGPoint(x: 1090, y: 1049))
        bezier54Path.addLine(to: CGPoint(x: 1175, y: 1019))
        UIColor.darkGray.setStroke()
        bezier54Path.lineWidth = 2
        bezier54Path.stroke()


        //// Bezier 55 Drawing
        let bezier55Path = UIBezierPath()
        bezier55Path.move(to: CGPoint(x: 1082, y: 903))
        bezier55Path.addLine(to: CGPoint(x: 1128, y: 1036))
        UIColor.darkGray.setStroke()
        bezier55Path.lineWidth = 2
        bezier55Path.stroke()


        //// Bezier 56 Drawing
        let bezier56Path = UIBezierPath()
        bezier56Path.move(to: CGPoint(x: 1092, y: 899))
        bezier56Path.addLine(to: CGPoint(x: 1138, y: 1031))
        UIColor.darkGray.setStroke()
        bezier56Path.lineWidth = 2
        bezier56Path.stroke()


        //// Bezier 58 Drawing
        let bezier58Path = UIBezierPath()
        bezier58Path.move(to: CGPoint(x: 1097, y: 950))
        bezier58Path.addLine(to: CGPoint(x: 1060, y: 963))
        UIColor.darkGray.setStroke()
        bezier58Path.lineWidth = 2
        bezier58Path.lineCapStyle = .round
        bezier58Path.stroke()


        //// Bezier 59 Drawing
        let bezier59Path = UIBezierPath()
        bezier59Path.move(to: CGPoint(x: 1105, y: 971))
        bezier59Path.addLine(to: CGPoint(x: 1068, y: 984))
        UIColor.darkGray.setStroke()
        bezier59Path.lineWidth = 2
        bezier59Path.stroke()


        //// Bezier 61 Drawing
        let bezier61Path = UIBezierPath()
        bezier61Path.move(to: CGPoint(x: 1120, y: 1014.5))
        bezier61Path.addLine(to: CGPoint(x: 1082, y: 1028))
        UIColor.darkGray.setStroke()
        bezier61Path.lineWidth = 2
        bezier61Path.stroke()


        //// Bezier 62 Drawing
        let bezier62Path = UIBezierPath()
        bezier62Path.move(to: CGPoint(x: 1152, y: 954.5))
        bezier62Path.addLine(to: CGPoint(x: 1116, y: 967))
        UIColor.darkGray.setStroke()
        bezier62Path.lineWidth = 2
        bezier62Path.stroke()


        //// Bezier 63 Drawing
        let bezier63Path = UIBezierPath()
        bezier63Path.move(to: CGPoint(x: 1145, y: 933.5))
        bezier63Path.addLine(to: CGPoint(x: 1109, y: 946))
        UIColor.darkGray.setStroke()
        bezier63Path.lineWidth = 2
        bezier63Path.stroke()


        //// Bezier 64 Drawing
        let bezier64Path = UIBezierPath()
        bezier64Path.move(to: CGPoint(x: 1160, y: 976))
        bezier64Path.addLine(to: CGPoint(x: 1123, y: 989))
        UIColor.darkGray.setStroke()
        bezier64Path.lineWidth = 2
        bezier64Path.stroke()


        //// Bezier 65 Drawing
        let bezier65Path = UIBezierPath()
        bezier65Path.move(to: CGPoint(x: 1167, y: 998))
        bezier65Path.addLine(to: CGPoint(x: 1131, y: 1011))
        UIColor.darkGray.setStroke()
        bezier65Path.lineWidth = 2
        bezier65Path.stroke()


        //// Bezier 66 Drawing
        let bezier66Path = UIBezierPath()
        bezier66Path.move(to: CGPoint(x: 1189.5, y: 1064))
        bezier66Path.addLine(to: CGPoint(x: 1251, y: 1241))
        UIColor.darkGray.setStroke()
        bezier66Path.lineWidth = 2
        bezier66Path.lineCapStyle = .round
        bezier66Path.lineJoinStyle = .round
        bezier66Path.stroke()


        //// Bezier 67 Drawing
        let bezier67Path = UIBezierPath()
        bezier67Path.move(to: CGPoint(x: 1210, y: 1082))
        bezier67Path.addLine(to: CGPoint(x: 1264, y: 1237))
        UIColor.darkGray.setStroke()
        bezier67Path.lineWidth = 2
        bezier67Path.stroke()


        //// Bezier 68 Drawing
        let bezier68Path = UIBezierPath()
        bezier68Path.move(to: CGPoint(x: 1160, y: 1101))
        bezier68Path.addLine(to: CGPoint(x: 1245, y: 1070))
        UIColor.darkGray.setStroke()
        bezier68Path.lineWidth = 2
        bezier68Path.stroke()


        //// Bezier 69 Drawing
        let bezier69Path = UIBezierPath()
        bezier69Path.move(to: CGPoint(x: 1212, y: 1129))
        bezier69Path.addLine(to: CGPoint(x: 1176, y: 1142))
        UIColor.darkGray.setStroke()
        bezier69Path.lineWidth = 2
        bezier69Path.stroke()


        //// Bezier 70 Drawing
        let bezier70Path = UIBezierPath()
        bezier70Path.move(to: CGPoint(x: 1227, y: 1174))
        bezier70Path.addLine(to: CGPoint(x: 1191, y: 1187))
        UIColor.darkGray.setStroke()
        bezier70Path.lineWidth = 2
        bezier70Path.stroke()


        //// Bezier 71 Drawing
        let bezier71Path = UIBezierPath()
        bezier71Path.move(to: CGPoint(x: 1235, y: 1196))
        bezier71Path.addLine(to: CGPoint(x: 1199, y: 1209))
        UIColor.darkGray.setStroke()
        bezier71Path.lineWidth = 2
        bezier71Path.stroke()


        //// Bezier 72 Drawing
        let bezier72Path = UIBezierPath()
        bezier72Path.move(to: CGPoint(x: 1243, y: 1218.5))
        bezier72Path.addLine(to: CGPoint(x: 1208, y: 1231))
        UIColor.darkGray.setStroke()
        bezier72Path.lineWidth = 2
        bezier72Path.stroke()


        //// Bezier 73 Drawing
        let bezier73Path = UIBezierPath()
        bezier73Path.move(to: CGPoint(x: 1291, y: 1201))
        bezier73Path.addLine(to: CGPoint(x: 1255, y: 1214))
        UIColor.darkGray.setStroke()
        bezier73Path.lineWidth = 2
        bezier73Path.stroke()


        //// Bezier 74 Drawing
        let bezier74Path = UIBezierPath()
        bezier74Path.move(to: CGPoint(x: 1283, y: 1178))
        bezier74Path.addLine(to: CGPoint(x: 1248, y: 1191))
        UIColor.darkGray.setStroke()
        bezier74Path.lineWidth = 2
        bezier74Path.stroke()


        //// Bezier 75 Drawing
        let bezier75Path = UIBezierPath()
        bezier75Path.move(to: CGPoint(x: 1276, y: 1156))
        bezier75Path.addLine(to: CGPoint(x: 1240, y: 1169))
        UIColor.darkGray.setStroke()
        bezier75Path.lineWidth = 2
        bezier75Path.stroke()


        //// Bezier 76 Drawing
        let bezier76Path = UIBezierPath()
        bezier76Path.move(to: CGPoint(x: 1268, y: 1134))
        bezier76Path.addLine(to: CGPoint(x: 1232, y: 1147))
        UIColor.darkGray.setStroke()
        bezier76Path.lineWidth = 2
        bezier76Path.stroke()


        //// Bezier 77 Drawing
        let bezier77Path = UIBezierPath()
        bezier77Path.move(to: CGPoint(x: 1261, y: 1112))
        bezier77Path.addLine(to: CGPoint(x: 1225, y: 1125))
        UIColor.darkGray.setStroke()
        bezier77Path.lineWidth = 2
        bezier77Path.stroke()


        //// Bezier 78 Drawing
        let bezier78Path = UIBezierPath()
        bezier78Path.move(to: CGPoint(x: 1253, y: 1090))
        bezier78Path.addLine(to: CGPoint(x: 1217, y: 1103))
        UIColor.darkGray.setStroke()
        bezier78Path.lineWidth = 2
        bezier78Path.stroke()


        //// Bezier 79 Drawing
        let bezier79Path = UIBezierPath()
        bezier79Path.move(to: CGPoint(x: 1210, y: 1082))
        bezier79Path.addLine(to: CGPoint(x: 1186, y: 1015))
        UIColor.darkGray.setStroke()
        bezier79Path.lineWidth = 2
        bezier79Path.stroke()


        //// Bezier 80 Drawing
        let bezier80Path = UIBezierPath()
        bezier80Path.move(to: CGPoint(x: 1162, y: 1102))
        bezier80Path.addLine(to: CGPoint(x: 1153.5, y: 1077))
        bezier80Path.addLine(to: CGPoint(x: 1035, y: 1119))
        bezier80Path.addLine(to: CGPoint(x: 1080, y: 1249))
        bezier80Path.addLine(to: CGPoint(x: 1010, y: 1274))
        bezier80Path.addLine(to: CGPoint(x: 999, y: 1242))
        bezier80Path.addLine(to: CGPoint(x: 986.6, y: 1246.3))
        UIColor.darkGray.setStroke()
        bezier80Path.lineWidth = 2
        bezier80Path.lineCapStyle = .round
        bezier80Path.lineJoinStyle = .round
        bezier80Path.stroke()


        //// Bezier 81 Drawing
        let bezier81Path = UIBezierPath()
        bezier81Path.move(to: CGPoint(x: 1128, y: 1036))
        bezier81Path.addLine(to: CGPoint(x: 1136, y: 1058.5))
        bezier81Path.addLine(to: CGPoint(x: 1006, y: 1105))
        UIColor.darkGray.setStroke()
        bezier81Path.lineWidth = 2
        bezier81Path.lineCapStyle = .round
        bezier81Path.lineJoinStyle = .round
        bezier81Path.stroke()


        //// Bezier 82 Drawing
        let bezier82Path = UIBezierPath()
        bezier82Path.move(to: CGPoint(x: 1175, y: 1019))
        bezier82Path.addLine(to: CGPoint(x: 1183, y: 1042))
        bezier82Path.addLine(to: CGPoint(x: 1146.5, y: 1055))
        bezier82Path.addLine(to: CGPoint(x: 1138, y: 1031))
        UIColor.darkGray.setStroke()
        bezier82Path.lineWidth = 2
        bezier82Path.lineCapStyle = .round
        bezier82Path.lineJoinStyle = .round
        bezier82Path.stroke()


        //// Bezier 83 Drawing
        let bezier83Path = UIBezierPath()
        bezier83Path.move(to: CGPoint(x: 724, y: 878))
        bezier83Path.addLine(to: CGPoint(x: 702, y: 819))
        UIColor.darkGray.setStroke()
        bezier83Path.lineWidth = 2
        bezier83Path.lineCapStyle = .round
        bezier83Path.lineJoinStyle = .round
        bezier83Path.stroke()


        //// Bezier 84 Drawing
        let bezier84Path = UIBezierPath()
        bezier84Path.move(to: CGPoint(x: 687, y: 891))
        bezier84Path.addLine(to: CGPoint(x: 724, y: 878))
        bezier84Path.addLine(to: CGPoint(x: 756, y: 964))
        bezier84Path.addLine(to: CGPoint(x: 719, y: 977))
        UIColor.darkGray.setStroke()
        bezier84Path.lineWidth = 2
        bezier84Path.lineCapStyle = .round
        bezier84Path.lineJoinStyle = .round
        bezier84Path.stroke()


        //// Bezier 87 Drawing
        let bezier87Path = UIBezierPath()
        bezier87Path.move(to: CGPoint(x: 806, y: 946.3))
        bezier87Path.addLine(to: CGPoint(x: 768.7, y: 959.2))
        bezier87Path.addLine(to: CGPoint(x: 736.5, y: 873.4))
        bezier87Path.addLine(to: CGPoint(x: 724, y: 878))
        UIColor.darkGray.setStroke()
        bezier87Path.lineWidth = 2
        bezier87Path.lineCapStyle = .round
        bezier87Path.lineJoinStyle = .round
        bezier87Path.stroke()


        //// Bezier 88 Drawing
        let bezier88Path = UIBezierPath()
        bezier88Path.move(to: CGPoint(x: 798, y: 925))
        bezier88Path.addLine(to: CGPoint(x: 762, y: 938))
        UIColor.darkGray.setStroke()
        bezier88Path.lineWidth = 2
        bezier88Path.lineCapStyle = .round
        bezier88Path.stroke()


        //// Bezier 89 Drawing
        let bezier89Path = UIBezierPath()
        bezier89Path.move(to: CGPoint(x: 790, y: 903))
        bezier89Path.addLine(to: CGPoint(x: 754, y: 916))
        UIColor.darkGray.setStroke()
        bezier89Path.lineWidth = 2
        bezier89Path.lineCapStyle = .round
        bezier89Path.stroke()


        //// Bezier 90 Drawing
        let bezier90Path = UIBezierPath()
        bezier90Path.move(to: CGPoint(x: 788, y: 895))
        bezier90Path.addLine(to: CGPoint(x: 783, y: 881.4))
        bezier90Path.addLine(to: CGPoint(x: 746, y: 895))
        UIColor.darkGray.setStroke()
        bezier90Path.lineWidth = 2
        bezier90Path.lineCapStyle = .round
        bezier90Path.lineJoinStyle = .round
        bezier90Path.stroke()


        //// Bezier 91 Drawing
        let bezier91Path = UIBezierPath()
        bezier91Path.move(to: CGPoint(x: 775, y: 860))
        bezier91Path.addLine(to: CGPoint(x: 783.2, y: 882))
        UIColor.darkGray.setStroke()
        bezier91Path.lineWidth = 2
        bezier91Path.lineCapStyle = .round
        bezier91Path.stroke()


        //// Bezier 92 Drawing
        let bezier92Path = UIBezierPath()
        bezier92Path.move(to: CGPoint(x: 724.3, y: 682))
        bezier92Path.addLine(to: CGPoint(x: 798.8, y: 889))
        UIColor.darkGray.setStroke()
        bezier92Path.lineWidth = 2
        bezier92Path.lineCapStyle = .round
        bezier92Path.stroke()


        //// Bezier 93 Drawing
        let bezier93Path = UIBezierPath()
        bezier93Path.move(to: CGPoint(x: 712.3, y: 688))
        bezier93Path.addLine(to: CGPoint(x: 766, y: 838.1))
        bezier93Path.addLine(to: CGPoint(x: 727.9, y: 852))
        bezier93Path.addLine(to: CGPoint(x: 713.3, y: 814))
        UIColor.darkGray.setStroke()
        bezier93Path.lineWidth = 2
        bezier93Path.lineCapStyle = .round
        bezier93Path.lineJoinStyle = .round
        bezier93Path.stroke()


        //// Bezier 95 Drawing
        let bezier95Path = UIBezierPath()
        bezier95Path.move(to: CGPoint(x: 747, y: 785))
        bezier95Path.addLine(to: CGPoint(x: 709, y: 799))
        UIColor.darkGray.setStroke()
        bezier95Path.lineWidth = 2
        bezier95Path.lineCapStyle = .round
        bezier95Path.stroke()


        //// Bezier 96 Drawing
        let bezier96Path = UIBezierPath()
        bezier96Path.move(to: CGPoint(x: 739, y: 763))
        bezier96Path.addLine(to: CGPoint(x: 701, y: 777))
        UIColor.darkGray.setStroke()
        bezier96Path.lineWidth = 2
        bezier96Path.lineCapStyle = .round
        bezier96Path.stroke()


        //// Bezier 97 Drawing
        let bezier97Path = UIBezierPath()
        bezier97Path.move(to: CGPoint(x: 730, y: 740))
        bezier97Path.addLine(to: CGPoint(x: 692, y: 754))
        UIColor.darkGray.setStroke()
        bezier97Path.lineWidth = 2
        bezier97Path.lineCapStyle = .round
        bezier97Path.stroke()


        //// Bezier 98 Drawing
        let bezier98Path = UIBezierPath()
        bezier98Path.move(to: CGPoint(x: 781, y: 720))
        bezier98Path.addLine(to: CGPoint(x: 743, y: 734))
        UIColor.darkGray.setStroke()
        bezier98Path.lineWidth = 2
        bezier98Path.stroke()


        //// Bezier 99 Drawing
        let bezier99Path = UIBezierPath()
        bezier99Path.move(to: CGPoint(x: 789, y: 743))
        bezier99Path.addLine(to: CGPoint(x: 751, y: 757))
        UIColor.darkGray.setStroke()
        bezier99Path.lineWidth = 2
        bezier99Path.stroke()


        //// Bezier 102 Drawing
        let bezier102Path = UIBezierPath()
        bezier102Path.move(to: CGPoint(x: 812, y: 812))
        bezier102Path.addLine(to: CGPoint(x: 776, y: 825))
        UIColor.darkGray.setStroke()
        bezier102Path.lineWidth = 2
        bezier102Path.lineCapStyle = .round
        bezier102Path.stroke()


        //// Bezier 105 Drawing
        let bezier105Path = UIBezierPath()
        bezier105Path.move(to: CGPoint(x: 758, y: 815))
        bezier105Path.addLine(to: CGPoint(x: 719, y: 829))
        UIColor.darkGray.setStroke()
        bezier105Path.lineWidth = 2
        bezier105Path.stroke()


        //// Bezier 106 Drawing
        let bezier106Path = UIBezierPath()
        bezier106Path.move(to: CGPoint(x: 365, y: 309))
        bezier106Path.addLine(to: CGPoint(x: 377, y: 305))
        UIColor.darkGray.setStroke()
        bezier106Path.lineWidth = 2
        bezier106Path.stroke()


        //// Bezier 107 Drawing
        let bezier107Path = UIBezierPath()
        bezier107Path.move(to: CGPoint(x: 831, y: 440))
        bezier107Path.addLine(to: CGPoint(x: 807, y: 449))
        bezier107Path.addLine(to: CGPoint(x: 816, y: 474))
        UIColor.darkGray.setStroke()
        bezier107Path.lineWidth = 2
        bezier107Path.lineCapStyle = .round
        bezier107Path.lineJoinStyle = .round
        bezier107Path.stroke()


        //// Bezier 108 Drawing
        let bezier108Path = UIBezierPath()
        bezier108Path.move(to: CGPoint(x: 852, y: 499))
        bezier108Path.addLine(to: CGPoint(x: 818, y: 511))
        bezier108Path.addLine(to: CGPoint(x: 844, y: 582))
        bezier108Path.addLine(to: CGPoint(x: 878, y: 570))
        UIColor.darkGray.setStroke()
        bezier108Path.lineWidth = 2
        bezier108Path.lineCapStyle = .round
        bezier108Path.lineJoinStyle = .round
        bezier108Path.stroke()


        //// Bezier 109 Drawing
        let bezier109Path = UIBezierPath()
        bezier109Path.move(to: CGPoint(x: 740, y: 373))
        bezier109Path.addLine(to: CGPoint(x: 781, y: 486))
        bezier109Path.addLine(to: CGPoint(x: 790, y: 483))
        bezier109Path.addLine(to: CGPoint(x: 804, y: 521))
        bezier109Path.addLine(to: CGPoint(x: 819, y: 516))
        UIColor.darkGray.setStroke()
        bezier109Path.lineWidth = 2
        bezier109Path.lineCapStyle = .round
        bezier109Path.lineJoinStyle = .round
        bezier109Path.stroke()


        //// Bezier 110 Drawing
        let bezier110Path = UIBezierPath()
        bezier110Path.move(to: CGPoint(x: 827, y: 534))
        bezier110Path.addLine(to: CGPoint(x: 860, y: 522))
        UIColor.darkGray.setStroke()
        bezier110Path.lineWidth = 2
        bezier110Path.stroke()


        //// Bezier 111 Drawing
        let bezier111Path = UIBezierPath()
        bezier111Path.move(to: CGPoint(x: 747, y: 492))
        bezier111Path.addLine(to: CGPoint(x: 767, y: 485))
        bezier111Path.addLine(to: CGPoint(x: 779, y: 519))
        bezier111Path.addLine(to: CGPoint(x: 799, y: 512))
        UIColor.darkGray.setStroke()
        bezier111Path.lineWidth = 2
        bezier111Path.lineCapStyle = .round
        bezier111Path.lineJoinStyle = .round
        bezier111Path.stroke()


        //// Bezier 113 Drawing
        let bezier113Path = UIBezierPath()
        bezier113Path.move(to: CGPoint(x: 844, y: 582))
        bezier113Path.addLine(to: CGPoint(x: 786.3, y: 602.7))
        UIColor.darkGray.setStroke()
        bezier113Path.lineWidth = 2
        bezier113Path.lineCapStyle = .round
        bezier113Path.lineJoinStyle = .round
        bezier113Path.stroke()


        //// Bezier 114 Drawing
        let bezier114Path = UIBezierPath()
        bezier114Path.move(to: CGPoint(x: 835, y: 637))
        bezier114Path.addLine(to: CGPoint(x: 818.5, y: 591))
        UIColor.darkGray.setStroke()
        bezier114Path.lineWidth = 2
        bezier114Path.stroke()


        //// Bezier 116 Drawing
        let bezier116Path = UIBezierPath()
        bezier116Path.move(to: CGPoint(x: 828, y: 587))
        bezier116Path.addLine(to: CGPoint(x: 804, y: 521))
        UIColor.darkGray.setStroke()
        bezier116Path.lineWidth = 2
        bezier116Path.stroke()


        //// Bezier 112 Drawing
        let bezier112Path = UIBezierPath()
        bezier112Path.move(to: CGPoint(x: 766, y: 363))
        bezier112Path.addLine(to: CGPoint(x: 804, y: 469))
        bezier112Path.addLine(to: CGPoint(x: 779, y: 478))
        UIColor.darkGray.setStroke()
        bezier112Path.lineWidth = 2
        bezier112Path.lineCapStyle = .round
        bezier112Path.lineJoinStyle = .round
        bezier112Path.stroke()


        //// Bezier 115 Drawing
        let bezier115Path = UIBezierPath()
        bezier115Path.move(to: CGPoint(x: 807, y: 449))
        bezier115Path.addLine(to: CGPoint(x: 775, y: 360))
        UIColor.darkGray.setStroke()
        bezier115Path.lineWidth = 2
        bezier115Path.stroke()


        //// Bezier 117 Drawing
        let bezier117Path = UIBezierPath()
        bezier117Path.move(to: CGPoint(x: 795, y: 413))
        bezier117Path.addLine(to: CGPoint(x: 817, y: 405))
        UIColor.darkGray.setStroke()
        bezier117Path.lineWidth = 2
        bezier117Path.lineCapStyle = .round
        bezier117Path.lineJoinStyle = .round
        bezier117Path.stroke()


        //// Bezier 118 Drawing
        let bezier118Path = UIBezierPath()
        bezier118Path.move(to: CGPoint(x: 787, y: 389))
        bezier118Path.addLine(to: CGPoint(x: 809, y: 381))
        UIColor.darkGray.setStroke()
        bezier118Path.lineWidth = 2
        bezier118Path.lineCapStyle = .round
        bezier118Path.lineJoinStyle = .round
        bezier118Path.stroke()


        //// Bezier 119 Drawing
        let bezier119Path = UIBezierPath()
        bezier119Path.move(to: CGPoint(x: 750, y: 397))
        bezier119Path.addLine(to: CGPoint(x: 774, y: 388.3))
        UIColor.darkGray.setStroke()
        bezier119Path.lineWidth = 2
        bezier119Path.lineCapStyle = .round
        bezier119Path.lineJoinStyle = .round
        bezier119Path.stroke()


        //// Bezier 120 Drawing
        let bezier120Path = UIBezierPath()
        bezier120Path.move(to: CGPoint(x: 754, y: 409))
        bezier120Path.addLine(to: CGPoint(x: 778, y: 400.3))
        UIColor.darkGray.setStroke()
        bezier120Path.lineWidth = 2
        bezier120Path.lineCapStyle = .round
        bezier120Path.lineJoinStyle = .round
        bezier120Path.stroke()


        //// Bezier 121 Drawing
        let bezier121Path = UIBezierPath()
        bezier121Path.move(to: CGPoint(x: 765, y: 438))
        bezier121Path.addLine(to: CGPoint(x: 789, y: 429.3))
        UIColor.darkGray.setStroke()
        bezier121Path.lineWidth = 2
        bezier121Path.lineCapStyle = .round
        bezier121Path.lineJoinStyle = .round
        bezier121Path.stroke()


        //// Bezier 122 Drawing
        let bezier122Path = UIBezierPath()
        bezier122Path.move(to: CGPoint(x: 790.7, y: 473))
        bezier122Path.addLine(to: CGPoint(x: 787, y: 463))
        bezier122Path.addLine(to: CGPoint(x: 800, y: 458.4))
        UIColor.darkGray.setStroke()
        bezier122Path.lineWidth = 2
        bezier122Path.lineCapStyle = .round
        bezier122Path.lineJoinStyle = .round
        bezier122Path.stroke()


        //// Bezier 123 Drawing
        let bezier123Path = UIBezierPath()
        bezier123Path.move(to: CGPoint(x: 790, y: 483))
        bezier123Path.addLine(to: CGPoint(x: 787, y: 474.8))
        UIColor.darkGray.setStroke()
        bezier123Path.lineWidth = 2
        bezier123Path.stroke()


        //// Bezier 124 Drawing
        let bezier124Path = UIBezierPath()
        bezier124Path.move(to: CGPoint(x: 794, y: 440))
        bezier124Path.addLine(to: CGPoint(x: 802, y: 437.2))
        UIColor.darkGray.setStroke()
        bezier124Path.lineWidth = 2
        bezier124Path.stroke()


        //// Bezier 125 Drawing
        let bezier125Path = UIBezierPath()
        bezier125Path.move(to: CGPoint(x: 804, y: 469))
        bezier125Path.addLine(to: CGPoint(x: 812, y: 466.2))
        UIColor.darkGray.setStroke()
        bezier125Path.lineWidth = 2
        bezier125Path.lineCapStyle = .round
        bezier125Path.lineJoinStyle = .round
        bezier125Path.stroke()


        //// Bezier 133 Drawing
        context.saveGState()
        context.translateBy(x: 796.4, y: 892.53)
        context.rotate(by: 25.5 * CGFloat.pi/180)
        context.scaleBy(x: 1.5, y: 1.5)

        let bezier133Path = UIBezierPath()
        bezier133Path.move(to: CGPoint(x: -0.2, y: 6))
        bezier133Path.addLine(to: CGPoint(x: -0.2, y: 1))
        bezier133Path.addLine(to: CGPoint(x: 4.8, y: 1))
        bezier133Path.addLine(to: CGPoint(x: -0.2, y: 6))
        UIColor.darkGray.setFill()
        bezier133Path.fill()
        UIColor.darkGray.setStroke()
        bezier133Path.lineWidth = 0.5
        bezier133Path.lineCapStyle = .round
        bezier133Path.lineJoinStyle = .round
        bezier133Path.stroke()

        context.restoreGState()


        //// Bezier 31 Drawing
        let bezier31Path = UIBezierPath()
        bezier31Path.move(to: CGPoint(x: 418, y: 598))
        bezier31Path.addLine(to: CGPoint(x: 459, y: 584))
        UIColor.darkGray.setStroke()
        bezier31Path.lineWidth = 2
        bezier31Path.stroke()


        //// Bezier 32 Drawing
        let bezier32Path = UIBezierPath()
        bezier32Path.move(to: CGPoint(x: 427, y: 622))
        bezier32Path.addLine(to: CGPoint(x: 468, y: 608))
        UIColor.darkGray.setStroke()
        bezier32Path.lineWidth = 2
        bezier32Path.stroke()


        //// Bezier 33 Drawing
        let bezier33Path = UIBezierPath()
        bezier33Path.move(to: CGPoint(x: 435, y: 646))
        bezier33Path.addLine(to: CGPoint(x: 476, y: 632))
        UIColor.darkGray.setStroke()
        bezier33Path.lineWidth = 2
        bezier33Path.stroke()


        //// Bezier 126 Drawing
        let bezier126Path = UIBezierPath()
        bezier126Path.move(to: CGPoint(x: 443, y: 669))
        bezier126Path.addLine(to: CGPoint(x: 484, y: 655))
        UIColor.darkGray.setStroke()
        bezier126Path.lineWidth = 2
        bezier126Path.stroke()


        //// Bezier 127 Drawing
        let bezier127Path = UIBezierPath()
        bezier127Path.move(to: CGPoint(x: 451, y: 692))
        bezier127Path.addLine(to: CGPoint(x: 492, y: 678))
        UIColor.darkGray.setStroke()
        bezier127Path.lineWidth = 2
        bezier127Path.stroke()


        //// Bezier 128 Drawing
        let bezier128Path = UIBezierPath()
        bezier128Path.move(to: CGPoint(x: 459, y: 717))
        bezier128Path.addLine(to: CGPoint(x: 500, y: 702.5))
        UIColor.darkGray.setStroke()
        bezier128Path.lineWidth = 2
        bezier128Path.stroke()


        //// Bezier 23 Drawing
        let bezier23Path = UIBezierPath()
        bezier23Path.move(to: CGPoint(x: 378, y: 482))
        bezier23Path.addLine(to: CGPoint(x: 419, y: 468))
        UIColor.darkGray.setStroke()
        bezier23Path.lineWidth = 2
        bezier23Path.stroke()


        //// Bezier 19 Drawing
        let bezier19Path = UIBezierPath()
        bezier19Path.move(to: CGPoint(x: 288, y: 430))
        bezier19Path.addLine(to: CGPoint(x: 279, y: 404))
        UIColor.darkGray.setStroke()
        bezier19Path.lineWidth = 2
        bezier19Path.stroke()


        //// Bezier 20 Drawing
        let bezier20Path = UIBezierPath()
        UIColor.black.setStroke()
        bezier20Path.lineWidth = 1
        bezier20Path.stroke()


        //// Bezier 25 Drawing
        let bezier25Path = UIBezierPath()
        bezier25Path.move(to: CGPoint(x: 347, y: 467))
        bezier25Path.addLine(to: CGPoint(x: 359, y: 463))
        bezier25Path.addLine(to: CGPoint(x: 412, y: 615))
        bezier25Path.addLine(to: CGPoint(x: 399.5, y: 619.3))
        UIColor.darkGray.setStroke()
        bezier25Path.lineWidth = 2
        bezier25Path.lineCapStyle = .round
        bezier25Path.lineJoinStyle = .round
        bezier25Path.stroke()


        //// Bezier 37 Drawing
        let bezier37Path = UIBezierPath()
        bezier37Path.move(to: CGPoint(x: 362, y: 514))
        bezier37Path.addLine(to: CGPoint(x: 374, y: 510))
        UIColor.darkGray.setStroke()
        bezier37Path.lineWidth = 2
        bezier37Path.lineCapStyle = .round
        bezier37Path.lineJoinStyle = .round
        bezier37Path.stroke()


        //// Bezier 129 Drawing
        let bezier129Path = UIBezierPath()
        bezier129Path.move(to: CGPoint(x: 378, y: 560))
        bezier129Path.addLine(to: CGPoint(x: 390, y: 556))
        UIColor.darkGray.setStroke()
        bezier129Path.lineWidth = 2
        bezier129Path.lineCapStyle = .round
        bezier129Path.lineJoinStyle = .round
        bezier129Path.stroke()


        //// Bezier 130 Drawing
        let bezier130Path = UIBezierPath()
        bezier130Path.move(to: CGPoint(x: 395, y: 606.1))
        bezier130Path.addLine(to: CGPoint(x: 407, y: 602))
        UIColor.darkGray.setStroke()
        bezier130Path.lineWidth = 2
        bezier130Path.lineCapStyle = .round
        bezier130Path.lineJoinStyle = .round
        bezier130Path.stroke()


        //// Bezier 131 Drawing
        let bezier131Path = UIBezierPath()
        bezier131Path.move(to: CGPoint(x: 1220, y: 1150))
        bezier131Path.addLine(to: CGPoint(x: 1184, y: 1163))
        UIColor.darkGray.setStroke()
        bezier131Path.lineWidth = 2
        bezier131Path.stroke()


        //// Bezier 132 Drawing
        let bezier132Path = UIBezierPath()
        UIColor.black.setStroke()
        bezier132Path.lineWidth = 1
        bezier132Path.stroke()


        //// Bezier 134 Drawing
        let bezier134Path = UIBezierPath()
        bezier134Path.move(to: CGPoint(x: 856, y: 1183))
        bezier134Path.addLine(to: CGPoint(x: 846.5, y: 1154))
        bezier134Path.addLine(to: CGPoint(x: 780, y: 1177))
        bezier134Path.addLine(to: CGPoint(x: 777, y: 1168))
        bezier134Path.addLine(to: CGPoint(x: 843.5, y: 1145))
        bezier134Path.addLine(to: CGPoint(x: 841.2, y: 1137.7))
        bezier134Path.addLine(to: CGPoint(x: 849, y: 1135))
        UIColor.darkGray.setStroke()
        bezier134Path.lineWidth = 2
        bezier134Path.lineCapStyle = .round
        bezier134Path.lineJoinStyle = .round
        bezier134Path.stroke()


        //// Bezier 135 Drawing
        let bezier135Path = UIBezierPath()
        bezier135Path.move(to: CGPoint(x: 1072, y: 1131))
        bezier135Path.addLine(to: CGPoint(x: 1064, y: 1109))
        UIColor.darkGray.setStroke()
        bezier135Path.lineWidth = 2
        bezier135Path.stroke()


        //// Bezier 136 Drawing
        let bezier136Path = UIBezierPath()
        bezier136Path.move(to: CGPoint(x: 1093, y: 1124))
        bezier136Path.addLine(to: CGPoint(x: 1085, y: 1102))
        UIColor.darkGray.setStroke()
        bezier136Path.lineWidth = 2
        bezier136Path.stroke()


        //// Bezier 137 Drawing
        let bezier137Path = UIBezierPath()
        bezier137Path.move(to: CGPoint(x: 1117, y: 1115))
        bezier137Path.addLine(to: CGPoint(x: 1109, y: 1093))
        UIColor.darkGray.setStroke()
        bezier137Path.lineWidth = 2
        bezier137Path.stroke()


        //// Bezier 138 Drawing
        let bezier138Path = UIBezierPath()
        bezier138Path.move(to: CGPoint(x: 1098, y: 1071))
        bezier138Path.addLine(to: CGPoint(x: 1090, y: 1049))
        UIColor.darkGray.setStroke()
        bezier138Path.lineWidth = 2
        bezier138Path.stroke()


        //// Bezier 139 Drawing
        let bezier139Path = UIBezierPath()
        bezier139Path.move(to: CGPoint(x: 1117, y: 1065))
        bezier139Path.addLine(to: CGPoint(x: 1102, y: 1022))
        UIColor.darkGray.setStroke()
        bezier139Path.lineWidth = 2
        bezier139Path.stroke()


        //// Bezier 140 Drawing
        let bezier140Path = UIBezierPath()
        bezier140Path.move(to: CGPoint(x: 1138, y: 910))
        bezier140Path.addLine(to: CGPoint(x: 1101, y: 923))
        UIColor.darkGray.setStroke()
        bezier140Path.lineWidth = 2
        bezier140Path.stroke()


        //// Bezier 57 Drawing
        let bezier57Path = UIBezierPath()
        bezier57Path.move(to: CGPoint(x: 1237, y: 1046.5))
        bezier57Path.addLine(to: CGPoint(x: 1202, y: 1059))
        UIColor.darkGray.setStroke()
        bezier57Path.lineWidth = 2
        bezier57Path.stroke()


        //// Bezier 60 Drawing
        let bezier60Path = UIBezierPath()
        bezier60Path.move(to: CGPoint(x: 1013, y: 1103))
        bezier60Path.addLine(to: CGPoint(x: 1005, y: 1080))
        UIColor.darkGray.setStroke()
        bezier60Path.lineWidth = 2
        bezier60Path.stroke()


        //// Bezier 141 Drawing
        let bezier141Path = UIBezierPath()
        bezier141Path.move(to: CGPoint(x: 1033, y: 1095))
        bezier141Path.addLine(to: CGPoint(x: 1025, y: 1072))
        UIColor.darkGray.setStroke()
        bezier141Path.lineWidth = 2
        bezier141Path.stroke()


        //// Bezier 142 Drawing
        let bezier142Path = UIBezierPath()
        bezier142Path.move(to: CGPoint(x: 1005, y: 1080))
        bezier142Path.addLine(to: CGPoint(x: 1025, y: 1072))
        UIColor.darkGray.setStroke()
        bezier142Path.lineWidth = 2
        bezier142Path.stroke()


        //// Bezier 85 Drawing
        let bezier85Path = UIBezierPath()
        UIColor.black.setStroke()
        bezier85Path.lineWidth = 1
        bezier85Path.stroke()


        //// Bezier 86 Drawing
        let bezier86Path = UIBezierPath()
        bezier86Path.move(to: CGPoint(x: 685, y: 886))
        bezier86Path.addLine(to: CGPoint(x: 679, y: 868))
        UIColor.darkGray.setStroke()
        bezier86Path.lineWidth = 2
        bezier86Path.lineCapStyle = .round
        bezier86Path.lineJoinStyle = .round
        bezier86Path.stroke()
        
        context.restoreGState()

    }

    //// Generated Images

    @objc dynamic public class var imageOfCanvas1: UIImage {
        if Cache.imageOfCanvas1 != nil {
            return Cache.imageOfCanvas1!
        }

        UIGraphicsBeginImageContextWithOptions(CGSize(width: 1343, height: 1308), false, 0)
            IZBasement.drawCanvas1()

        Cache.imageOfCanvas1 = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return Cache.imageOfCanvas1!
    }

    //// Customization Infrastructure

    @objc @IBOutlet dynamic var canvas1Targets: [AnyObject]! {
        get { return Cache.canvas1Targets }
        set {
            Cache.canvas1Targets = newValue
            for target: AnyObject in newValue {
                let _ = target.perform(NSSelectorFromString("setImage:"), with: IZBasement.imageOfCanvas1)
            }
        }
    }




    @objc(IZBasementResizingBehavior)
    public enum ResizingBehavior: Int {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.

        public func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }

            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)

            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }

            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
}
