//
//  IZFirstFloor.swift
//  InfozentrumGuide
//
//  Created by RWTH on 19.01.18.
//  Copyright © 2018 RWTH. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//
//  This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
//



import UIKit

public class IZFirstFloor : NSObject {

    //// Cache

    private struct Cache {
        static var imageOfCanvas1: UIImage?
        static var canvas1Targets: [AnyObject]?
    }

    //// Drawing Methods

    @objc dynamic public class func drawCanvas1(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 1343, height: 1308), resizing: ResizingBehavior = .aspectFit) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        //// Resize to Target Frame
        context.saveGState()
        let resizedFrame: CGRect = resizing.apply(rect: CGRect(x: 0, y: 0, width: 1343, height: 1308), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 1343, y: resizedFrame.height / 1308)


        //// Color Declarations
        let grass = UIColor(red: 0.788, green: 0.906, blue: 0.725, alpha: 1.000)
        let background = UIColor(red: 0.934, green: 0.928, blue: 0.910, alpha: 1.000)
        let greyedOutBackground = UIColor(red: 0.627, green: 0.627, blue: 0.627, alpha: 1.000)

        //// pool_bg Drawing
        context.saveGState()
        context.translateBy(x: 276.45, y: 307.28)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let pool_bgPath = UIBezierPath()
        pool_bgPath.move(to: CGPoint(x: 83.55, y: -1.01))
        pool_bgPath.addLine(to: CGPoint(x: -21.13, y: 35.91))
        pool_bgPath.addLine(to: CGPoint(x: 133, y: 481))
        pool_bgPath.addLine(to: CGPoint(x: 120, y: 486))
        pool_bgPath.addLine(to: CGPoint(x: 126, y: 501))
        pool_bgPath.addLine(to: CGPoint(x: 165, y: 487))
        pool_bgPath.addLine(to: CGPoint(x: 188, y: 555))
        pool_bgPath.addLine(to: CGPoint(x: 282, y: 521))
        pool_bgPath.addLine(to: CGPoint(x: 259, y: 453))
        pool_bgPath.addLine(to: CGPoint(x: 243, y: 459))
        pool_bgPath.addLine(to: CGPoint(x: 83.55, y: -1.01))
        pool_bgPath.close()
        background.setFill()
        pool_bgPath.fill()

        context.restoreGState()


        //// rbi_bg Drawing
        context.saveGState()
        context.translateBy(x: 659.88, y: 660.14)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let rbi_bgPath = UIBezierPath()
        rbi_bgPath.move(to: CGPoint(x: 87, y: 413))
        rbi_bgPath.addLine(to: CGPoint(x: 0, y: 178))
        rbi_bgPath.addLine(to: CGPoint(x: 48, y: 160))
        rbi_bgPath.addLine(to: CGPoint(x: 7, y: 47))
        rbi_bgPath.addLine(to: CGPoint(x: 59, y: 28))
        rbi_bgPath.addLine(to: CGPoint(x: 54, y: 14))
        rbi_bgPath.addLine(to: CGPoint(x: 92, y: 0))
        rbi_bgPath.addLine(to: CGPoint(x: 170, y: 222))
        rbi_bgPath.addLine(to: CGPoint(x: 122, y: 239))
        rbi_bgPath.addLine(to: CGPoint(x: 169, y: 370))
        rbi_bgPath.addLine(to: CGPoint(x: 115, y: 388))
        rbi_bgPath.addLine(to: CGPoint(x: 119, y: 401))
        rbi_bgPath.addLine(to: CGPoint(x: 87, y: 413))
        rbi_bgPath.close()
        background.setFill()
        rbi_bgPath.fill()

        context.restoreGState()


        //// mvdr_bg Drawing
        context.saveGState()
        context.translateBy(x: 769.85, y: 893.11)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let mvdr_bgPath = UIBezierPath()
        mvdr_bgPath.move(to: CGPoint(x: 336.17, y: 229.97))
        mvdr_bgPath.addLine(to: CGPoint(x: 384, y: 214))
        mvdr_bgPath.addLine(to: CGPoint(x: 438, y: 368))
        mvdr_bgPath.addLine(to: CGPoint(x: 522, y: 338))
        mvdr_bgPath.addLine(to: CGPoint(x: 444, y: 116))
        mvdr_bgPath.addLine(to: CGPoint(x: 398, y: 132))
        mvdr_bgPath.addLine(to: CGPoint(x: 352, y: 0))
        mvdr_bgPath.addLine(to: CGPoint(x: 266, y: 29))
        mvdr_bgPath.addLine(to: CGPoint(x: 313, y: 162))
        mvdr_bgPath.addLine(to: CGPoint(x: 336.17, y: 229.97))
        mvdr_bgPath.close()
        background.setFill()
        mvdr_bgPath.fill()

        context.restoreGState()


        //// Greyed out Drawing
        context.saveGState()
        context.translateBy(x: 16.5, y: 13.5)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let greyedOutPath = UIBezierPath()
        greyedOutPath.move(to: CGPoint(x: 630, y: 259))
        greyedOutPath.addLine(to: CGPoint(x: 590, y: 144))
        greyedOutPath.addLine(to: CGPoint(x: 611, y: 136))
        greyedOutPath.addLine(to: CGPoint(x: 562, y: 0))
        greyedOutPath.addLine(to: CGPoint(x: 463, y: 34))
        greyedOutPath.addLine(to: CGPoint(x: 492, y: 114))
        greyedOutPath.addLine(to: CGPoint(x: 400, y: 147))
        greyedOutPath.addLine(to: CGPoint(x: 400, y: 84))
        greyedOutPath.addLine(to: CGPoint(x: 366, y: 87))
        greyedOutPath.addLine(to: CGPoint(x: 333, y: 95))
        greyedOutPath.addLine(to: CGPoint(x: 301, y: 110))
        greyedOutPath.addLine(to: CGPoint(x: 277, y: 127))
        greyedOutPath.addLine(to: CGPoint(x: 313, y: 175))
        greyedOutPath.addLine(to: CGPoint(x: 136, y: 236))
        greyedOutPath.addLine(to: CGPoint(x: 120, y: 188))
        greyedOutPath.addLine(to: CGPoint(x: 0, y: 229))
        greyedOutPath.addLine(to: CGPoint(x: 65, y: 427))
        greyedOutPath.addLine(to: CGPoint(x: 87, y: 419))
        greyedOutPath.addLine(to: CGPoint(x: 101, y: 459))
        greyedOutPath.addLine(to: CGPoint(x: 271, y: 415))
        greyedOutPath.addLine(to: CGPoint(x: 262, y: 390))
        greyedOutPath.addLine(to: CGPoint(x: 241.37, y: 327.41))
        greyedOutPath.addLine(to: CGPoint(x: 346.05, y: 290.49))
        greyedOutPath.addLine(to: CGPoint(x: 368, y: 353))
        greyedOutPath.addLine(to: CGPoint(x: 630, y: 259))
        greyedOutPath.close()
        greyedOutBackground.setFill()
        greyedOutPath.fill()

        context.restoreGState()


        //// Greyed out 2 Drawing
        context.saveGState()
        context.translateBy(x: 347.7, y: 794.42)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let greyedOut2Path = UIBezierPath()
        greyedOut2Path.move(to: CGPoint(x: 90, y: 0))
        greyedOut2Path.addLine(to: CGPoint(x: 50, y: 15))
        greyedOut2Path.addLine(to: CGPoint(x: 49, y: 200))
        greyedOut2Path.addLine(to: CGPoint(x: 0, y: 200))
        greyedOut2Path.addLine(to: CGPoint(x: 1, y: 318))
        greyedOut2Path.addLine(to: CGPoint(x: 158, y: 321))
        greyedOut2Path.addLine(to: CGPoint(x: 158, y: 238))
        greyedOut2Path.addLine(to: CGPoint(x: 129, y: 238))
        greyedOut2Path.addLine(to: CGPoint(x: 129, y: 97))
        greyedOut2Path.addLine(to: CGPoint(x: 240, y: 97))
        greyedOut2Path.addLine(to: CGPoint(x: 295, y: 262))
        greyedOut2Path.addLine(to: CGPoint(x: 275, y: 269))
        greyedOut2Path.addLine(to: CGPoint(x: 297, y: 334))
        greyedOut2Path.addLine(to: CGPoint(x: 386, y: 303))
        greyedOut2Path.addLine(to: CGPoint(x: 440, y: 465))
        greyedOut2Path.addLine(to: CGPoint(x: 500, y: 444))
        greyedOut2Path.addLine(to: CGPoint(x: 491, y: 418))
        greyedOut2Path.addLine(to: CGPoint(x: 508.5, y: 411.5))
        greyedOut2Path.addLine(to: CGPoint(x: 534.63, y: 493.93))
        greyedOut2Path.addLine(to: CGPoint(x: 546.66, y: 496.83))
        greyedOut2Path.addLine(to: CGPoint(x: 557.66, y: 496.73))
        greyedOut2Path.addLine(to: CGPoint(x: 570.65, y: 495.62))
        greyedOut2Path.addLine(to: CGPoint(x: 582.62, y: 492.51))
        greyedOut2Path.addLine(to: CGPoint(x: 602.55, y: 484.34))
        greyedOut2Path.addLine(to: CGPoint(x: 619.45, y: 472.19))
        greyedOut2Path.addLine(to: CGPoint(x: 631.32, y: 458.09))
        greyedOut2Path.addLine(to: CGPoint(x: 625.16, y: 439.14))
        greyedOut2Path.addLine(to: CGPoint(x: 638.16, y: 439.03))
        greyedOut2Path.addLine(to: CGPoint(x: 656.14, y: 436.87))
        greyedOut2Path.addLine(to: CGPoint(x: 671.1, y: 431.74))
        greyedOut2Path.addLine(to: CGPoint(x: 686.02, y: 423.61))
        greyedOut2Path.addLine(to: CGPoint(x: 698.93, y: 412.5))
        greyedOut2Path.addLine(to: CGPoint(x: 679.41, y: 352.66))
        greyedOut2Path.addLine(to: CGPoint(x: 759.17, y: 324.97))
        greyedOut2Path.addLine(to: CGPoint(x: 721, y: 216))
        greyedOut2Path.addLine(to: CGPoint(x: 636, y: 245))
        greyedOut2Path.addLine(to: CGPoint(x: 617, y: 187))
        greyedOut2Path.addLine(to: CGPoint(x: 480, y: 233))
        greyedOut2Path.addLine(to: CGPoint(x: 426, y: 251))
        greyedOut2Path.addLine(to: CGPoint(x: 430, y: 264))
        greyedOut2Path.addLine(to: CGPoint(x: 398, y: 276))
        greyedOut2Path.addLine(to: CGPoint(x: 325, y: 78))
        greyedOut2Path.addLine(to: CGPoint(x: 196, y: 81))
        greyedOut2Path.addLine(to: CGPoint(x: 183, y: 43))
        greyedOut2Path.addLine(to: CGPoint(x: 113, y: 68))
        greyedOut2Path.addLine(to: CGPoint(x: 90, y: 0))
        greyedOut2Path.close()
        greyedOutBackground.setFill()
        greyedOut2Path.fill()

        context.restoreGState()


        //// Bezier Drawing
        context.saveGState()
        context.translateBy(x: 16.5, y: 13.5)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: 0, y: 229))
        bezierPath.addCurve(to: CGPoint(x: 120, y: 188), controlPoint1: CGPoint(x: 103, y: 194), controlPoint2: CGPoint(x: 120, y: 188))
        bezierPath.addLine(to: CGPoint(x: 136, y: 236))
        bezierPath.addLine(to: CGPoint(x: 313.5, y: 175.5))
        bezierPath.addLine(to: CGPoint(x: 277, y: 127))
        bezierPath.addLine(to: CGPoint(x: 301, y: 110))
        bezierPath.addLine(to: CGPoint(x: 333, y: 95))
        bezierPath.addLine(to: CGPoint(x: 366, y: 87))
        bezierPath.addLine(to: CGPoint(x: 400, y: 84))
        bezierPath.addLine(to: CGPoint(x: 400.5, y: 146.5))
        bezierPath.addLine(to: CGPoint(x: 491.5, y: 114.5))
        bezierPath.addLine(to: CGPoint(x: 463, y: 34))
        bezierPath.addLine(to: CGPoint(x: 562, y: 0))
        bezierPath.addLine(to: CGPoint(x: 611, y: 136))
        bezierPath.addLine(to: CGPoint(x: 590, y: 144))
        bezierPath.addLine(to: CGPoint(x: 630, y: 259))
        bezierPath.addLine(to: CGPoint(x: 380.5, y: 347.5))
        bezierPath.addLine(to: CGPoint(x: 368, y: 352))
        bezierPath.addLine(to: CGPoint(x: 371, y: 360.72))
        bezierPath.addLine(to: CGPoint(x: 505, y: 751))
        bezierPath.addLine(to: CGPoint(x: 521, y: 745))
        bezierPath.addLine(to: CGPoint(x: 544.5, y: 812.5))
        bezierPath.addLine(to: CGPoint(x: 520.5, y: 821.5))
        bezierPath.addLine(to: CGPoint(x: 534, y: 859))
        bezierPath.addLine(to: CGPoint(x: 663, y: 856))
        bezierPath.addLine(to: CGPoint(x: 649, y: 819))
        bezierPath.addLine(to: CGPoint(x: 697, y: 801))
        bezierPath.addLine(to: CGPoint(x: 655.5, y: 688))
        bezierPath.addLine(to: CGPoint(x: 708, y: 669))
        bezierPath.addLine(to: CGPoint(x: 703, y: 655))
        bezierPath.addLine(to: CGPoint(x: 741, y: 641))
        bezierPath.addLine(to: CGPoint(x: 819, y: 863))
        bezierPath.addLine(to: CGPoint(x: 771, y: 880))
        bezierPath.addLine(to: CGPoint(x: 818, y: 1011))
        bezierPath.addLine(to: CGPoint(x: 863.06, y: 995.87))
        bezierPath.addLine(to: CGPoint(x: 955, y: 965))
        bezierPath.addLine(to: CGPoint(x: 974, y: 1023))
        bezierPath.addLine(to: CGPoint(x: 1059, y: 994))
        bezierPath.addLine(to: CGPoint(x: 1035.68, y: 926.94))
        bezierPath.addLine(to: CGPoint(x: 1027, y: 902))
        bezierPath.addLine(to: CGPoint(x: 1112.5, y: 873.5))
        bezierPath.addLine(to: CGPoint(x: 1158.5, y: 1005.5))
        bezierPath.addLine(to: CGPoint(x: 1205, y: 989))
        bezierPath.addLine(to: CGPoint(x: 1283, y: 1211))
        bezierPath.addLine(to: CGPoint(x: 1199, y: 1241))
        bezierPath.addLine(to: CGPoint(x: 1145, y: 1087))
        bezierPath.addLine(to: CGPoint(x: 1017, y: 1131))
        bezierPath.addLine(to: CGPoint(x: 1037, y: 1190))
        bezierPath.addLine(to: CGPoint(x: 1024, y: 1202))
        bezierPath.addLine(to: CGPoint(x: 1009, y: 1210))
        bezierPath.addLine(to: CGPoint(x: 994, y: 1215))
        bezierPath.addLine(to: CGPoint(x: 978, y: 1217))
        bezierPath.addLine(to: CGPoint(x: 963, y: 1217))
        bezierPath.addLine(to: CGPoint(x: 970, y: 1237))
        bezierPath.addLine(to: CGPoint(x: 958, y: 1250))
        bezierPath.addLine(to: CGPoint(x: 941, y: 1262))
        bezierPath.addLine(to: CGPoint(x: 921, y: 1271))
        bezierPath.addLine(to: CGPoint(x: 908.32, y: 1273.99))
        bezierPath.addLine(to: CGPoint(x: 895.51, y: 1275))
        bezierPath.addLine(to: CGPoint(x: 884.87, y: 1274.58))
        bezierPath.addLine(to: CGPoint(x: 873, y: 1272))
        bezierPath.addLine(to: CGPoint(x: 846, y: 1190))
        bezierPath.addLine(to: CGPoint(x: 829, y: 1196))
        bezierPath.addLine(to: CGPoint(x: 838, y: 1222))
        bezierPath.addLine(to: CGPoint(x: 778, y: 1243.5))
        bezierPath.addLine(to: CGPoint(x: 724, y: 1081))
        bezierPath.addLine(to: CGPoint(x: 635, y: 1112))
        bezierPath.addLine(to: CGPoint(x: 613, y: 1047))
        bezierPath.addLine(to: CGPoint(x: 632.5, y: 1040.5))
        bezierPath.addLine(to: CGPoint(x: 578, y: 875))
        bezierPath.addLine(to: CGPoint(x: 466.5, y: 875.5))
        bezierPath.addLine(to: CGPoint(x: 467, y: 1016))
        bezierPath.addLine(to: CGPoint(x: 495.5, y: 1016.5))
        bezierPath.addLine(to: CGPoint(x: 496, y: 1099))
        bezierPath.addLine(to: CGPoint(x: 339, y: 1096))
        bezierPath.addLine(to: CGPoint(x: 338, y: 978))
        bezierPath.addLine(to: CGPoint(x: 387, y: 978))
        bezierPath.addLine(to: CGPoint(x: 388, y: 793))
        bezierPath.addLine(to: CGPoint(x: 382.5, y: 777.5))
        bezierPath.addLine(to: CGPoint(x: 395, y: 773))
        bezierPath.addLine(to: CGPoint(x: 362.47, y: 678.27))
        bezierPath.addLine(to: CGPoint(x: 271, y: 415))
        bezierPath.addLine(to: CGPoint(x: 101, y: 459))
        bezierPath.addLine(to: CGPoint(x: 87, y: 419))
        bezierPath.addLine(to: CGPoint(x: 65, y: 427))
        bezierPath.addLine(to: CGPoint(x: 0, y: 229))
        UIColor.darkGray.setStroke()
        bezierPath.lineWidth = 2
        bezierPath.lineCapStyle = .round
        bezierPath.lineJoinStyle = .round
        bezierPath.stroke()

        context.restoreGState()


        //// Bezier 94 Drawing
        context.saveGState()
        context.translateBy(x: 609.86, y: 891.71)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier94Path = UIBezierPath()
        bezier94Path.move(to: CGPoint(x: 68.5, y: 204.5))
        bezier94Path.addLine(to: CGPoint(x: 0, y: 0))
        bezier94Path.addLine(to: CGPoint(x: 67, y: 0))
        bezier94Path.addLine(to: CGPoint(x: 134.5, y: 181))
        bezier94Path.addLine(to: CGPoint(x: 68.5, y: 204.5))
        bezier94Path.close()
        grass.setFill()
        bezier94Path.fill()

        context.restoreGState()


        //// Bezier 3 Drawing
        context.saveGState()
        context.translateBy(x: 376.02, y: 127.14)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier3Path = UIBezierPath()
        bezier3Path.move(to: CGPoint(x: 0, y: 181))
        bezier3Path.addLine(to: CGPoint(x: 184, y: 116))
        bezier3Path.addLine(to: CGPoint(x: 143, y: 0))
        bezier3Path.addLine(to: CGPoint(x: 131, y: 4))
        UIColor.darkGray.setStroke()
        bezier3Path.lineWidth = 2
        bezier3Path.lineCapStyle = .round
        bezier3Path.lineJoinStyle = .round
        bezier3Path.stroke()

        context.restoreGState()


        //// Bezier 4 Drawing
        context.saveGState()
        context.translateBy(x: 276.25, y: 158.27)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier4Path = UIBezierPath()
        bezier4Path.move(to: CGPoint(x: 0, y: 73))
        bezier4Path.addLine(to: CGPoint(x: 66.5, y: 50))
        bezier4Path.addLine(to: CGPoint(x: 76.5, y: 79))
        bezier4Path.addLine(to: CGPoint(x: 152.5, y: 53))
        bezier4Path.addLine(to: CGPoint(x: 142.5, y: 24))
        bezier4Path.addLine(to: CGPoint(x: 209.5, y: 0))
        bezier4Path.addLine(to: CGPoint(x: 237.5, y: 79))
        bezier4Path.addLine(to: CGPoint(x: 42.5, y: 148))
        bezier4Path.addLine(to: CGPoint(x: 0, y: 73))
        bezier4Path.close()
        grass.setFill()
        bezier4Path.fill()
        UIColor.darkGray.setStroke()
        bezier4Path.lineWidth = 2
        bezier4Path.lineCapStyle = .round
        bezier4Path.lineJoinStyle = .round
        bezier4Path.stroke()

        context.restoreGState()


        //// Bezier 5 Drawing
        context.saveGState()
        context.translateBy(x: 98.65, y: 397.73)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier5Path = UIBezierPath()
        bezier5Path.move(to: CGPoint(x: 0, y: 36))
        bezier5Path.addLine(to: CGPoint(x: 101, y: 0))
        bezier5Path.addLine(to: CGPoint(x: 118, y: 49))
        UIColor.darkGray.setStroke()
        bezier5Path.lineWidth = 2
        bezier5Path.lineCapStyle = .round
        bezier5Path.lineJoinStyle = .round
        bezier5Path.stroke()

        context.restoreGState()


        //// Bezier 6 Drawing
        context.saveGState()
        context.translateBy(x: 149.95, y: 249.17)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier6Path = UIBezierPath()
        bezier6Path.move(to: CGPoint(x: 51, y: 149))
        bezier6Path.addLine(to: CGPoint(x: 0, y: 0))
        UIColor.darkGray.setStroke()
        bezier6Path.lineWidth = 2
        bezier6Path.lineCapStyle = .round
        bezier6Path.lineJoinStyle = .round
        bezier6Path.stroke()

        context.restoreGState()


        //// Bezier 7 Drawing
        context.saveGState()
        context.translateBy(x: 328.46, y: 191.73)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier7Path = UIBezierPath()
        bezier7Path.move(to: CGPoint(x: 14, y: 17))
        bezier7Path.addLine(to: CGPoint(x: 0, y: 0))
        UIColor.darkGray.setStroke()
        bezier7Path.lineWidth = 2
        bezier7Path.lineCapStyle = .round
        bezier7Path.lineJoinStyle = .round
        bezier7Path.stroke()

        context.restoreGState()


        //// Bezier 8 Drawing
        context.saveGState()
        context.translateBy(x: 415.71, y: 163.49)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier8Path = UIBezierPath()
        bezier8Path.move(to: CGPoint(x: 3, y: 20))
        bezier8Path.addLine(to: CGPoint(x: 0, y: 0))
        UIColor.red.setFill()
        bezier8Path.fill()
        UIColor.darkGray.setStroke()
        bezier8Path.lineWidth = 2
        bezier8Path.lineCapStyle = .round
        bezier8Path.lineJoinStyle = .round
        bezier8Path.stroke()

        context.restoreGState()


        //// Bezier 9 Drawing
        context.saveGState()
        context.translateBy(x: 355.57, y: 293.97)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier9Path = UIBezierPath()
        bezier9Path.move(to: CGPoint(x: 26.5, y: 75.8))
        bezier9Path.addLine(to: CGPoint(x: 0, y: 0))
        UIColor.darkGray.setStroke()
        bezier9Path.lineWidth = 2
        bezier9Path.lineCapStyle = .round
        bezier9Path.lineJoinStyle = .round
        bezier9Path.stroke()

        context.restoreGState()


        //// Bezier 10 Drawing
        context.saveGState()
        context.translateBy(x: 208.91, y: 368.69)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier10Path = UIBezierPath()
        bezier10Path.move(to: CGPoint(x: 0, y: 54))
        bezier10Path.addLine(to: CGPoint(x: 52.51, y: 40.42))
        bezier10Path.addLine(to: CGPoint(x: 66.42, y: 36.73))
        UIColor.darkGray.setStroke()
        bezier10Path.lineWidth = 2
        bezier10Path.lineCapStyle = .round
        bezier10Path.lineJoinStyle = .round
        bezier10Path.stroke()

        context.restoreGState()


        //// Bezier 11 Drawing
        context.saveGState()
        context.translateBy(x: 260.55, y: 410.14)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier11Path = UIBezierPath()
        bezier11Path.move(to: CGPoint(x: 0, y: -0))
        bezier11Path.addLine(to: CGPoint(x: 6.67, y: 24.8))
        UIColor.darkGray.setStroke()
        bezier11Path.lineWidth = 2
        bezier11Path.lineCapStyle = .round
        bezier11Path.lineJoinStyle = .round
        bezier11Path.stroke()

        context.restoreGState()


        //// Bezier 12 Drawing
        context.saveGState()
        context.translateBy(x: 265.27, y: 213.18)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier12Path = UIBezierPath()
        bezier12Path.move(to: CGPoint(x: 11, y: 19))
        bezier12Path.addLine(to: CGPoint(x: 0, y: 0))
        UIColor.red.setFill()
        bezier12Path.fill()
        UIColor.darkGray.setStroke()
        bezier12Path.lineWidth = 2
        bezier12Path.lineCapStyle = .round
        bezier12Path.lineJoinStyle = .round
        bezier12Path.stroke()

        context.restoreGState()


        //// Bezier 13 Drawing
        context.saveGState()
        context.translateBy(x: 479.9, y: 142.05)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier13Path = UIBezierPath()
        bezier13Path.move(to: CGPoint(x: 45, y: 4))
        bezier13Path.addLine(to: CGPoint(x: 6, y: 18))
        bezier13Path.addLine(to: CGPoint(x: 0, y: 0))
        UIColor.darkGray.setStroke()
        bezier13Path.lineWidth = 2
        bezier13Path.lineCapStyle = .round
        bezier13Path.lineJoinStyle = .round
        bezier13Path.stroke()

        context.restoreGState()


        //// Bezier 14 Drawing
        context.saveGState()
        context.translateBy(x: 531.93, y: 138.5)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier14Path = UIBezierPath()
        bezier14Path.move(to: CGPoint(x: 0, y: 23))
        bezier14Path.addLine(to: CGPoint(x: 65, y: 0))
        bezier14Path.addLine(to: CGPoint(x: 74, y: 25))
        UIColor.darkGray.setStroke()
        bezier14Path.lineWidth = 2
        bezier14Path.lineCapStyle = .round
        bezier14Path.lineJoinStyle = .round
        bezier14Path.stroke()

        context.restoreGState()


        //// Bezier 15 Drawing
        context.saveGState()
        context.translateBy(x: 151.5, y: 415.19)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier15Path = UIBezierPath()
        bezier15Path.move(to: CGPoint(x: 15, y: 44))
        bezier15Path.addLine(to: CGPoint(x: 0, y: 0))
        UIColor.darkGray.setStroke()
        bezier15Path.lineWidth = 2
        bezier15Path.lineCapStyle = .round
        bezier15Path.lineJoinStyle = .round
        bezier15Path.stroke()

        context.restoreGState()


        //// Bezier 16 Drawing
        context.saveGState()
        context.translateBy(x: 315.7, y: 392.63)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier16Path = UIBezierPath()
        bezier16Path.move(to: CGPoint(x: -21.26, y: -63.44))
        bezier16Path.addLine(to: CGPoint(x: 115.24, y: 336.38))
        UIColor.darkGray.setStroke()
        bezier16Path.lineWidth = 2
        bezier16Path.lineJoinStyle = .round
        bezier16Path.stroke()

        context.restoreGState()


        //// Bezier 17 Drawing
        context.saveGState()
        context.translateBy(x: 351.62, y: 401.94)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier17Path = UIBezierPath()
        bezier17Path.move(to: CGPoint(x: 24.99, y: -44.16))
        bezier17Path.addLine(to: CGPoint(x: -14.89, y: -30.81))
        bezier17Path.addLine(to: CGPoint(x: 64.32, y: 200.22))
        bezier17Path.addLine(to: CGPoint(x: 87.72, y: 270.61))
        bezier17Path.addLine(to: CGPoint(x: 104.5, y: 318))
        bezier17Path.addLine(to: CGPoint(x: 40, y: 340))
        UIColor.darkGray.setStroke()
        bezier17Path.lineWidth = 2
        bezier17Path.lineCapStyle = .round
        bezier17Path.lineJoinStyle = .round
        bezier17Path.stroke()

        context.restoreGState()


        //// Bezier 21 Drawing
        context.saveGState()
        context.translateBy(x: 311.83, y: 500.57)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier21Path = UIBezierPath()
        bezier21Path.move(to: CGPoint(x: 0, y: 14))
        bezier21Path.addLine(to: CGPoint(x: 41, y: 0))
        UIColor.darkGray.setStroke()
        bezier21Path.lineWidth = 2
        bezier21Path.stroke()

        context.restoreGState()


        //// Bezier 22 Drawing
        context.saveGState()
        context.translateBy(x: 320.52, y: 525.68)
        context.rotate(by: 0.5 * CGFloat.pi/180)
        context.scaleBy(x: 0.97, y: 0.97)

        let bezier22Path = UIBezierPath()
        bezier22Path.move(to: CGPoint(x: 0, y: 14))
        bezier22Path.addLine(to: CGPoint(x: 41, y: 0))
        UIColor.darkGray.setStroke()
        bezier22Path.lineWidth = 2
        bezier22Path.stroke()

        context.restoreGState()


        //// Bezier 24 Drawing
        context.saveGState()
        context.translateBy(x: 346.02, y: 599.15)
        context.rotate(by: 0.5 * CGFloat.pi/180)
        context.scaleBy(x: 0.98, y: 0.98)

        let bezier24Path = UIBezierPath()
        bezier24Path.move(to: CGPoint(x: 0, y: 14))
        bezier24Path.addLine(to: CGPoint(x: 40, y: 0))
        UIColor.darkGray.setStroke()
        bezier24Path.lineWidth = 2
        bezier24Path.stroke()

        context.restoreGState()


        //// Bezier 26 Drawing
        context.saveGState()
        context.translateBy(x: 402.12, y: 551.64)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier26Path = UIBezierPath()
        bezier26Path.move(to: CGPoint(x: 0, y: 14))
        bezier26Path.addLine(to: CGPoint(x: 41, y: 0))
        UIColor.darkGray.setStroke()
        bezier26Path.lineWidth = 2
        bezier26Path.stroke()

        context.restoreGState()


        //// Bezier 28 Drawing
        context.saveGState()
        context.translateBy(x: 394.12, y: 527.64)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier28Path = UIBezierPath()
        bezier28Path.move(to: CGPoint(x: 0, y: 14))
        bezier28Path.addLine(to: CGPoint(x: 41, y: 0))
        UIColor.darkGray.setStroke()
        bezier28Path.lineWidth = 2
        bezier28Path.stroke()

        context.restoreGState()


        //// Bezier 29 Drawing
        context.saveGState()
        context.translateBy(x: 385.82, y: 503.21)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier29Path = UIBezierPath()
        bezier29Path.move(to: CGPoint(x: 0, y: 14))
        bezier29Path.addLine(to: CGPoint(x: 41, y: 0))
        UIColor.darkGray.setStroke()
        bezier29Path.lineWidth = 2
        bezier29Path.stroke()

        context.restoreGState()


        //// Bezier 30 Drawing
        context.saveGState()
        context.translateBy(x: 361.41, y: 431.01)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier30Path = UIBezierPath()
        bezier30Path.move(to: CGPoint(x: 0, y: 14))
        bezier30Path.addLine(to: CGPoint(x: 41, y: 0))
        UIColor.darkGray.setStroke()
        bezier30Path.lineWidth = 2
        bezier30Path.stroke()

        context.restoreGState()


        //// Bezier 34 Drawing
        context.saveGState()
        context.translateBy(x: 437.43, y: 767.7)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier34Path = UIBezierPath()
        bezier34Path.move(to: CGPoint(x: 79, y: -0))
        bezier34Path.addLine(to: CGPoint(x: 0, y: 28))
        bezier34Path.addLine(to: CGPoint(x: 23, y: 96))
        bezier34Path.addLine(to: CGPoint(x: 93, y: 71))
        UIColor.darkGray.setStroke()
        bezier34Path.lineWidth = 2
        bezier34Path.lineCapStyle = .round
        bezier34Path.stroke()

        context.restoreGState()


        //// Bezier 35 Drawing
        context.saveGState()
        context.translateBy(x: 398.19, y: 795.36)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier35Path = UIBezierPath()
        bezier35Path.move(to: CGPoint(x: 0, y: 14))
        bezier35Path.addLine(to: CGPoint(x: 39, y: 0))
        UIColor.darkGray.setStroke()
        bezier35Path.lineWidth = 2
        bezier35Path.stroke()

        context.restoreGState()


        //// Bezier 36 Drawing
        context.saveGState()
        context.translateBy(x: 453.34, y: 720.84)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier36Path = UIBezierPath()
        bezier36Path.move(to: CGPoint(x: 0, y: 0))
        bezier36Path.addLine(to: CGPoint(x: 21.5, y: 62))
        UIColor.darkGray.setStroke()
        bezier36Path.lineWidth = 2
        bezier36Path.stroke()

        context.restoreGState()


        //// Bezier 38 Drawing
        context.saveGState()
        context.translateBy(x: 420.6, y: 863.56)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier38Path = UIBezierPath()
        bezier38Path.move(to: CGPoint(x: 54, y: 87))
        bezier38Path.addLine(to: CGPoint(x: 0, y: 87))
        bezier38Path.addLine(to: CGPoint(x: 0, y: 14))
        bezier38Path.addLine(to: CGPoint(x: 39, y: 0))
        UIColor.darkGray.setStroke()
        bezier38Path.lineWidth = 2
        bezier38Path.lineCapStyle = .round
        bezier38Path.lineJoinStyle = .round
        bezier38Path.stroke()

        context.restoreGState()


        //// Bezier 40 Drawing
        context.saveGState()
        context.translateBy(x: 420.34, y: 892.56)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier40Path = UIBezierPath()
        bezier40Path.move(to: CGPoint(x: 55, y: 15))
        bezier40Path.addLine(to: CGPoint(x: 55, y: 0))
        bezier40Path.addLine(to: CGPoint(x: 0, y: 0))
        UIColor.darkGray.setStroke()
        bezier40Path.lineWidth = 2
        bezier40Path.stroke()

        context.restoreGState()


        //// Bezier 41 Drawing
        context.saveGState()
        context.translateBy(x: 396.41, y: 884.35)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier41Path = UIBezierPath()
        bezier41Path.move(to: CGPoint(x: 23, y: 0))
        bezier41Path.addLine(to: CGPoint(x: 0, y: 0))
        UIColor.darkGray.setStroke()
        bezier41Path.lineWidth = 2
        bezier41Path.lineCapStyle = .round
        bezier41Path.lineJoinStyle = .round
        bezier41Path.stroke()

        context.restoreGState()


        //// Bezier 42 Drawing
        context.saveGState()
        context.translateBy(x: 396.19, y: 910.35)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier42Path = UIBezierPath()
        bezier42Path.move(to: CGPoint(x: 23, y: 0))
        bezier42Path.addLine(to: CGPoint(x: 0, y: 0))
        UIColor.darkGray.setStroke()
        bezier42Path.lineWidth = 2
        bezier42Path.lineCapStyle = .round
        bezier42Path.lineJoinStyle = .round
        bezier42Path.stroke()

        context.restoreGState()


        //// Bezier 39 Drawing
        context.saveGState()
        context.translateBy(x: 609.36, y: 891.21)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier39Path = UIBezierPath()
        bezier39Path.move(to: CGPoint(x: 135, y: 182))
        bezier39Path.addLine(to: CGPoint(x: 69, y: 205))
        bezier39Path.addLine(to: CGPoint(x: 0, y: 1))
        bezier39Path.addLine(to: CGPoint(x: 68, y: 0))
        bezier39Path.addLine(to: CGPoint(x: 135, y: 182))
        bezier39Path.addLine(to: CGPoint(x: 198, y: 160))
        bezier39Path.addLine(to: CGPoint(x: 229, y: 250))
        bezier39Path.addLine(to: CGPoint(x: 388, y: 194))
        bezier39Path.addLine(to: CGPoint(x: 373, y: 149))
        UIColor.darkGray.setStroke()
        bezier39Path.lineWidth = 2
        bezier39Path.lineCapStyle = .round
        bezier39Path.lineJoinStyle = .round
        bezier39Path.stroke()

        context.restoreGState()


        //// Bezier 43 Drawing
        context.saveGState()
        context.translateBy(x: 726.72, y: 1080.24)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier43Path = UIBezierPath()
        bezier43Path.move(to: CGPoint(x: 0, y: 22))
        bezier43Path.addLine(to: CGPoint(x: 64, y: 0))
        bezier43Path.addLine(to: CGPoint(x: 80, y: 47))
        bezier43Path.addLine(to: CGPoint(x: 111, y: 140))
        UIColor.darkGray.setStroke()
        bezier43Path.lineWidth = 2
        bezier43Path.lineCapStyle = .round
        bezier43Path.lineJoinStyle = .round
        bezier43Path.stroke()

        context.restoreGState()


        //// Bezier 46 Drawing
        context.saveGState()
        context.translateBy(x: 928.11, y: 1151)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier46Path = UIBezierPath()
        bezier46Path.move(to: CGPoint(x: 42, y: 89))
        bezier46Path.addLine(to: CGPoint(x: 14, y: 5))
        bezier46Path.addLine(to: CGPoint(x: 0, y: 10))
        bezier46Path.addLine(to: CGPoint(x: 28, y: 0))
        UIColor.darkGray.setStroke()
        bezier46Path.lineWidth = 2
        bezier46Path.lineCapStyle = .round
        bezier46Path.lineJoinStyle = .round
        bezier46Path.stroke()

        context.restoreGState()


        //// Bezier 47 Drawing
        context.saveGState()
        context.translateBy(x: 850.17, y: 1143.32)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier47Path = UIBezierPath()
        bezier47Path.move(to: CGPoint(x: 0, y: 60))
        bezier47Path.addLine(to: CGPoint(x: 170, y: 0))
        UIColor.darkGray.setStroke()
        bezier47Path.lineWidth = 2
        bezier47Path.stroke()

        context.restoreGState()


        //// Bezier 48 Drawing
        context.saveGState()
        context.translateBy(x: 845.8, y: 1186.28)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier48Path = UIBezierPath()
        bezier48Path.move(to: CGPoint(x: 7, y: 26))
        bezier48Path.addLine(to: CGPoint(x: 0, y: 4))
        bezier48Path.addLine(to: CGPoint(x: 11, y: 0))
        UIColor.darkGray.setStroke()
        bezier48Path.lineWidth = 2
        bezier48Path.lineCapStyle = .round
        bezier48Path.lineJoinStyle = .round
        bezier48Path.stroke()

        context.restoreGState()


        //// Bezier 49 Drawing
        context.saveGState()
        context.translateBy(x: 1005.29, y: 1130.67)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier49Path = UIBezierPath()
        bezier49Path.move(to: CGPoint(x: 20, y: 27))
        bezier49Path.addLine(to: CGPoint(x: 11, y: 0))
        bezier49Path.addLine(to: CGPoint(x: 0, y: 4))
        UIColor.darkGray.setStroke()
        bezier49Path.lineWidth = 2
        bezier49Path.lineCapStyle = .round
        bezier49Path.lineJoinStyle = .round
        bezier49Path.stroke()

        context.restoreGState()


        //// Bezier 50 Drawing
        context.saveGState()
        context.translateBy(x: 771.15, y: 1030.62)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier50Path = UIBezierPath()
        bezier50Path.move(to: CGPoint(x: 56, y: -0))
        bezier50Path.addLine(to: CGPoint(x: 0, y: 19))
        bezier50Path.addLine(to: CGPoint(x: 4.5, y: 32))
        UIColor.darkGray.setStroke()
        bezier50Path.lineWidth = 2
        bezier50Path.lineCapStyle = .round
        bezier50Path.lineJoinStyle = .round
        bezier50Path.stroke()

        context.restoreGState()


        //// Bezier 51 Drawing
        context.saveGState()
        context.translateBy(x: 825.16, y: 1030.1)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier51Path = UIBezierPath()
        bezier51Path.move(to: CGPoint(x: 155, y: 12))
        bezier51Path.addLine(to: CGPoint(x: 20.5, y: 58.5))
        bezier51Path.addLine(to: CGPoint(x: 0, y: 0))
        UIColor.darkGray.setStroke()
        bezier51Path.lineWidth = 2
        bezier51Path.lineCapStyle = .round
        bezier51Path.lineJoinStyle = .round
        bezier51Path.stroke()

        context.restoreGState()


        //// Bezier 52 Drawing
        context.saveGState()
        context.translateBy(x: 870.78, y: 1016.49)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier52Path = UIBezierPath()
        bezier52Path.move(to: CGPoint(x: 0, y: 0))
        bezier52Path.addLine(to: CGPoint(x: 19.5, y: 57))
        UIColor.darkGray.setStroke()
        bezier52Path.lineWidth = 2
        bezier52Path.stroke()

        context.restoreGState()


        //// Bezier 55 Drawing
        context.saveGState()
        context.translateBy(x: 1074.2, y: 912.26)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier55Path = UIBezierPath()
        bezier55Path.move(to: CGPoint(x: 0, y: 0))
        bezier55Path.addLine(to: CGPoint(x: 70.55, y: 200.13))
        UIColor.darkGray.setStroke()
        bezier55Path.lineWidth = 2
        bezier55Path.stroke()

        context.restoreGState()


        //// Bezier 56 Drawing
        context.saveGState()
        context.translateBy(x: 1084.23, y: 908.35)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier56Path = UIBezierPath()
        bezier56Path.move(to: CGPoint(x: 0, y: 0))
        bezier56Path.addLine(to: CGPoint(x: 49.05, y: 137.97))
        bezier56Path.addLine(to: CGPoint(x: 84.87, y: 125.5))
        bezier56Path.addLine(to: CGPoint(x: 82, y: 116.94))
        UIColor.darkGray.setStroke()
        bezier56Path.lineWidth = 2
        bezier56Path.lineCapStyle = .round
        bezier56Path.lineJoinStyle = .round
        bezier56Path.stroke()

        context.restoreGState()


        //// Bezier 58 Drawing
        context.saveGState()
        context.translateBy(x: 1053.79, y: 962.07)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier58Path = UIBezierPath()
        bezier58Path.move(to: CGPoint(x: 37, y: 0))
        bezier58Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier58Path.lineWidth = 2
        bezier58Path.lineCapStyle = .round
        bezier58Path.stroke()

        context.restoreGState()


        //// Bezier 59 Drawing
        context.saveGState()
        context.translateBy(x: 1061.6, y: 985.14)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier59Path = UIBezierPath()
        bezier59Path.move(to: CGPoint(x: 37, y: 0))
        bezier59Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier59Path.lineWidth = 2
        bezier59Path.lineCapStyle = .round
        bezier59Path.stroke()

        context.restoreGState()


        //// Bezier 61 Drawing
        context.saveGState()
        context.translateBy(x: 1076.22, y: 1028.76)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier61Path = UIBezierPath()
        bezier61Path.move(to: CGPoint(x: 38, y: 0))
        bezier61Path.addLine(to: CGPoint(x: 0, y: 13.5))
        UIColor.darkGray.setStroke()
        bezier61Path.lineWidth = 2
        bezier61Path.stroke()

        context.restoreGState()


        //// Bezier 62 Drawing
        context.saveGState()
        context.translateBy(x: 1109.75, y: 969.06)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier62Path = UIBezierPath()
        bezier62Path.move(to: CGPoint(x: 36, y: 0))
        bezier62Path.addLine(to: CGPoint(x: 0, y: 12.5))
        UIColor.darkGray.setStroke()
        bezier62Path.lineWidth = 2
        bezier62Path.stroke()

        context.restoreGState()


        //// Bezier 63 Drawing
        context.saveGState()
        context.translateBy(x: 1101.93, y: 946)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier63Path = UIBezierPath()
        bezier63Path.move(to: CGPoint(x: 36, y: 0))
        bezier63Path.addLine(to: CGPoint(x: 0, y: 12.5))
        UIColor.darkGray.setStroke()
        bezier63Path.lineWidth = 2
        bezier63Path.stroke()

        context.restoreGState()


        //// Bezier 64 Drawing
        context.saveGState()
        context.translateBy(x: 1116.56, y: 991.62)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier64Path = UIBezierPath()
        bezier64Path.move(to: CGPoint(x: 37, y: 0))
        bezier64Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier64Path.lineWidth = 2
        bezier64Path.stroke()

        context.restoreGState()


        //// Bezier 65 Drawing
        context.saveGState()
        context.translateBy(x: 1125.37, y: 1012.69)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier65Path = UIBezierPath()
        bezier65Path.move(to: CGPoint(x: 36, y: 0))
        bezier65Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier65Path.lineWidth = 2
        bezier65Path.stroke()

        context.restoreGState()


        //// Bezier 66 Drawing
        context.saveGState()
        context.translateBy(x: 1180.29, y: 1074.2)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier66Path = UIBezierPath()
        bezier66Path.move(to: CGPoint(x: 0.73, y: 1.8))
        bezier66Path.addLine(to: CGPoint(x: 61.5, y: 177))
        UIColor.darkGray.setStroke()
        bezier66Path.lineWidth = 2
        bezier66Path.lineCapStyle = .round
        bezier66Path.lineJoinStyle = .round
        bezier66Path.stroke()

        context.restoreGState()


        //// Bezier 67 Drawing
        context.saveGState()
        context.translateBy(x: 1200.63, y: 1092.37)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier67Path = UIBezierPath()
        bezier67Path.move(to: CGPoint(x: -22.21, y: -66.18))
        bezier67Path.addLine(to: CGPoint(x: 54, y: 155))
        UIColor.darkGray.setStroke()
        bezier67Path.lineWidth = 2
        bezier67Path.lineCapStyle = .round
        bezier67Path.stroke()

        context.restoreGState()


        //// Bezier 68 Drawing
        context.saveGState()
        context.translateBy(x: 1150.74, y: 1079.94)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier68Path = UIBezierPath()
        bezier68Path.move(to: CGPoint(x: 0, y: 31))
        bezier68Path.addLine(to: CGPoint(x: 85, y: 0))
        UIColor.darkGray.setStroke()
        bezier68Path.lineWidth = 2
        bezier68Path.stroke()

        context.restoreGState()


        //// Bezier 69 Drawing
        context.saveGState()
        context.translateBy(x: 1166.22, y: 1139.08)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier69Path = UIBezierPath()
        bezier69Path.move(to: CGPoint(x: 36, y: 0))
        bezier69Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier69Path.lineWidth = 2
        bezier69Path.stroke()

        context.restoreGState()


        //// Bezier 70 Drawing
        context.saveGState()
        context.translateBy(x: 1180.83, y: 1184.21)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier70Path = UIBezierPath()
        bezier70Path.move(to: CGPoint(x: 36, y: 0))
        bezier70Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier70Path.lineWidth = 2
        bezier70Path.stroke()

        context.restoreGState()


        //// Bezier 71 Drawing
        context.saveGState()
        context.translateBy(x: 1188.64, y: 1206.27)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier71Path = UIBezierPath()
        bezier71Path.move(to: CGPoint(x: 36, y: 0))
        bezier71Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier71Path.lineWidth = 2
        bezier71Path.stroke()

        context.restoreGState()


        //// Bezier 72 Drawing
        context.saveGState()
        context.translateBy(x: 1197.44, y: 1228.85)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier72Path = UIBezierPath()
        bezier72Path.move(to: CGPoint(x: 35, y: 0))
        bezier72Path.addLine(to: CGPoint(x: 0, y: 12.5))
        UIColor.darkGray.setStroke()
        bezier72Path.lineWidth = 2
        bezier72Path.stroke()

        context.restoreGState()


        //// Bezier 73 Drawing
        context.saveGState()
        context.translateBy(x: 1244.59, y: 1211.76)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier73Path = UIBezierPath()
        bezier73Path.move(to: CGPoint(x: 36, y: 0))
        bezier73Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier73Path.lineWidth = 2
        bezier73Path.stroke()

        context.restoreGState()


        //// Bezier 74 Drawing
        context.saveGState()
        context.translateBy(x: 1237.79, y: 1188.7)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier74Path = UIBezierPath()
        bezier74Path.move(to: CGPoint(x: 35, y: 0))
        bezier74Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier74Path.lineWidth = 2
        bezier74Path.stroke()

        context.restoreGState()


        //// Bezier 75 Drawing
        context.saveGState()
        context.translateBy(x: 1229.98, y: 1166.63)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier75Path = UIBezierPath()
        bezier75Path.move(to: CGPoint(x: 36, y: 0))
        bezier75Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier75Path.lineWidth = 2
        bezier75Path.stroke()

        context.restoreGState()


        //// Bezier 76 Drawing
        context.saveGState()
        context.translateBy(x: 1222.18, y: 1144.56)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier76Path = UIBezierPath()
        bezier76Path.move(to: CGPoint(x: 36, y: 0))
        bezier76Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier76Path.lineWidth = 2
        bezier76Path.stroke()

        context.restoreGState()


        //// Bezier 77 Drawing
        context.saveGState()
        context.translateBy(x: 1215.37, y: 1122.5)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier77Path = UIBezierPath()
        bezier77Path.move(to: CGPoint(x: 36, y: 0))
        bezier77Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier77Path.lineWidth = 2
        bezier77Path.stroke()

        context.restoreGState()


        //// Bezier 78 Drawing
        context.saveGState()
        context.translateBy(x: 1207.56, y: 1100.44)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier78Path = UIBezierPath()
        bezier78Path.move(to: CGPoint(x: 36, y: 0))
        bezier78Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier78Path.lineWidth = 2
        bezier78Path.stroke()

        context.restoreGState()


        //// Bezier 83 Drawing
        context.saveGState()
        context.translateBy(x: 694.94, y: 824.95)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier83Path = UIBezierPath()
        bezier83Path.move(to: CGPoint(x: 81.99, y: 221.34))
        bezier83Path.addLine(to: CGPoint(x: 0, y: 0))
        UIColor.darkGray.setStroke()
        bezier83Path.lineWidth = 2
        bezier83Path.lineCapStyle = .round
        bezier83Path.lineJoinStyle = .round
        bezier83Path.stroke()

        context.restoreGState()


        //// Bezier 87 Drawing
        context.saveGState()
        context.translateBy(x: 715.47, y: 879.54)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier87Path = UIBezierPath()
        bezier87Path.move(to: CGPoint(x: 72.95, y: 162.83))
        bezier87Path.addLine(to: CGPoint(x: 12.5, y: 0))
        UIColor.darkGray.setStroke()
        bezier87Path.lineWidth = 2
        bezier87Path.lineCapStyle = .round
        bezier87Path.lineJoinStyle = .round
        bezier87Path.stroke()

        context.restoreGState()


        //// Bezier 90 Drawing
        context.saveGState()
        context.translateBy(x: 738.4, y: 887.73)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier90Path = UIBezierPath()
        bezier90Path.move(to: CGPoint(x: 42, y: 13.6))
        bezier90Path.addLine(to: CGPoint(x: 37, y: 0))
        bezier90Path.addLine(to: CGPoint(x: -1.99, y: 14.1))
        UIColor.darkGray.setStroke()
        bezier90Path.lineWidth = 2
        bezier90Path.lineCapStyle = .round
        bezier90Path.lineJoinStyle = .round
        bezier90Path.stroke()

        context.restoreGState()


        //// Bezier 91 Drawing
        context.saveGState()
        context.translateBy(x: 767.58, y: 866.59)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier91Path = UIBezierPath()
        bezier91Path.move(to: CGPoint(x: 0, y: 0))
        bezier91Path.addLine(to: CGPoint(x: 8.2, y: 22))
        UIColor.darkGray.setStroke()
        bezier91Path.lineWidth = 2
        bezier91Path.lineCapStyle = .round
        bezier91Path.stroke()

        context.restoreGState()


        //// Bezier 92 Drawing
        context.saveGState()
        context.translateBy(x: 718.44, y: 688.15)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier92Path = UIBezierPath()
        bezier92Path.move(to: CGPoint(x: 0, y: 0))
        bezier92Path.addLine(to: CGPoint(x: 74.5, y: 207))
        UIColor.darkGray.setStroke()
        bezier92Path.lineWidth = 2
        bezier92Path.lineCapStyle = .round
        bezier92Path.stroke()

        context.restoreGState()


        //// Bezier 93 Drawing
        context.saveGState()
        context.translateBy(x: 706.39, y: 694.05)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier93Path = UIBezierPath()
        bezier93Path.move(to: CGPoint(x: 0, y: 0))
        bezier93Path.addLine(to: CGPoint(x: 53.7, y: 150.1))
        bezier93Path.addLine(to: CGPoint(x: 15.6, y: 164))
        bezier93Path.addLine(to: CGPoint(x: 1, y: 126))
        UIColor.darkGray.setStroke()
        bezier93Path.lineWidth = 2
        bezier93Path.lineCapStyle = .round
        bezier93Path.lineJoinStyle = .round
        bezier93Path.stroke()

        context.restoreGState()


        //// Bezier 95 Drawing
        context.saveGState()
        context.translateBy(x: 705.24, y: 801.01)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier95Path = UIBezierPath()
        bezier95Path.move(to: CGPoint(x: 38, y: 0))
        bezier95Path.addLine(to: CGPoint(x: 0, y: 14))
        UIColor.darkGray.setStroke()
        bezier95Path.lineWidth = 2
        bezier95Path.lineCapStyle = .round
        bezier95Path.stroke()

        context.restoreGState()


        //// Bezier 96 Drawing
        context.saveGState()
        context.translateBy(x: 694.43, y: 768.94)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier96Path = UIBezierPath()
        bezier96Path.move(to: CGPoint(x: 38, y: 0))
        bezier96Path.addLine(to: CGPoint(x: 0, y: 14))
        UIColor.darkGray.setStroke()
        bezier96Path.lineWidth = 2
        bezier96Path.lineCapStyle = .round
        bezier96Path.stroke()

        context.restoreGState()


        //// Bezier 97 Drawing
        context.saveGState()
        context.translateBy(x: 685.63, y: 744.87)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier97Path = UIBezierPath()
        bezier97Path.move(to: CGPoint(x: 38, y: 0))
        bezier97Path.addLine(to: CGPoint(x: 0, y: 14))
        UIColor.darkGray.setStroke()
        bezier97Path.lineWidth = 2
        bezier97Path.lineCapStyle = .round
        bezier97Path.stroke()

        context.restoreGState()


        //// Bezier 98 Drawing
        context.saveGState()
        context.translateBy(x: 737.81, y: 726.31)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier98Path = UIBezierPath()
        bezier98Path.move(to: CGPoint(x: 38, y: 0))
        bezier98Path.addLine(to: CGPoint(x: 0, y: 14))
        UIColor.darkGray.setStroke()
        bezier98Path.lineWidth = 2
        bezier98Path.stroke()

        context.restoreGState()


        //// Bezier 99 Drawing
        context.saveGState()
        context.translateBy(x: 749.61, y: 763.38)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier99Path = UIBezierPath()
        bezier99Path.move(to: CGPoint(x: 38, y: 0))
        bezier99Path.addLine(to: CGPoint(x: 0, y: 14))
        UIColor.darkGray.setStroke()
        bezier99Path.lineWidth = 2
        bezier99Path.stroke()

        context.restoreGState()


        //// Bezier 102 Drawing
        context.saveGState()
        context.translateBy(x: 772.11, y: 826.69)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier102Path = UIBezierPath()
        bezier102Path.move(to: CGPoint(x: 36, y: 0))
        bezier102Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier102Path.lineWidth = 2
        bezier102Path.lineCapStyle = .round
        bezier102Path.stroke()

        context.restoreGState()


        //// Bezier 105 Drawing
        context.saveGState()
        context.translateBy(x: 711.98, y: 821.1)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier105Path = UIBezierPath()
        bezier105Path.move(to: CGPoint(x: 39, y: 0))
        bezier105Path.addLine(to: CGPoint(x: 0, y: 14))
        UIColor.darkGray.setStroke()
        bezier105Path.lineWidth = 2
        bezier105Path.stroke()

        context.restoreGState()


        //// Bezier 106 Drawing
        context.saveGState()
        context.translateBy(x: 362.44, y: 308.03)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier106Path = UIBezierPath()
        bezier106Path.move(to: CGPoint(x: 0, y: 4))
        bezier106Path.addLine(to: CGPoint(x: 12, y: 0))
        UIColor.darkGray.setStroke()
        bezier106Path.lineWidth = 2
        bezier106Path.stroke()

        context.restoreGState()


        //// Bezier 2 Drawing
        context.saveGState()
        context.translateBy(x: 732.21, y: 278.76)
        context.rotate(by: 1.1 * CGFloat.pi/180)
        context.scaleBy(x: 1.08, y: 1.08)

        let bezier2Path = UIBezierPath()
        bezier2Path.move(to: CGPoint(x: 0, y: 34))
        bezier2Path.addLine(to: CGPoint(x: 95, y: 297.5))
        bezier2Path.addLine(to: CGPoint(x: 187, y: 264))
        bezier2Path.addLine(to: CGPoint(x: 123.64, y: 89.76))
        bezier2Path.addLine(to: CGPoint(x: 91, y: 0))
        bezier2Path.addLine(to: CGPoint(x: 0, y: 34))
        bezier2Path.close()
        background.setFill()
        bezier2Path.fill()
        UIColor.darkGray.setStroke()
        bezier2Path.lineWidth = 2
        bezier2Path.lineCapStyle = .round
        bezier2Path.lineJoinStyle = .round
        bezier2Path.stroke()

        context.restoreGState()


        //// Bezier 107 Drawing
        context.saveGState()
        context.translateBy(x: 837.8, y: 377.46)
        context.rotate(by: 1.1 * CGFloat.pi/180)
        context.scaleBy(x: 1.08, y: 1.08)

        let bezier107Path = UIBezierPath()
        bezier107Path.move(to: CGPoint(x: 24, y: 0))
        bezier107Path.addLine(to: CGPoint(x: 0, y: 9))
        bezier107Path.addLine(to: CGPoint(x: 9, y: 34))
        UIColor.darkGray.setStroke()
        bezier107Path.lineWidth = 2
        bezier107Path.lineCapStyle = .round
        bezier107Path.lineJoinStyle = .round
        bezier107Path.stroke()

        context.restoreGState()


        //// Bezier 113 Drawing
        context.saveGState()
        context.translateBy(x: 814.5, y: 536.36)
        context.rotate(by: 1.1 * CGFloat.pi/180)
        context.scaleBy(x: 1.08, y: 1.08)

        let bezier113Path = UIBezierPath()
        bezier113Path.move(to: CGPoint(x: 90.98, y: -12.27))
        bezier113Path.addLine(to: CGPoint(x: 0, y: 20.7))
        UIColor.darkGray.setStroke()
        bezier113Path.lineWidth = 2
        bezier113Path.lineCapStyle = .round
        bezier113Path.lineJoinStyle = .round
        bezier113Path.stroke()

        context.restoreGState()


        //// Bezier 114 Drawing
        context.saveGState()
        context.translateBy(x: 874.08, y: 530.75)
        context.rotate(by: 1.1 * CGFloat.pi/180)
        context.scaleBy(x: 1.08, y: 1.08)

        let bezier114Path = UIBezierPath()
        bezier114Path.move(to: CGPoint(x: 16.5, y: 46))
        bezier114Path.addLine(to: CGPoint(x: 1.88, y: 5.75))
        UIColor.darkGray.setStroke()
        bezier114Path.lineWidth = 2
        bezier114Path.stroke()

        context.restoreGState()


        //// Bezier 116 Drawing
        context.saveGState()
        context.translateBy(x: 844.37, y: 440.24)
        context.rotate(by: 1.1 * CGFloat.pi/180)
        context.scaleBy(x: 1.08, y: 1.08)

        let bezier116Path = UIBezierPath()
        bezier116Path.move(to: CGPoint(x: 23.98, y: 65.07))
        bezier116Path.addLine(to: CGPoint(x: -3.28, y: -8.49))
        bezier116Path.addLine(to: CGPoint(x: -29.95, y: 1.28))
        bezier116Path.addLine(to: CGPoint(x: -3.53, y: 74.86))
        bezier116Path.addLine(to: CGPoint(x: 23.98, y: 65.07))
        bezier116Path.close()
        UIColor.darkGray.setStroke()
        bezier116Path.lineWidth = 2
        bezier116Path.lineCapStyle = .round
        bezier116Path.lineJoinStyle = .round
        bezier116Path.stroke()

        context.restoreGState()


        //// Bezier 115 Drawing
        context.saveGState()
        context.translateBy(x: 804.9, y: 290.41)
        context.rotate(by: 1.1 * CGFloat.pi/180)
        context.scaleBy(x: 1.08, y: 1.08)

        let bezier115Path = UIBezierPath()
        bezier115Path.move(to: CGPoint(x: 32, y: 89))
        bezier115Path.addLine(to: CGPoint(x: 0, y: 0))
        UIColor.darkGray.setStroke()
        bezier115Path.lineWidth = 2
        bezier115Path.stroke()

        context.restoreGState()


        //// Bezier 117 Drawing
        context.saveGState()
        context.translateBy(x: 821.17, y: 325.91)
        context.rotate(by: 1.1 * CGFloat.pi/180)
        context.scaleBy(x: 1.08, y: 1.08)

        let bezier117Path = UIBezierPath()
        bezier117Path.move(to: CGPoint(x: 0, y: 8))
        bezier117Path.addLine(to: CGPoint(x: 22, y: 0))
        UIColor.darkGray.setStroke()
        bezier117Path.lineWidth = 2
        bezier117Path.lineCapStyle = .round
        bezier117Path.lineJoinStyle = .round
        bezier117Path.stroke()

        context.restoreGState()


        //// Bezier 118 Drawing
        context.saveGState()
        context.translateBy(x: 812.17, y: 298.91)
        context.rotate(by: 1.1 * CGFloat.pi/180)
        context.scaleBy(x: 1.08, y: 1.08)

        let bezier118Path = UIBezierPath()
        bezier118Path.move(to: CGPoint(x: 0, y: 8))
        bezier118Path.addLine(to: CGPoint(x: 22, y: 0))
        UIColor.darkGray.setStroke()
        bezier118Path.lineWidth = 2
        bezier118Path.lineCapStyle = .round
        bezier118Path.lineJoinStyle = .round
        bezier118Path.stroke()

        context.restoreGState()


        //// Bezier 120 Drawing
        context.saveGState()
        context.translateBy(x: 785.39, y: 344.49)
        context.rotate(by: 1.1 * CGFloat.pi/180)
        context.scaleBy(x: 1.08, y: 1.08)

        let bezier120Path = UIBezierPath()
        bezier120Path.move(to: CGPoint(x: -10.3, y: 12.71))
        bezier120Path.addLine(to: CGPoint(x: 24, y: 0))
        bezier120Path.addLine(to: CGPoint(x: 7.07, y: -46.9))
        UIColor.darkGray.setStroke()
        bezier120Path.lineWidth = 2
        bezier120Path.lineCapStyle = .round
        bezier120Path.lineJoinStyle = .round
        bezier120Path.stroke()

        context.restoreGState()


        //// Bezier 121 Drawing
        context.saveGState()
        context.translateBy(x: 792.67, y: 365.04)
        context.rotate(by: 1.1 * CGFloat.pi/180)
        context.scaleBy(x: 1.08, y: 1.08)

        let bezier121Path = UIBezierPath()
        bezier121Path.move(to: CGPoint(x: 39, y: 42.5))
        bezier121Path.addLine(to: CGPoint(x: 13.34, y: 51.57))
        bezier121Path.addLine(to: CGPoint(x: -1.83, y: 9.66))
        bezier121Path.addLine(to: CGPoint(x: 24, y: 0))
        bezier121Path.addLine(to: CGPoint(x: 39, y: 42.5))
        bezier121Path.close()
        UIColor.darkGray.setStroke()
        bezier121Path.lineWidth = 2
        bezier121Path.lineCapStyle = .round
        bezier121Path.lineJoinStyle = .round
        bezier121Path.stroke()

        context.restoreGState()


        //// Bezier 122 Drawing
        context.saveGState()
        context.translateBy(x: 815.82, y: 396.91)
        context.rotate(by: 1.1 * CGFloat.pi/180)
        context.scaleBy(x: 1.08, y: 1.08)

        let bezier122Path = UIBezierPath()
        bezier122Path.move(to: CGPoint(x: 4.5, y: 17.36))
        bezier122Path.addLine(to: CGPoint(x: 0, y: 4.6))
        bezier122Path.addLine(to: CGPoint(x: 11.57, y: 0.52))
        UIColor.darkGray.setStroke()
        bezier122Path.lineWidth = 2
        bezier122Path.lineCapStyle = .round
        bezier122Path.lineJoinStyle = .round
        bezier122Path.stroke()

        context.restoreGState()


        //// Bezier 32 Drawing
        context.saveGState()
        context.translateBy(x: 418.12, y: 601.64)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier32Path = UIBezierPath()
        bezier32Path.move(to: CGPoint(x: 0, y: 14))
        bezier32Path.addLine(to: CGPoint(x: 41, y: 0))
        UIColor.darkGray.setStroke()
        bezier32Path.lineWidth = 2
        bezier32Path.stroke()

        context.restoreGState()


        //// Bezier 33 Drawing
        context.saveGState()
        context.translateBy(x: 426.12, y: 626.64)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier33Path = UIBezierPath()
        bezier33Path.move(to: CGPoint(x: 0, y: 14))
        bezier33Path.addLine(to: CGPoint(x: 41, y: 0))
        UIColor.darkGray.setStroke()
        bezier33Path.lineWidth = 2
        bezier33Path.stroke()

        context.restoreGState()


        //// Bezier 128 Drawing
        context.saveGState()
        context.translateBy(x: 458.97, y: 723.34)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier128Path = UIBezierPath()
        bezier128Path.move(to: CGPoint(x: 0, y: 14.5))
        bezier128Path.addLine(to: CGPoint(x: 41, y: 0))
        UIColor.darkGray.setStroke()
        bezier128Path.lineWidth = 2
        bezier128Path.stroke()

        context.restoreGState()


        //// Bezier 23 Drawing
        context.saveGState()
        context.translateBy(x: 370.12, y: 455.64)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier23Path = UIBezierPath()
        bezier23Path.move(to: CGPoint(x: 0, y: 14))
        bezier23Path.addLine(to: CGPoint(x: 41, y: 0))
        UIColor.darkGray.setStroke()
        bezier23Path.lineWidth = 2
        bezier23Path.stroke()

        context.restoreGState()


        //// Bezier 19 Drawing
        context.saveGState()
        context.translateBy(x: 275.58, y: 406.28)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier19Path = UIBezierPath()
        bezier19Path.move(to: CGPoint(x: 9, y: 26))
        bezier19Path.addLine(to: CGPoint(x: -21.13, y: -63.09))
        bezier19Path.addLine(to: CGPoint(x: 83.55, y: -100.01))
        UIColor.darkGray.setStroke()
        bezier19Path.lineWidth = 2
        bezier19Path.stroke()

        context.restoreGState()


        //// Bezier 20 Drawing
        context.saveGState()
        context.translateBy(x: 342.53, y: 470.36)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier20Path = UIBezierPath()
        UIColor.black.setStroke()
        bezier20Path.lineWidth = 1
        bezier20Path.stroke()

        context.restoreGState()


        //// Bezier 131 Drawing
        context.saveGState()
        context.translateBy(x: 1174.04, y: 1160.14)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier131Path = UIBezierPath()
        bezier131Path.move(to: CGPoint(x: 36, y: 0))
        bezier131Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier131Path.lineWidth = 2
        bezier131Path.stroke()

        context.restoreGState()


        //// Bezier 132 Drawing
        context.saveGState()
        context.translateBy(x: 837.68, y: 1142.71)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier132Path = UIBezierPath()
        UIColor.black.setStroke()
        bezier132Path.lineWidth = 1
        bezier132Path.stroke()

        context.restoreGState()


        //// Bezier 138 Drawing
        context.saveGState()
        context.translateBy(x: 1080.92, y: 1058.33)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier138Path = UIBezierPath()
        bezier138Path.move(to: CGPoint(x: 23.67, y: 67.47))
        bezier138Path.addLine(to: CGPoint(x: 0, y: 0))
        UIColor.darkGray.setStroke()
        bezier138Path.lineWidth = 2
        bezier138Path.stroke()

        context.restoreGState()


        //// Bezier 140 Drawing
        context.saveGState()
        context.translateBy(x: 1093.11, y: 922.68)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier140Path = UIBezierPath()
        bezier140Path.move(to: CGPoint(x: 37, y: 0))
        bezier140Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier140Path.lineWidth = 2
        bezier140Path.stroke()

        context.restoreGState()


        //// Bezier 57 Drawing
        context.saveGState()
        context.translateBy(x: 1193.94, y: 1058.81)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier57Path = UIBezierPath()
        bezier57Path.move(to: CGPoint(x: 35, y: 0))
        bezier57Path.addLine(to: CGPoint(x: 0, y: 12.5))
        UIColor.darkGray.setStroke()
        bezier57Path.lineWidth = 2
        bezier57Path.stroke()

        context.restoreGState()


        //// Bezier 85 Drawing
        context.saveGState()
        context.translateBy(x: 677.86, y: 891.3)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier85Path = UIBezierPath()
        UIColor.black.setStroke()
        bezier85Path.lineWidth = 1
        bezier85Path.stroke()

        context.restoreGState()


        //// Bezier 86 Drawing
        context.saveGState()
        context.translateBy(x: 671.52, y: 873.75)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier86Path = UIBezierPath()
        bezier86Path.move(to: CGPoint(x: 6, y: 18))
        bezier86Path.addLine(to: CGPoint(x: 0, y: 0))
        UIColor.darkGray.setStroke()
        bezier86Path.lineWidth = 2
        bezier86Path.lineCapStyle = .round
        bezier86Path.lineJoinStyle = .round
        bezier86Path.stroke()

        context.restoreGState()


        //// Bezier 27 Drawing
        context.saveGState()
        context.translateBy(x: 305.12, y: 476.64)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier27Path = UIBezierPath()
        bezier27Path.move(to: CGPoint(x: 0, y: 14))
        bezier27Path.addLine(to: CGPoint(x: 38.89, y: 1.02))
        UIColor.darkGray.setStroke()
        bezier27Path.lineWidth = 2
        bezier27Path.stroke()

        context.restoreGState()


        //// Bezier 25 Drawing
        context.saveGState()
        context.translateBy(x: 337.12, y: 573.94)
        context.rotate(by: 0.5 * CGFloat.pi/180)
        context.scaleBy(x: 0.98, y: 0.98)

        let bezier25Path = UIBezierPath()
        bezier25Path.move(to: CGPoint(x: 0, y: 14))
        bezier25Path.addLine(to: CGPoint(x: 40, y: 0))
        UIColor.darkGray.setStroke()
        bezier25Path.lineWidth = 2
        bezier25Path.lineCapStyle = .round
        bezier25Path.stroke()

        context.restoreGState()


        //// Bezier 31 Drawing
        context.saveGState()
        context.translateBy(x: 329.12, y: 549.94)
        context.rotate(by: 0.5 * CGFloat.pi/180)
        context.scaleBy(x: 0.98, y: 0.98)

        let bezier31Path = UIBezierPath()
        bezier31Path.move(to: CGPoint(x: 0, y: 14))
        bezier31Path.addLine(to: CGPoint(x: 40, y: 0))
        UIColor.darkGray.setStroke()
        bezier31Path.lineWidth = 2
        bezier31Path.lineCapStyle = .round
        bezier31Path.stroke()

        context.restoreGState()


        //// Bezier 37 Drawing
        context.saveGState()
        context.translateBy(x: 296.12, y: 452.64)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier37Path = UIBezierPath()
        bezier37Path.move(to: CGPoint(x: 0, y: 14))
        bezier37Path.addLine(to: CGPoint(x: 41, y: 0))
        UIColor.darkGray.setStroke()
        bezier37Path.lineWidth = 2
        bezier37Path.stroke()

        context.restoreGState()


        //// Bezier 18 Drawing
        context.saveGState()
        context.translateBy(x: 354.12, y: 623.94)
        context.rotate(by: 0.5 * CGFloat.pi/180)
        context.scaleBy(x: 0.98, y: 0.98)

        let bezier18Path = UIBezierPath()
        bezier18Path.move(to: CGPoint(x: 0, y: 14))
        bezier18Path.addLine(to: CGPoint(x: 40, y: 0))
        UIColor.darkGray.setStroke()
        bezier18Path.lineWidth = 2
        bezier18Path.stroke()

        context.restoreGState()


        //// Bezier 100 Drawing
        context.saveGState()
        context.translateBy(x: 362.12, y: 647.94)
        context.rotate(by: 0.5 * CGFloat.pi/180)
        context.scaleBy(x: 0.98, y: 0.98)

        let bezier100Path = UIBezierPath()
        bezier100Path.move(to: CGPoint(x: 0, y: 14))
        bezier100Path.addLine(to: CGPoint(x: 40, y: 0))
        UIColor.darkGray.setStroke()
        bezier100Path.lineWidth = 2
        bezier100Path.stroke()

        context.restoreGState()


        //// Bezier 101 Drawing
        context.saveGState()
        context.translateBy(x: 370.12, y: 672.94)
        context.rotate(by: 0.5 * CGFloat.pi/180)
        context.scaleBy(x: 0.98, y: 0.98)

        let bezier101Path = UIBezierPath()
        bezier101Path.move(to: CGPoint(x: 0, y: 14))
        bezier101Path.addLine(to: CGPoint(x: 40, y: 0))
        UIColor.darkGray.setStroke()
        bezier101Path.lineWidth = 2
        bezier101Path.stroke()

        context.restoreGState()


        //// Bezier 103 Drawing
        context.saveGState()
        context.translateBy(x: 287.12, y: 428.64)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier103Path = UIBezierPath()
        bezier103Path.move(to: CGPoint(x: 0, y: 14))
        bezier103Path.addLine(to: CGPoint(x: 41, y: 0))
        UIColor.darkGray.setStroke()
        bezier103Path.lineWidth = 2
        bezier103Path.stroke()

        context.restoreGState()


        //// Bezier 104 Drawing
        context.saveGState()
        context.translateBy(x: 279.12, y: 404.64)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier104Path = UIBezierPath()
        bezier104Path.move(to: CGPoint(x: 0, y: 14))
        bezier104Path.addLine(to: CGPoint(x: 41, y: 0))
        UIColor.darkGray.setStroke()
        bezier104Path.lineWidth = 2
        bezier104Path.stroke()

        context.restoreGState()


        //// Bezier 126 Drawing
        context.saveGState()
        context.translateBy(x: 271.12, y: 378.64)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier126Path = UIBezierPath()
        bezier126Path.move(to: CGPoint(x: 0, y: 14))
        bezier126Path.addLine(to: CGPoint(x: 41, y: 0))
        UIColor.darkGray.setStroke()
        bezier126Path.lineWidth = 2
        bezier126Path.stroke()

        context.restoreGState()


        //// Bezier 127 Drawing
        context.saveGState()
        context.translateBy(x: 263.12, y: 354.64)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier127Path = UIBezierPath()
        bezier127Path.move(to: CGPoint(x: 0, y: 14))
        bezier127Path.addLine(to: CGPoint(x: 41, y: 0))
        UIColor.darkGray.setStroke()
        bezier127Path.lineWidth = 2
        bezier127Path.stroke()

        context.restoreGState()


        //// Bezier 129 Drawing
        context.saveGState()
        context.translateBy(x: 304.12, y: 368.64)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier129Path = UIBezierPath()
        bezier129Path.move(to: CGPoint(x: 7.97, y: 10.29))
        bezier129Path.addLine(to: CGPoint(x: 32.9, y: 2.07))
        UIColor.darkGray.setStroke()
        bezier129Path.lineWidth = 2
        bezier129Path.stroke()

        context.restoreGState()


        //// Bezier 119 Drawing
        context.saveGState()
        context.translateBy(x: 830.17, y: 351.91)
        context.rotate(by: 1.1 * CGFloat.pi/180)
        context.scaleBy(x: 1.08, y: 1.08)

        let bezier119Path = UIBezierPath()
        bezier119Path.move(to: CGPoint(x: 0, y: 8))
        bezier119Path.addLine(to: CGPoint(x: 22, y: 0))
        UIColor.darkGray.setStroke()
        bezier119Path.lineWidth = 2
        bezier119Path.lineCapStyle = .round
        bezier119Path.lineJoinStyle = .round
        bezier119Path.stroke()

        context.restoreGState()


        //// Bezier 130 Drawing
        context.saveGState()
        context.translateBy(x: 853.17, y: 418.91)
        context.rotate(by: 1.1 * CGFloat.pi/180)
        context.scaleBy(x: 1.08, y: 1.08)

        let bezier130Path = UIBezierPath()
        bezier130Path.move(to: CGPoint(x: 33.35, y: 105.02))
        bezier130Path.addLine(to: CGPoint(x: -1.84, y: 8.46))
        bezier130Path.addLine(to: CGPoint(x: 22, y: 0))
        UIColor.darkGray.setStroke()
        bezier130Path.lineWidth = 2
        bezier130Path.lineCapStyle = .round
        bezier130Path.lineJoinStyle = .round
        bezier130Path.stroke()

        context.restoreGState()


        //// Bezier 108 Drawing
        context.saveGState()
        context.translateBy(x: 860.17, y: 444.91)
        context.rotate(by: 1.1 * CGFloat.pi/180)
        context.scaleBy(x: 1.08, y: 1.08)

        let bezier108Path = UIBezierPath()
        bezier108Path.move(to: CGPoint(x: 0, y: 8))
        bezier108Path.addLine(to: CGPoint(x: 22.99, y: -0.35))
        UIColor.darkGray.setStroke()
        bezier108Path.lineWidth = 2
        bezier108Path.lineCapStyle = .round
        bezier108Path.lineJoinStyle = .round
        bezier108Path.stroke()

        context.restoreGState()


        //// Bezier 110 Drawing
        context.saveGState()
        context.translateBy(x: 870.17, y: 471.91)
        context.rotate(by: 1.1 * CGFloat.pi/180)
        context.scaleBy(x: 1.08, y: 1.08)

        let bezier110Path = UIBezierPath()
        bezier110Path.move(to: CGPoint(x: 0, y: 8))
        bezier110Path.addLine(to: CGPoint(x: 22.99, y: -0.35))
        UIColor.darkGray.setStroke()
        bezier110Path.lineWidth = 2
        bezier110Path.lineCapStyle = .round
        bezier110Path.lineJoinStyle = .round
        bezier110Path.stroke()

        context.restoreGState()


        //// Bezier 133 Drawing
        context.saveGState()
        context.translateBy(x: 879.17, y: 498.91)
        context.rotate(by: 1.1 * CGFloat.pi/180)
        context.scaleBy(x: 1.08, y: 1.08)

        let bezier133Path = UIBezierPath()
        bezier133Path.move(to: CGPoint(x: 0, y: 8))
        bezier133Path.addLine(to: CGPoint(x: 22.99, y: -0.35))
        UIColor.darkGray.setStroke()
        bezier133Path.lineWidth = 2
        bezier133Path.lineCapStyle = .round
        bezier133Path.lineJoinStyle = .round
        bezier133Path.stroke()

        context.restoreGState()


        //// Bezier 109 Drawing
        context.saveGState()
        context.translateBy(x: 833.17, y: 491.91)
        context.rotate(by: 1.1 * CGFloat.pi/180)
        context.scaleBy(x: 1.08, y: 1.08)

        let bezier109Path = UIBezierPath()
        bezier109Path.move(to: CGPoint(x: 0, y: 8))
        bezier109Path.addLine(to: CGPoint(x: 25.75, y: -1.33))
        UIColor.darkGray.setStroke()
        bezier109Path.lineWidth = 2
        bezier109Path.lineCapStyle = .round
        bezier109Path.lineJoinStyle = .round
        bezier109Path.stroke()

        context.restoreGState()


        //// Bezier 111 Drawing
        context.saveGState()
        context.translateBy(x: 804.17, y: 515.91)
        context.rotate(by: 1.1 * CGFloat.pi/180)
        context.scaleBy(x: 1.08, y: 1.08)

        let bezier111Path = UIBezierPath()
        bezier111Path.move(to: CGPoint(x: 0, y: 8))
        bezier111Path.addLine(to: CGPoint(x: 28.51, y: -2.31))
        UIColor.darkGray.setStroke()
        bezier111Path.lineWidth = 2
        bezier111Path.lineCapStyle = .round
        bezier111Path.lineJoinStyle = .round
        bezier111Path.stroke()

        context.restoreGState()


        //// Bezier 123 Drawing
        context.saveGState()
        context.translateBy(x: 786.17, y: 461.91)
        context.rotate(by: 1.1 * CGFloat.pi/180)
        context.scaleBy(x: 1.08, y: 1.08)

        let bezier123Path = UIBezierPath()
        bezier123Path.move(to: CGPoint(x: 0, y: 8))
        bezier123Path.addLine(to: CGPoint(x: 28.51, y: -2.31))
        UIColor.darkGray.setStroke()
        bezier123Path.lineWidth = 2
        bezier123Path.lineCapStyle = .round
        bezier123Path.lineJoinStyle = .round
        bezier123Path.stroke()

        context.restoreGState()


        //// Bezier 124 Drawing
        let bezier124Path = UIBezierPath()
        bezier124Path.move(to: CGPoint(x: 809, y: 462))
        bezier124Path.addLine(to: CGPoint(x: 801, y: 439))
        bezier124Path.addLine(to: CGPoint(x: 777, y: 447))
        UIColor.darkGray.setStroke()
        bezier124Path.lineWidth = 2
        bezier124Path.lineCapStyle = .round
        bezier124Path.lineJoinStyle = .round
        bezier124Path.stroke()


        //// Bezier 125 Drawing
        let bezier125Path = UIBezierPath()
        bezier125Path.move(to: CGPoint(x: 774, y: 438))
        bezier125Path.addLine(to: CGPoint(x: 798, y: 430))
        bezier125Path.addLine(to: CGPoint(x: 771, y: 351))
        bezier125Path.addLine(to: CGPoint(x: 747, y: 359))
        UIColor.darkGray.setStroke()
        bezier125Path.lineWidth = 2
        bezier125Path.lineCapStyle = .round
        bezier125Path.lineJoinStyle = .round
        bezier125Path.stroke()


        //// Bezier 143 Drawing
        context.saveGState()
        context.translateBy(x: 756.17, y: 377.91)
        context.rotate(by: 1.1 * CGFloat.pi/180)
        context.scaleBy(x: 1.08, y: 1.08)

        let bezier143Path = UIBezierPath()
        bezier143Path.move(to: CGPoint(x: 0, y: 8))
        bezier143Path.addLine(to: CGPoint(x: 22, y: 0))
        UIColor.darkGray.setStroke()
        bezier143Path.lineWidth = 2
        bezier143Path.lineCapStyle = .round
        bezier143Path.lineJoinStyle = .round
        bezier143Path.stroke()

        context.restoreGState()


        //// Bezier 144 Drawing
        context.saveGState()
        context.translateBy(x: 765.17, y: 403.91)
        context.rotate(by: 1.1 * CGFloat.pi/180)
        context.scaleBy(x: 1.08, y: 1.08)

        let bezier144Path = UIBezierPath()
        bezier144Path.move(to: CGPoint(x: 0, y: 8))
        bezier144Path.addLine(to: CGPoint(x: 22, y: 0))
        UIColor.darkGray.setStroke()
        bezier144Path.lineWidth = 2
        bezier144Path.lineCapStyle = .round
        bezier144Path.lineJoinStyle = .round
        bezier144Path.stroke()

        context.restoreGState()


        //// Bezier 145 Drawing
        let bezier145Path = UIBezierPath()
        bezier145Path.move(to: CGPoint(x: 768, y: 352))
        bezier145Path.addLine(to: CGPoint(x: 753, y: 308))
        UIColor.darkGray.setStroke()
        bezier145Path.lineWidth = 2
        bezier145Path.lineCapStyle = .round
        bezier145Path.lineJoinStyle = .round
        bezier145Path.stroke()


        //// Bezier 112 Drawing
        context.saveGState()
        context.translateBy(x: 804.17, y: 402.91)
        context.rotate(by: 1.1 * CGFloat.pi/180)
        context.scaleBy(x: 1.08, y: 1.08)

        let bezier112Path = UIBezierPath()
        bezier112Path.move(to: CGPoint(x: 0, y: 8))
        bezier112Path.addLine(to: CGPoint(x: 11.95, y: 3.56))
        UIColor.darkGray.setStroke()
        bezier112Path.lineWidth = 2
        bezier112Path.lineCapStyle = .round
        bezier112Path.lineJoinStyle = .round
        bezier112Path.stroke()

        context.restoreGState()


        //// Bezier 146 Drawing
        context.saveGState()
        context.translateBy(x: 846.08, y: 512.75)
        context.rotate(by: 1.1 * CGFloat.pi/180)
        context.scaleBy(x: 1.08, y: 1.08)

        let bezier146Path = UIBezierPath()
        bezier146Path.move(to: CGPoint(x: 9.72, y: 27.83))
        bezier146Path.addLine(to: CGPoint(x: 1.88, y: 5.75))
        UIColor.darkGray.setStroke()
        bezier146Path.lineWidth = 2
        bezier146Path.lineCapStyle = .round
        bezier146Path.stroke()

        context.restoreGState()


        //// Bezier 45 Drawing
        context.saveGState()
        context.translateBy(x: 760.91, y: 1172.54)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier45Path = UIBezierPath()
        bezier45Path.move(to: CGPoint(x: 0, y: 21))
        bezier45Path.addLine(to: CGPoint(x: 60, y: 0))
        UIColor.darkGray.setStroke()
        bezier45Path.lineWidth = 2
        bezier45Path.stroke()

        context.restoreGState()


        //// Bezier 44 Drawing
        context.saveGState()
        context.translateBy(x: 745.81, y: 1127.41)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier44Path = UIBezierPath()
        bezier44Path.move(to: CGPoint(x: 0, y: 21))
        bezier44Path.addLine(to: CGPoint(x: 60, y: 0))
        UIColor.darkGray.setStroke()
        bezier44Path.lineWidth = 2
        bezier44Path.stroke()

        context.restoreGState()


        //// Bezier 53 Drawing
        context.saveGState()
        context.translateBy(x: 1002.3, y: 1014.64)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier53Path = UIBezierPath()
        bezier53Path.move(to: CGPoint(x: 0, y: 24))
        bezier53Path.addLine(to: CGPoint(x: 14, y: 66))
        bezier53Path.addLine(to: CGPoint(x: 79, y: 43))
        bezier53Path.addLine(to: CGPoint(x: 64, y: 0))
        UIColor.darkGray.setStroke()
        bezier53Path.lineWidth = 2
        bezier53Path.lineCapStyle = .round
        bezier53Path.lineJoinStyle = .round
        bezier53Path.stroke()

        context.restoreGState()


        //// Bezier 60 Drawing
        context.saveGState()
        context.translateBy(x: 1045.11, y: 938.68)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier60Path = UIBezierPath()
        bezier60Path.move(to: CGPoint(x: 38, y: -0.01))
        bezier60Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier60Path.lineWidth = 2
        bezier60Path.stroke()

        context.restoreGState()


        //// Bezier 80 Drawing
        context.saveGState()
        context.translateBy(x: 1069.11, y: 1007.68)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier80Path = UIBezierPath()
        bezier80Path.move(to: CGPoint(x: 37, y: 0))
        bezier80Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier80Path.lineWidth = 2
        bezier80Path.stroke()

        context.restoreGState()


        //// Bezier 54 Drawing
        context.saveGState()
        context.translateBy(x: 1083.22, y: 1050.76)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier54Path = UIBezierPath()
        bezier54Path.move(to: CGPoint(x: 38, y: 0))
        bezier54Path.addLine(to: CGPoint(x: 0, y: 13.5))
        UIColor.darkGray.setStroke()
        bezier54Path.lineWidth = 2
        bezier54Path.stroke()

        context.restoreGState()


        //// Bezier 81 Drawing
        context.saveGState()
        context.translateBy(x: 1091.22, y: 1071.76)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier81Path = UIBezierPath()
        bezier81Path.move(to: CGPoint(x: 38, y: 0))
        bezier81Path.addLine(to: CGPoint(x: 0, y: 13.5))
        UIColor.darkGray.setStroke()
        bezier81Path.lineWidth = 2
        bezier81Path.stroke()

        context.restoreGState()


        //// Bezier 134 Drawing
        context.saveGState()
        context.translateBy(x: 1098.22, y: 1092.76)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier134Path = UIBezierPath()
        bezier134Path.move(to: CGPoint(x: 38, y: 0))
        bezier134Path.addLine(to: CGPoint(x: 0, y: 13.5))
        UIColor.darkGray.setStroke()
        bezier134Path.lineWidth = 2
        bezier134Path.stroke()

        context.restoreGState()


        //// Bezier 79 Drawing
        context.saveGState()
        context.translateBy(x: 1159.11, y: 1117.69)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier79Path = UIBezierPath()
        bezier79Path.move(to: CGPoint(x: 36, y: 0))
        bezier79Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier79Path.lineWidth = 2
        bezier79Path.stroke()

        context.restoreGState()


        //// Bezier 82 Drawing
        context.saveGState()
        context.translateBy(x: 1186.94, y: 1037.81)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier82Path = UIBezierPath()
        bezier82Path.move(to: CGPoint(x: 35, y: 0))
        bezier82Path.addLine(to: CGPoint(x: 0, y: 12.5))
        UIColor.darkGray.setStroke()
        bezier82Path.lineWidth = 2
        bezier82Path.stroke()

        context.restoreGState()


        //// Bezier 135 Drawing
        let bezier135Path = UIBezierPath()
        bezier135Path.move(to: CGPoint(x: 1153, y: 1110))
        bezier135Path.addLine(to: CGPoint(x: 1146, y: 1089))
        UIColor.darkGray.setStroke()
        bezier135Path.lineWidth = 2
        bezier135Path.lineCapStyle = .round
        bezier135Path.lineJoinStyle = .round
        bezier135Path.stroke()


        //// Bezier 136 Drawing
        let bezier136Path = UIBezierPath()
        bezier136Path.move(to: CGPoint(x: 1132.2, y: 1047))
        bezier136Path.addLine(to: CGPoint(x: 1139.4, y: 1068))
        bezier136Path.addLine(to: CGPoint(x: 1175.2, y: 1056))
        bezier136Path.addLine(to: CGPoint(x: 1168.1, y: 1035))
        UIColor.darkGray.setStroke()
        bezier136Path.lineWidth = 2
        bezier136Path.lineCapStyle = .round
        bezier136Path.lineJoinStyle = .round
        bezier136Path.stroke()


        //// Bezier 137 Drawing
        context.saveGState()
        context.translateBy(x: 729.12, y: 702.67)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier137Path = UIBezierPath()
        bezier137Path.move(to: CGPoint(x: 38, y: 0))
        bezier137Path.addLine(to: CGPoint(x: 0, y: 14))
        UIColor.darkGray.setStroke()
        bezier137Path.lineWidth = 2
        bezier137Path.stroke()

        context.restoreGState()


        //// Bezier 139 Drawing
        context.saveGState()
        context.translateBy(x: 756.61, y: 782.38)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier139Path = UIBezierPath()
        bezier139Path.move(to: CGPoint(x: 37.4, y: 0.29))
        bezier139Path.addLine(to: CGPoint(x: 0, y: 14))
        UIColor.darkGray.setStroke()
        bezier139Path.lineWidth = 2
        bezier139Path.stroke()

        context.restoreGState()


        //// Bezier 141 Drawing
        context.saveGState()
        context.translateBy(x: 763.12, y: 803.67)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier141Path = UIBezierPath()
        bezier141Path.move(to: CGPoint(x: 38, y: 0))
        bezier141Path.addLine(to: CGPoint(x: 0, y: 14))
        UIColor.darkGray.setStroke()
        bezier141Path.lineWidth = 2
        bezier141Path.stroke()

        context.restoreGState()


        //// Bezier 142 Drawing
        context.saveGState()
        context.translateBy(x: 780.11, y: 849.69)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier142Path = UIBezierPath()
        bezier142Path.move(to: CGPoint(x: 36, y: 0))
        bezier142Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier142Path.lineWidth = 2
        bezier142Path.lineCapStyle = .round
        bezier142Path.stroke()

        context.restoreGState()


        //// Bezier 148 Drawing
        context.saveGState()
        context.translateBy(x: 776.11, y: 993.69)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier148Path = UIBezierPath()
        bezier148Path.move(to: CGPoint(x: 36, y: 0))
        bezier148Path.addLine(to: CGPoint(x: -0.99, y: 13.5))
        UIColor.darkGray.setStroke()
        bezier148Path.lineWidth = 2
        bezier148Path.lineCapStyle = .round
        bezier148Path.stroke()

        context.restoreGState()


        //// Bezier 149 Drawing
        context.saveGState()
        context.translateBy(x: 696.11, y: 927.69)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier149Path = UIBezierPath()
        bezier149Path.move(to: CGPoint(x: 36, y: 0))
        bezier149Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier149Path.lineWidth = 2
        bezier149Path.lineCapStyle = .round
        bezier149Path.stroke()

        context.restoreGState()


        //// Bezier 150 Drawing
        context.saveGState()
        context.translateBy(x: 703.11, y: 948.69)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier150Path = UIBezierPath()
        bezier150Path.move(to: CGPoint(x: 36, y: 0))
        bezier150Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier150Path.lineWidth = 2
        bezier150Path.lineCapStyle = .round
        bezier150Path.stroke()

        context.restoreGState()


        //// Bezier 152 Drawing
        context.saveGState()
        context.translateBy(x: 718.11, y: 990.69)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier152Path = UIBezierPath()
        bezier152Path.move(to: CGPoint(x: 36, y: 0))
        bezier152Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier152Path.lineWidth = 2
        bezier152Path.lineCapStyle = .round
        bezier152Path.stroke()

        context.restoreGState()


        //// Bezier 153 Drawing
        context.saveGState()
        context.translateBy(x: 726.11, y: 1011.69)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier153Path = UIBezierPath()
        bezier153Path.move(to: CGPoint(x: 36, y: 0))
        bezier153Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier153Path.lineWidth = 2
        bezier153Path.lineCapStyle = .round
        bezier153Path.stroke()

        context.restoreGState()


        //// Bezier 154 Drawing
        context.saveGState()
        context.translateBy(x: 734.11, y: 1033.69)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier154Path = UIBezierPath()
        bezier154Path.move(to: CGPoint(x: 36, y: 0))
        bezier154Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier154Path.lineWidth = 2
        bezier154Path.lineCapStyle = .round
        bezier154Path.stroke()

        context.restoreGState()


        //// Bezier 155 Drawing
        context.saveGState()
        context.translateBy(x: 672.11, y: 860.69)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier155Path = UIBezierPath()
        bezier155Path.move(to: CGPoint(x: 36, y: 0))
        bezier155Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier155Path.lineWidth = 2
        bezier155Path.stroke()

        context.restoreGState()


        //// Bezier 156 Drawing
        context.saveGState()
        context.translateBy(x: 680.11, y: 883.69)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier156Path = UIBezierPath()
        bezier156Path.move(to: CGPoint(x: 36, y: 0))
        bezier156Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier156Path.lineWidth = 2
        bezier156Path.lineCapStyle = .round
        bezier156Path.stroke()

        context.restoreGState()


        //// Bezier 157 Drawing
        context.saveGState()
        context.translateBy(x: 688.11, y: 905.69)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier157Path = UIBezierPath()
        bezier157Path.move(to: CGPoint(x: 36, y: 0))
        bezier157Path.addLine(to: CGPoint(x: 0, y: 13))
        UIColor.darkGray.setStroke()
        bezier157Path.lineWidth = 2
        bezier157Path.lineCapStyle = .round
        bezier157Path.stroke()

        context.restoreGState()


        //// Bezier 147 Drawing
        context.saveGState()
        context.translateBy(x: 768.11, y: 972.69)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier147Path = UIBezierPath()
        bezier147Path.move(to: CGPoint(x: 36, y: 0))
        bezier147Path.addLine(to: CGPoint(x: -0.99, y: 13.5))
        UIColor.darkGray.setStroke()
        bezier147Path.lineWidth = 2
        bezier147Path.lineCapStyle = .round
        bezier147Path.stroke()

        context.restoreGState()


        //// Bezier 151 Drawing
        context.saveGState()
        context.translateBy(x: 711.11, y: 968.69)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier151Path = UIBezierPath()
        bezier151Path.move(to: CGPoint(x: 36, y: 0))
        bezier151Path.addLine(to: CGPoint(x: -0.99, y: 13.5))
        UIColor.darkGray.setStroke()
        bezier151Path.lineWidth = 2
        bezier151Path.stroke()

        context.restoreGState()


        //// Bezier 84 Drawing
        context.saveGState()
        context.translateBy(x: 760.11, y: 950.69)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier84Path = UIBezierPath()
        bezier84Path.move(to: CGPoint(x: 36, y: 0))
        bezier84Path.addLine(to: CGPoint(x: -0.99, y: 13.5))
        UIColor.darkGray.setStroke()
        bezier84Path.lineWidth = 2
        bezier84Path.lineCapStyle = .round
        bezier84Path.stroke()

        context.restoreGState()


        //// Bezier 88 Drawing
        context.saveGState()
        context.translateBy(x: 753.11, y: 930.69)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier88Path = UIBezierPath()
        bezier88Path.move(to: CGPoint(x: 36, y: 0))
        bezier88Path.addLine(to: CGPoint(x: -0.99, y: 13.5))
        UIColor.darkGray.setStroke()
        bezier88Path.lineWidth = 2
        bezier88Path.lineCapStyle = .round
        bezier88Path.stroke()

        context.restoreGState()


        //// Bezier 89 Drawing
        context.saveGState()
        context.translateBy(x: 746.11, y: 909.69)
        context.rotate(by: 0.5 * CGFloat.pi/180)

        let bezier89Path = UIBezierPath()
        bezier89Path.move(to: CGPoint(x: 36, y: 0))
        bezier89Path.addLine(to: CGPoint(x: -0.99, y: 13.5))
        UIColor.darkGray.setStroke()
        bezier89Path.lineWidth = 2
        bezier89Path.lineCapStyle = .round
        bezier89Path.stroke()

        context.restoreGState()
        
        context.restoreGState()

    }

    //// Generated Images

    @objc dynamic public class var imageOfCanvas1: UIImage {
        if Cache.imageOfCanvas1 != nil {
            return Cache.imageOfCanvas1!
        }

        UIGraphicsBeginImageContextWithOptions(CGSize(width: 1343, height: 1308), false, 0)
            IZFirstFloor.drawCanvas1()

        Cache.imageOfCanvas1 = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return Cache.imageOfCanvas1!
    }

    //// Customization Infrastructure

    @objc @IBOutlet dynamic var canvas1Targets: [AnyObject]! {
        get { return Cache.canvas1Targets }
        set {
            Cache.canvas1Targets = newValue
            for target: AnyObject in newValue {
                let _ = target.perform(NSSelectorFromString("setImage:"), with: IZFirstFloor.imageOfCanvas1)
            }
        }
    }




    @objc(IZFirstFloorResizingBehavior)
    public enum ResizingBehavior: Int {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.

        public func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }

            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)

            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }

            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
}
