//
//  IZGroundfloor.swift
//  InfozentrumGuide
//
//  Created by RWTH on 18.01.18.
//  Copyright © 2018 RWTH. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//
//  This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
//



import UIKit

public class IZGroundfloor : NSObject {

    //// Cache

    private struct Cache {
        static var imageOfCanvas1: UIImage?
        static var canvas1Targets: [AnyObject]?
    }

    //// Drawing Methods

    @objc dynamic public class func drawCanvas1(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 1343, height: 1308), resizing: ResizingBehavior = .aspectFit) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        //// Resize to Target Frame
        context.saveGState()
        let resizedFrame: CGRect = resizing.apply(rect: CGRect(x: 0, y: 0, width: 1343, height: 1308), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 1343, y: resizedFrame.height / 1308)


        //// Color Declarations
        let color = UIColor(red: 0.706, green: 0.876, blue: 0.613, alpha: 1.000)
        let color3 = UIColor(red: 0.945, green: 0.945, blue: 0.945, alpha: 1.000)

        //// IZ
        context.saveGState()
        context.translateBy(x: 16.5, y: 13.5)
        context.rotate(by: 0.5 * CGFloat.pi/180)



        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: 0, y: 229))
        bezierPath.addCurve(to: CGPoint(x: 120, y: 188), controlPoint1: CGPoint(x: 103, y: 194), controlPoint2: CGPoint(x: 120, y: 188))
        bezierPath.addLine(to: CGPoint(x: 136, y: 236))
        bezierPath.addLine(to: CGPoint(x: 313.5, y: 175.5))
        bezierPath.addLine(to: CGPoint(x: 277, y: 127))
        bezierPath.addLine(to: CGPoint(x: 301, y: 110))
        bezierPath.addLine(to: CGPoint(x: 333, y: 95))
        bezierPath.addLine(to: CGPoint(x: 366, y: 87))
        bezierPath.addLine(to: CGPoint(x: 400, y: 84))
        bezierPath.addLine(to: CGPoint(x: 400.5, y: 146.5))
        bezierPath.addLine(to: CGPoint(x: 491.5, y: 114.5))
        bezierPath.addLine(to: CGPoint(x: 463, y: 34))
        bezierPath.addLine(to: CGPoint(x: 562, y: 0))
        bezierPath.addLine(to: CGPoint(x: 611, y: 136))
        bezierPath.addLine(to: CGPoint(x: 590, y: 144))
        bezierPath.addLine(to: CGPoint(x: 630, y: 259))
        bezierPath.addLine(to: CGPoint(x: 368, y: 352))
        bezierPath.addLine(to: CGPoint(x: 505, y: 751))
        bezierPath.addLine(to: CGPoint(x: 521, y: 745))
        bezierPath.addLine(to: CGPoint(x: 544.5, y: 812.5))
        bezierPath.addLine(to: CGPoint(x: 520.5, y: 821.5))
        bezierPath.addLine(to: CGPoint(x: 534, y: 859))
        bezierPath.addLine(to: CGPoint(x: 663, y: 856))
        bezierPath.addLine(to: CGPoint(x: 649, y: 819))
        bezierPath.addLine(to: CGPoint(x: 697, y: 801))
        bezierPath.addLine(to: CGPoint(x: 655.5, y: 688))
        bezierPath.addLine(to: CGPoint(x: 708, y: 669))
        bezierPath.addLine(to: CGPoint(x: 703, y: 655))
        bezierPath.addLine(to: CGPoint(x: 741, y: 641))
        bezierPath.addLine(to: CGPoint(x: 819, y: 863))
        bezierPath.addLine(to: CGPoint(x: 771, y: 880))
        bezierPath.addLine(to: CGPoint(x: 818, y: 1011))
        bezierPath.addLine(to: CGPoint(x: 863.06, y: 995.87))
        bezierPath.addLine(to: CGPoint(x: 955, y: 965))
        bezierPath.addLine(to: CGPoint(x: 974, y: 1023))
        bezierPath.addLine(to: CGPoint(x: 1059, y: 994))
        bezierPath.addLine(to: CGPoint(x: 1035.68, y: 926.94))
        bezierPath.addLine(to: CGPoint(x: 1027, y: 902))
        bezierPath.addLine(to: CGPoint(x: 1112.5, y: 873.5))
        bezierPath.addLine(to: CGPoint(x: 1158.5, y: 1005.5))
        bezierPath.addLine(to: CGPoint(x: 1205, y: 989))
        bezierPath.addLine(to: CGPoint(x: 1283, y: 1211))
        bezierPath.addLine(to: CGPoint(x: 1199, y: 1241))
        bezierPath.addLine(to: CGPoint(x: 1145, y: 1087))
        bezierPath.addLine(to: CGPoint(x: 1017, y: 1131))
        bezierPath.addLine(to: CGPoint(x: 1037, y: 1190))
        bezierPath.addLine(to: CGPoint(x: 1024, y: 1202))
        bezierPath.addLine(to: CGPoint(x: 1009, y: 1210))
        bezierPath.addLine(to: CGPoint(x: 994, y: 1215))
        bezierPath.addLine(to: CGPoint(x: 978, y: 1217))
        bezierPath.addLine(to: CGPoint(x: 963, y: 1217))
        bezierPath.addLine(to: CGPoint(x: 970, y: 1237))
        bezierPath.addLine(to: CGPoint(x: 958, y: 1250))
        bezierPath.addLine(to: CGPoint(x: 941, y: 1262))
        bezierPath.addLine(to: CGPoint(x: 921, y: 1271))
        bezierPath.addLine(to: CGPoint(x: 908.32, y: 1273.99))
        bezierPath.addLine(to: CGPoint(x: 895.51, y: 1275))
        bezierPath.addLine(to: CGPoint(x: 884.87, y: 1274.58))
        bezierPath.addLine(to: CGPoint(x: 873, y: 1272))
        bezierPath.addLine(to: CGPoint(x: 846, y: 1190))
        bezierPath.addLine(to: CGPoint(x: 829, y: 1196))
        bezierPath.addLine(to: CGPoint(x: 838, y: 1222))
        bezierPath.addLine(to: CGPoint(x: 778, y: 1243.5))
        bezierPath.addLine(to: CGPoint(x: 724, y: 1081))
        bezierPath.addLine(to: CGPoint(x: 635, y: 1112))
        bezierPath.addLine(to: CGPoint(x: 613, y: 1047))
        bezierPath.addLine(to: CGPoint(x: 632.5, y: 1040.5))
        bezierPath.addLine(to: CGPoint(x: 578, y: 875))
        bezierPath.addLine(to: CGPoint(x: 466.5, y: 875.5))
        bezierPath.addLine(to: CGPoint(x: 467, y: 1016))
        bezierPath.addLine(to: CGPoint(x: 495.5, y: 1016.5))
        bezierPath.addLine(to: CGPoint(x: 496, y: 1099))
        bezierPath.addLine(to: CGPoint(x: 339, y: 1096))
        bezierPath.addLine(to: CGPoint(x: 338, y: 978))
        bezierPath.addLine(to: CGPoint(x: 387, y: 978))
        bezierPath.addLine(to: CGPoint(x: 388, y: 793))
        bezierPath.addLine(to: CGPoint(x: 382.5, y: 777.5))
        bezierPath.addLine(to: CGPoint(x: 395, y: 773))
        bezierPath.addLine(to: CGPoint(x: 362.47, y: 678.27))
        bezierPath.addLine(to: CGPoint(x: 271, y: 415))
        bezierPath.addLine(to: CGPoint(x: 101, y: 459))
        bezierPath.addLine(to: CGPoint(x: 87, y: 419))
        bezierPath.addLine(to: CGPoint(x: 65, y: 427))
        bezierPath.addLine(to: CGPoint(x: 0, y: 229))
        color3.setFill()
        bezierPath.fill()
        UIColor.darkGray.setStroke()
        bezierPath.lineWidth = 2
        bezierPath.lineCapStyle = .round
        bezierPath.lineJoinStyle = .round
        bezierPath.stroke()


        //// Bezier 94 Drawing
        let bezier94Path = UIBezierPath()
        bezier94Path.move(to: CGPoint(x: 669.5, y: 1077.5))
        bezier94Path.addLine(to: CGPoint(x: 601, y: 873))
        bezier94Path.addLine(to: CGPoint(x: 668, y: 873))
        bezier94Path.addLine(to: CGPoint(x: 735.5, y: 1054))
        bezier94Path.addLine(to: CGPoint(x: 669.5, y: 1077.5))
        bezier94Path.close()
        color.setFill()
        bezier94Path.fill()


        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.move(to: CGPoint(x: 380.5, y: 347.5))
        bezier3Path.addLine(to: CGPoint(x: 360.5, y: 291.5))
        bezier3Path.addLine(to: CGPoint(x: 544.5, y: 226.5))
        bezier3Path.addLine(to: CGPoint(x: 503.5, y: 110.5))
        bezier3Path.addLine(to: CGPoint(x: 491.5, y: 114.5))
        UIColor.darkGray.setStroke()
        bezier3Path.lineWidth = 2
        bezier3Path.lineCapStyle = .round
        bezier3Path.lineJoinStyle = .round
        bezier3Path.stroke()


        //// Bezier 4 Drawing
        let bezier4Path = UIBezierPath()
        bezier4Path.move(to: CGPoint(x: 261, y: 215.5))
        bezier4Path.addLine(to: CGPoint(x: 327.5, y: 192.5))
        bezier4Path.addLine(to: CGPoint(x: 337.5, y: 221.5))
        bezier4Path.addLine(to: CGPoint(x: 413.5, y: 195.5))
        bezier4Path.addLine(to: CGPoint(x: 403.5, y: 166.5))
        bezier4Path.addLine(to: CGPoint(x: 470.5, y: 142.5))
        bezier4Path.addLine(to: CGPoint(x: 498.5, y: 221.5))
        bezier4Path.addLine(to: CGPoint(x: 303.5, y: 290.5))
        bezier4Path.addLine(to: CGPoint(x: 261, y: 215.5))
        bezier4Path.close()
        color.setFill()
        bezier4Path.fill()
        UIColor.darkGray.setStroke()
        bezier4Path.lineWidth = 2
        bezier4Path.lineCapStyle = .round
        bezier4Path.lineJoinStyle = .round
        bezier4Path.stroke()


        //// Bezier 5 Drawing
        let bezier5Path = UIBezierPath()
        bezier5Path.move(to: CGPoint(x: 85.5, y: 419.5))
        bezier5Path.addLine(to: CGPoint(x: 186.5, y: 383.5))
        bezier5Path.addLine(to: CGPoint(x: 203.5, y: 432.5))
        UIColor.darkGray.setStroke()
        bezier5Path.lineWidth = 2
        bezier5Path.lineCapStyle = .round
        bezier5Path.lineJoinStyle = .round
        bezier5Path.stroke()


        //// Bezier 6 Drawing
        let bezier6Path = UIBezierPath()
        bezier6Path.move(to: CGPoint(x: 186.5, y: 383.5))
        bezier6Path.addLine(to: CGPoint(x: 135.5, y: 234.5))
        UIColor.darkGray.setStroke()
        bezier6Path.lineWidth = 2
        bezier6Path.lineCapStyle = .round
        bezier6Path.lineJoinStyle = .round
        bezier6Path.stroke()


        //// Bezier 7 Drawing
        let bezier7Path = UIBezierPath()
        bezier7Path.move(to: CGPoint(x: 327.5, y: 192.5))
        bezier7Path.addLine(to: CGPoint(x: 313.5, y: 175.5))
        UIColor.darkGray.setStroke()
        bezier7Path.lineWidth = 2
        bezier7Path.lineCapStyle = .round
        bezier7Path.lineJoinStyle = .round
        bezier7Path.stroke()


        //// Bezier 8 Drawing
        let bezier8Path = UIBezierPath()
        bezier8Path.move(to: CGPoint(x: 403.5, y: 166.5))
        bezier8Path.addLine(to: CGPoint(x: 400.5, y: 146.5))
        UIColor.red.setFill()
        bezier8Path.fill()
        UIColor.darkGray.setStroke()
        bezier8Path.lineWidth = 2
        bezier8Path.lineCapStyle = .round
        bezier8Path.lineJoinStyle = .round
        bezier8Path.stroke()


        //// Bezier 9 Drawing
        let bezier9Path = UIBezierPath()
        bezier9Path.move(to: CGPoint(x: 368.5, y: 353.5))
        bezier9Path.addLine(to: CGPoint(x: 341.5, y: 277.5))
        UIColor.darkGray.setStroke()
        bezier9Path.lineWidth = 2
        bezier9Path.lineCapStyle = .round
        bezier9Path.lineJoinStyle = .round
        bezier9Path.stroke()


        //// Bezier 10 Drawing
        let bezier10Path = UIBezierPath()
        bezier10Path.move(to: CGPoint(x: 195.5, y: 407.5))
        bezier10Path.addLine(to: CGPoint(x: 248.01, y: 393.92))
        bezier10Path.addLine(to: CGPoint(x: 265.1, y: 389.5))
        bezier10Path.addLine(to: CGPoint(x: 367.5, y: 353.5))
        UIColor.darkGray.setStroke()
        bezier10Path.lineWidth = 2
        bezier10Path.lineCapStyle = .round
        bezier10Path.lineJoinStyle = .round
        bezier10Path.stroke()


        //// Bezier 11 Drawing
        let bezier11Path = UIBezierPath()
        bezier11Path.move(to: CGPoint(x: 247.5, y: 394.5))
        bezier11Path.addLine(to: CGPoint(x: 253.5, y: 418.5))
        UIColor.darkGray.setStroke()
        bezier11Path.lineWidth = 2
        bezier11Path.lineCapStyle = .round
        bezier11Path.lineJoinStyle = .round
        bezier11Path.stroke()


        //// Bezier 12 Drawing
        let bezier12Path = UIBezierPath()
        bezier12Path.move(to: CGPoint(x: 261.5, y: 216.5))
        bezier12Path.addLine(to: CGPoint(x: 250.5, y: 197.5))
        UIColor.red.setFill()
        bezier12Path.fill()
        UIColor.darkGray.setStroke()
        bezier12Path.lineWidth = 2
        bezier12Path.lineCapStyle = .round
        bezier12Path.lineJoinStyle = .round
        bezier12Path.stroke()


        //// Bezier 13 Drawing
        let bezier13Path = UIBezierPath()
        bezier13Path.move(to: CGPoint(x: 509.5, y: 128.5))
        bezier13Path.addLine(to: CGPoint(x: 470.5, y: 142.5))
        bezier13Path.addLine(to: CGPoint(x: 464.5, y: 124.5))
        UIColor.darkGray.setStroke()
        bezier13Path.lineWidth = 2
        bezier13Path.lineCapStyle = .round
        bezier13Path.lineJoinStyle = .round
        bezier13Path.stroke()


        //// Bezier 14 Drawing
        let bezier14Path = UIBezierPath()
        bezier14Path.move(to: CGPoint(x: 516.5, y: 143.5))
        bezier14Path.addLine(to: CGPoint(x: 581.5, y: 120.5))
        bezier14Path.addLine(to: CGPoint(x: 590.5, y: 145.5))
        UIColor.darkGray.setStroke()
        bezier14Path.lineWidth = 2
        bezier14Path.lineCapStyle = .round
        bezier14Path.lineJoinStyle = .round
        bezier14Path.stroke()


        //// Bezier 15 Drawing
        let bezier15Path = UIBezierPath()
        bezier15Path.move(to: CGPoint(x: 153.5, y: 444.5))
        bezier15Path.addLine(to: CGPoint(x: 138.5, y: 400.5))
        UIColor.darkGray.setStroke()
        bezier15Path.lineWidth = 2
        bezier15Path.lineCapStyle = .round
        bezier15Path.lineJoinStyle = .round
        bezier15Path.stroke()


        //// Bezier 16 Drawing
        let bezier16Path = UIBezierPath()
        bezier16Path.move(to: CGPoint(x: 302.5, y: 376.5))
        bezier16Path.addLine(to: CGPoint(x: 385.5, y: 616.5))
        bezier16Path.addLine(to: CGPoint(x: 346.5, y: 630.5))
        UIColor.darkGray.setStroke()
        bezier16Path.lineWidth = 2
        bezier16Path.lineCapStyle = .round
        bezier16Path.lineJoinStyle = .round
        bezier16Path.stroke()


        //// Bezier 17 Drawing
        let bezier17Path = UIBezierPath()
        bezier17Path.move(to: CGPoint(x: 326.5, y: 367.5))
        bezier17Path.addLine(to: CGPoint(x: 402.82, y: 585.72))
        bezier17Path.addLine(to: CGPoint(x: 414.01, y: 582.2))
        bezier17Path.addLine(to: CGPoint(x: 438.43, y: 652.09))
        bezier17Path.addLine(to: CGPoint(x: 426.22, y: 656.11))
        bezier17Path.addLine(to: CGPoint(x: 442.5, y: 703.37))
        bezier17Path.addLine(to: CGPoint(x: 379.41, y: 726))
        UIColor.darkGray.setStroke()
        bezier17Path.lineWidth = 2
        bezier17Path.lineCapStyle = .round
        bezier17Path.lineJoinStyle = .round
        bezier17Path.stroke()


        //// Bezier 18 Drawing
        let bezier18Path = UIBezierPath()
        bezier18Path.move(to: CGPoint(x: 362.5, y: 677.5))
        bezier18Path.addLine(to: CGPoint(x: 402.5, y: 663.5))
        bezier18Path.addLine(to: CGPoint(x: 418.5, y: 710.5))
        UIColor.darkGray.setStroke()
        bezier18Path.lineWidth = 2
        bezier18Path.lineCapStyle = .round
        bezier18Path.lineJoinStyle = .round
        bezier18Path.stroke()


        //// Bezier 19 Drawing
        context.saveGState()
        context.translateBy(x: 271.5, y: 415.5)

        let bezier19Path = UIBezierPath()
        bezier19Path.move(to: CGPoint(x: -6.3, y: 1))
        bezier19Path.addLine(to: CGPoint(x: 39, y: -14))
        UIColor.darkGray.setStroke()
        bezier19Path.lineWidth = 2
        bezier19Path.lineCapStyle = .round
        bezier19Path.lineJoinStyle = .round
        bezier19Path.stroke()

        context.restoreGState()


        //// Bezier 20 Drawing
        let bezier20Path = UIBezierPath()
        bezier20Path.move(to: CGPoint(x: 278.5, y: 438.5))
        bezier20Path.addLine(to: CGPoint(x: 319.5, y: 424.5))
        UIColor.darkGray.setStroke()
        bezier20Path.lineWidth = 2
        bezier20Path.stroke()


        //// Bezier 21 Drawing
        let bezier21Path = UIBezierPath()
        bezier21Path.move(to: CGPoint(x: 303.5, y: 510.5))
        bezier21Path.addLine(to: CGPoint(x: 344.5, y: 496.5))
        UIColor.darkGray.setStroke()
        bezier21Path.lineWidth = 2
        bezier21Path.stroke()


        //// Bezier 22 Drawing
        context.saveGState()
        context.translateBy(x: 312.5, y: 520.5)
        context.scaleBy(x: 0.97, y: 0.97)

        let bezier22Path = UIBezierPath()
        bezier22Path.move(to: CGPoint(x: 0, y: 14))
        bezier22Path.addLine(to: CGPoint(x: 41, y: 0))
        UIColor.darkGray.setStroke()
        bezier22Path.lineWidth = 2
        bezier22Path.stroke()

        context.restoreGState()


        //// Bezier 23 Drawing
        let bezier23Path = UIBezierPath()
        bezier23Path.move(to: CGPoint(x: 320.5, y: 558.5))
        bezier23Path.addLine(to: CGPoint(x: 361.5, y: 544.5))
        UIColor.darkGray.setStroke()
        bezier23Path.lineWidth = 2
        bezier23Path.stroke()


        //// Bezier 24 Drawing
        context.saveGState()
        context.translateBy(x: 329.5, y: 568.5)
        context.scaleBy(x: 0.98, y: 0.98)

        let bezier24Path = UIBezierPath()
        bezier24Path.move(to: CGPoint(x: 0, y: 14))
        bezier24Path.addLine(to: CGPoint(x: 40, y: 0))
        UIColor.darkGray.setStroke()
        bezier24Path.lineWidth = 2
        bezier24Path.lineCapStyle = .round
        bezier24Path.stroke()

        context.restoreGState()


        //// Bezier 25 Drawing
        context.saveGState()
        context.translateBy(x: 337.5, y: 592.5)
        context.scaleBy(x: 0.96, y: 0.96)

        let bezier25Path = UIBezierPath()
        bezier25Path.move(to: CGPoint(x: 0, y: 14.6))
        bezier25Path.addLine(to: CGPoint(x: 41, y: 0))
        UIColor.darkGray.setStroke()
        bezier25Path.lineWidth = 2
        bezier25Path.lineCapStyle = .round
        bezier25Path.lineJoinStyle = .round
        bezier25Path.stroke()

        context.restoreGState()


        //// Bezier 26 Drawing
        let bezier26Path = UIBezierPath()
        bezier26Path.move(to: CGPoint(x: 394.5, y: 560.5))
        bezier26Path.addLine(to: CGPoint(x: 435.5, y: 546.5))
        UIColor.darkGray.setStroke()
        bezier26Path.lineWidth = 2
        bezier26Path.stroke()


        //// Bezier 27 Drawing
        let bezier27Path = UIBezierPath()
        bezier27Path.move(to: CGPoint(x: 385.5, y: 536.5))
        bezier27Path.addLine(to: CGPoint(x: 426.5, y: 522.5))
        UIColor.darkGray.setStroke()
        bezier27Path.lineWidth = 2
        bezier27Path.stroke()


        //// Bezier 28 Drawing
        let bezier28Path = UIBezierPath()
        bezier28Path.move(to: CGPoint(x: 377.5, y: 512.5))
        bezier28Path.addLine(to: CGPoint(x: 418.5, y: 498.5))
        UIColor.darkGray.setStroke()
        bezier28Path.lineWidth = 2
        bezier28Path.stroke()


        //// Bezier 29 Drawing
        let bezier29Path = UIBezierPath()
        bezier29Path.move(to: CGPoint(x: 368.5, y: 488.5))
        bezier29Path.addLine(to: CGPoint(x: 409.5, y: 474.5))
        UIColor.darkGray.setStroke()
        bezier29Path.lineWidth = 2
        bezier29Path.stroke()


        //// Bezier 30 Drawing
        let bezier30Path = UIBezierPath()
        bezier30Path.move(to: CGPoint(x: 344.5, y: 415.5))
        bezier30Path.addLine(to: CGPoint(x: 385.5, y: 401.5))
        UIColor.darkGray.setStroke()
        bezier30Path.lineWidth = 2
        bezier30Path.stroke()


        //// Bezier 31 Drawing
        context.saveGState()
        context.translateBy(x: 413.5, y: 572)
        context.scaleBy(x: 1.01, y: 1)

        let bezier31Path = UIBezierPath()
        bezier31Path.move(to: CGPoint(x: -1.98, y: 11))
        bezier31Path.addLine(to: CGPoint(x: 29, y: 0))
        UIColor.darkGray.setStroke()
        bezier31Path.lineWidth = 2
        bezier31Path.lineCapStyle = .round
        bezier31Path.stroke()

        context.restoreGState()


        //// Bezier 32 Drawing
        let bezier32Path = UIBezierPath()
        bezier32Path.move(to: CGPoint(x: 421.5, y: 604.5))
        bezier32Path.addLine(to: CGPoint(x: 450.5, y: 594.5))
        UIColor.darkGray.setStroke()
        bezier32Path.lineWidth = 2
        bezier32Path.stroke()


        //// Bezier 33 Drawing
        let bezier33Path = UIBezierPath()
        bezier33Path.move(to: CGPoint(x: 435.5, y: 653))
        bezier33Path.addLine(to: CGPoint(x: 466.5, y: 642))
        UIColor.darkGray.setStroke()
        bezier33Path.lineWidth = 2
        bezier33Path.lineCapStyle = .round
        bezier33Path.stroke()


        //// Bezier 34 Drawing
        let bezier34Path = UIBezierPath()
        bezier34Path.move(to: CGPoint(x: 506.5, y: 750.5))
        bezier34Path.addLine(to: CGPoint(x: 427.5, y: 778.5))
        bezier34Path.addLine(to: CGPoint(x: 450.5, y: 846.5))
        bezier34Path.addLine(to: CGPoint(x: 520.5, y: 821.5))
        UIColor.darkGray.setStroke()
        bezier34Path.lineWidth = 2
        bezier34Path.lineCapStyle = .round
        bezier34Path.stroke()


        //// Bezier 35 Drawing
        let bezier35Path = UIBezierPath()
        bezier35Path.move(to: CGPoint(x: 388.5, y: 792.5))
        bezier35Path.addLine(to: CGPoint(x: 427.5, y: 778.5))
        UIColor.darkGray.setStroke()
        bezier35Path.lineWidth = 2
        bezier35Path.stroke()


        //// Bezier 36 Drawing
        let bezier36Path = UIBezierPath()
        bezier36Path.move(to: CGPoint(x: 442.5, y: 703.5))
        bezier36Path.addLine(to: CGPoint(x: 463.5, y: 765.5))
        UIColor.darkGray.setStroke()
        bezier36Path.lineWidth = 2
        bezier36Path.stroke()


        //// Bezier 37 Drawing
        context.saveGState()
        context.translateBy(x: 450.5, y: 712.06)
        context.scaleBy(x: 0.96, y: 0.96)

        let bezier37Path = UIBezierPath()
        bezier37Path.move(to: CGPoint(x: 0, y: 15.04))
        bezier37Path.addLine(to: CGPoint(x: 42.71, y: -0.58))
        UIColor.darkGray.setStroke()
        bezier37Path.lineWidth = 2
        bezier37Path.lineCapStyle = .round
        bezier37Path.lineJoinStyle = .round
        bezier37Path.stroke()

        context.restoreGState()


        //// Bezier 38 Drawing
        let bezier38Path = UIBezierPath()
        bezier38Path.move(to: CGPoint(x: 465.5, y: 933.5))
        bezier38Path.addLine(to: CGPoint(x: 411.5, y: 933.5))
        bezier38Path.addLine(to: CGPoint(x: 411.5, y: 860.5))
        bezier38Path.addLine(to: CGPoint(x: 450.5, y: 846.5))
        UIColor.darkGray.setStroke()
        bezier38Path.lineWidth = 2
        bezier38Path.lineCapStyle = .round
        bezier38Path.lineJoinStyle = .round
        bezier38Path.stroke()


        //// Bezier 40 Drawing
        let bezier40Path = UIBezierPath()
        bezier40Path.move(to: CGPoint(x: 466.5, y: 890.5))
        bezier40Path.addLine(to: CGPoint(x: 466.5, y: 875.5))
        bezier40Path.addLine(to: CGPoint(x: 411.5, y: 875.5))
        UIColor.darkGray.setStroke()
        bezier40Path.lineWidth = 2
        bezier40Path.stroke()


        //// Bezier 41 Drawing
        let bezier41Path = UIBezierPath()
        bezier41Path.move(to: CGPoint(x: 410.5, y: 867.5))
        bezier41Path.addLine(to: CGPoint(x: 387.5, y: 867.5))
        UIColor.darkGray.setStroke()
        bezier41Path.lineWidth = 2
        bezier41Path.lineCapStyle = .round
        bezier41Path.lineJoinStyle = .round
        bezier41Path.stroke()


        //// Bezier 42 Drawing
        let bezier42Path = UIBezierPath()
        bezier42Path.move(to: CGPoint(x: 410.5, y: 893.5))
        bezier42Path.addLine(to: CGPoint(x: 387.5, y: 893.5))
        UIColor.darkGray.setStroke()
        bezier42Path.lineWidth = 2
        bezier42Path.lineCapStyle = .round
        bezier42Path.lineJoinStyle = .round
        bezier42Path.stroke()


        //// Bezier 39 Drawing
        let bezier39Path = UIBezierPath()
        bezier39Path.move(to: CGPoint(x: 735.5, y: 1054.5))
        bezier39Path.addLine(to: CGPoint(x: 669.5, y: 1077.5))
        bezier39Path.addLine(to: CGPoint(x: 600.5, y: 873.5))
        bezier39Path.addLine(to: CGPoint(x: 668.5, y: 872.5))
        bezier39Path.addLine(to: CGPoint(x: 735.5, y: 1054.5))
        bezier39Path.addLine(to: CGPoint(x: 798.5, y: 1032.5))
        bezier39Path.addLine(to: CGPoint(x: 829.5, y: 1122.5))
        bezier39Path.addLine(to: CGPoint(x: 988.5, y: 1066.5))
        bezier39Path.addLine(to: CGPoint(x: 973.5, y: 1021.5))
        UIColor.darkGray.setStroke()
        bezier39Path.lineWidth = 2
        bezier39Path.lineCapStyle = .round
        bezier39Path.lineJoinStyle = .round
        bezier39Path.stroke()


        //// Bezier 43 Drawing
        let bezier43Path = UIBezierPath()
        bezier43Path.move(to: CGPoint(x: 719.5, y: 1082.5))
        bezier43Path.addLine(to: CGPoint(x: 783.5, y: 1060.5))
        bezier43Path.addLine(to: CGPoint(x: 830.5, y: 1200.5))
        UIColor.darkGray.setStroke()
        bezier43Path.lineWidth = 2
        bezier43Path.lineCapStyle = .round
        bezier43Path.lineJoinStyle = .round
        bezier43Path.stroke()


        //// Bezier 45 Drawing
        let bezier45Path = UIBezierPath()
        bezier45Path.move(to: CGPoint(x: 754.5, y: 1173.5))
        bezier45Path.addLine(to: CGPoint(x: 814.5, y: 1152.5))
        UIColor.darkGray.setStroke()
        bezier45Path.lineWidth = 2
        bezier45Path.stroke()


        //// Bezier 44 Drawing
        let bezier44Path = UIBezierPath()
        bezier44Path.move(to: CGPoint(x: 739, y: 1128.5))
        bezier44Path.addLine(to: CGPoint(x: 799, y: 1107.5))
        UIColor.darkGray.setStroke()
        bezier44Path.lineWidth = 2
        bezier44Path.stroke()


        //// Bezier 46 Drawing
        let bezier46Path = UIBezierPath()
        bezier46Path.move(to: CGPoint(x: 963.5, y: 1218.5))
        bezier46Path.addLine(to: CGPoint(x: 935.5, y: 1134.5))
        bezier46Path.addLine(to: CGPoint(x: 921.5, y: 1139.5))
        bezier46Path.addLine(to: CGPoint(x: 949.5, y: 1129.5))
        UIColor.darkGray.setStroke()
        bezier46Path.lineWidth = 2
        bezier46Path.lineCapStyle = .round
        bezier46Path.lineJoinStyle = .round
        bezier46Path.stroke()


        //// Bezier 47 Drawing
        let bezier47Path = UIBezierPath()
        bezier47Path.move(to: CGPoint(x: 843.5, y: 1182.5))
        bezier47Path.addLine(to: CGPoint(x: 1013.5, y: 1122.5))
        UIColor.darkGray.setStroke()
        bezier47Path.lineWidth = 2
        bezier47Path.stroke()


        //// Bezier 48 Drawing
        let bezier48Path = UIBezierPath()
        bezier48Path.move(to: CGPoint(x: 846.5, y: 1191.5))
        bezier48Path.addLine(to: CGPoint(x: 839.5, y: 1169.5))
        bezier48Path.addLine(to: CGPoint(x: 850.5, y: 1165.5))
        UIColor.darkGray.setStroke()
        bezier48Path.lineWidth = 2
        bezier48Path.lineCapStyle = .round
        bezier48Path.lineJoinStyle = .round
        bezier48Path.stroke()


        //// Bezier 49 Drawing
        let bezier49Path = UIBezierPath()
        bezier49Path.move(to: CGPoint(x: 1018.5, y: 1135.5))
        bezier49Path.addLine(to: CGPoint(x: 1009.5, y: 1108.5))
        bezier49Path.addLine(to: CGPoint(x: 998.5, y: 1112.5))
        UIColor.darkGray.setStroke()
        bezier49Path.lineWidth = 2
        bezier49Path.lineCapStyle = .round
        bezier49Path.lineJoinStyle = .round
        bezier49Path.stroke()


        //// Bezier 50 Drawing
        let bezier50Path = UIBezierPath()
        bezier50Path.move(to: CGPoint(x: 819.5, y: 1010.5))
        bezier50Path.addLine(to: CGPoint(x: 763.5, y: 1029.5))
        bezier50Path.addLine(to: CGPoint(x: 768, y: 1042.5))
        UIColor.darkGray.setStroke()
        bezier50Path.lineWidth = 2
        bezier50Path.lineCapStyle = .round
        bezier50Path.lineJoinStyle = .round
        bezier50Path.stroke()


        //// Bezier 51 Drawing
        let bezier51Path = UIBezierPath()
        bezier51Path.move(to: CGPoint(x: 972.5, y: 1021.5))
        bezier51Path.addLine(to: CGPoint(x: 838, y: 1068))
        bezier51Path.addLine(to: CGPoint(x: 817.5, y: 1009.5))
        UIColor.darkGray.setStroke()
        bezier51Path.lineWidth = 2
        bezier51Path.lineCapStyle = .round
        bezier51Path.lineJoinStyle = .round
        bezier51Path.stroke()


        //// Bezier 52 Drawing
        let bezier52Path = UIBezierPath()
        bezier52Path.move(to: CGPoint(x: 863, y: 995.5))
        bezier52Path.addLine(to: CGPoint(x: 882.5, y: 1051.5))
        UIColor.darkGray.setStroke()
        bezier52Path.lineWidth = 2
        bezier52Path.stroke()


        //// Bezier 53 Drawing
        let bezier53Path = UIBezierPath()
        bezier53Path.move(to: CGPoint(x: 994.5, y: 1016.5))
        bezier53Path.addLine(to: CGPoint(x: 1008.5, y: 1058.5))
        bezier53Path.addLine(to: CGPoint(x: 1073.5, y: 1035.5))
        bezier53Path.addLine(to: CGPoint(x: 1058.5, y: 992.5))
        UIColor.darkGray.setStroke()
        bezier53Path.lineWidth = 2
        bezier53Path.lineCapStyle = .round
        bezier53Path.lineJoinStyle = .round
        bezier53Path.stroke()


        //// Bezier 54 Drawing
        let bezier54Path = UIBezierPath()
        bezier54Path.move(to: CGPoint(x: 1073.5, y: 1035.5))
        bezier54Path.addLine(to: CGPoint(x: 1158.5, y: 1005.5))
        UIColor.darkGray.setStroke()
        bezier54Path.lineWidth = 2
        bezier54Path.stroke()


        //// Bezier 55 Drawing
        let bezier55Path = UIBezierPath()
        bezier55Path.move(to: CGPoint(x: 1065.5, y: 889.5))
        bezier55Path.addLine(to: CGPoint(x: 1111.5, y: 1022.5))
        UIColor.darkGray.setStroke()
        bezier55Path.lineWidth = 2
        bezier55Path.stroke()


        //// Bezier 56 Drawing
        let bezier56Path = UIBezierPath()
        bezier56Path.move(to: CGPoint(x: 1075.5, y: 885.5))
        bezier56Path.addLine(to: CGPoint(x: 1121.5, y: 1017.5))
        UIColor.darkGray.setStroke()
        bezier56Path.lineWidth = 2
        bezier56Path.stroke()


        //// Bezier 57 Drawing
        let bezier57Path = UIBezierPath()
        bezier57Path.move(to: CGPoint(x: 1072.5, y: 913.5))
        bezier57Path.addLine(to: CGPoint(x: 1035.5, y: 926.5))
        UIColor.darkGray.setStroke()
        bezier57Path.lineWidth = 2
        bezier57Path.lineCapStyle = .round
        bezier57Path.stroke()


        //// Bezier 58 Drawing
        let bezier58Path = UIBezierPath()
        bezier58Path.move(to: CGPoint(x: 1080.5, y: 936.5))
        bezier58Path.addLine(to: CGPoint(x: 1043.5, y: 949.5))
        UIColor.darkGray.setStroke()
        bezier58Path.lineWidth = 2
        bezier58Path.lineCapStyle = .round
        bezier58Path.stroke()


        //// Bezier 59 Drawing
        let bezier59Path = UIBezierPath()
        bezier59Path.move(to: CGPoint(x: 1088.5, y: 957.5))
        bezier59Path.addLine(to: CGPoint(x: 1051.5, y: 970.5))
        UIColor.darkGray.setStroke()
        bezier59Path.lineWidth = 2
        bezier59Path.stroke()


        //// Bezier 60 Drawing
        let bezier60Path = UIBezierPath()
        bezier60Path.move(to: CGPoint(x: 1095.5, y: 979.5))
        bezier60Path.addLine(to: CGPoint(x: 1058.5, y: 992.5))
        UIColor.darkGray.setStroke()
        bezier60Path.lineWidth = 2
        bezier60Path.lineCapStyle = .round
        bezier60Path.stroke()


        //// Bezier 61 Drawing
        let bezier61Path = UIBezierPath()
        bezier61Path.move(to: CGPoint(x: 1103.5, y: 1001))
        bezier61Path.addLine(to: CGPoint(x: 1065.5, y: 1014.5))
        UIColor.darkGray.setStroke()
        bezier61Path.lineWidth = 2
        bezier61Path.stroke()


        //// Bezier 62 Drawing
        let bezier62Path = UIBezierPath()
        bezier62Path.move(to: CGPoint(x: 1135.5, y: 941))
        bezier62Path.addLine(to: CGPoint(x: 1099.5, y: 953.5))
        UIColor.darkGray.setStroke()
        bezier62Path.lineWidth = 2
        bezier62Path.stroke()


        //// Bezier 63 Drawing
        let bezier63Path = UIBezierPath()
        bezier63Path.move(to: CGPoint(x: 1128.5, y: 920))
        bezier63Path.addLine(to: CGPoint(x: 1092.5, y: 932.5))
        UIColor.darkGray.setStroke()
        bezier63Path.lineWidth = 2
        bezier63Path.stroke()


        //// Bezier 64 Drawing
        let bezier64Path = UIBezierPath()
        bezier64Path.move(to: CGPoint(x: 1142.5, y: 963))
        bezier64Path.addLine(to: CGPoint(x: 1106.5, y: 975.5))
        UIColor.darkGray.setStroke()
        bezier64Path.lineWidth = 2
        bezier64Path.stroke()


        //// Bezier 65 Drawing
        let bezier65Path = UIBezierPath()
        bezier65Path.move(to: CGPoint(x: 1150.5, y: 984.5))
        bezier65Path.addLine(to: CGPoint(x: 1114.5, y: 997.5))
        UIColor.darkGray.setStroke()
        bezier65Path.lineWidth = 2
        bezier65Path.stroke()


        //// Bezier 66 Drawing
        let bezier66Path = UIBezierPath()
        bezier66Path.move(to: CGPoint(x: 1181.5, y: 1073.5))
        bezier66Path.addLine(to: CGPoint(x: 1234.5, y: 1227.5))
        UIColor.darkGray.setStroke()
        bezier66Path.lineWidth = 2
        bezier66Path.stroke()


        //// Bezier 67 Drawing
        let bezier67Path = UIBezierPath()
        bezier67Path.move(to: CGPoint(x: 1193.5, y: 1068.5))
        bezier67Path.addLine(to: CGPoint(x: 1247.5, y: 1223.5))
        UIColor.darkGray.setStroke()
        bezier67Path.lineWidth = 2
        bezier67Path.stroke()


        //// Bezier 68 Drawing
        let bezier68Path = UIBezierPath()
        bezier68Path.move(to: CGPoint(x: 1143.5, y: 1087.5))
        bezier68Path.addLine(to: CGPoint(x: 1228.5, y: 1056.5))
        UIColor.darkGray.setStroke()
        bezier68Path.lineWidth = 2
        bezier68Path.stroke()


        //// Bezier 69 Drawing
        let bezier69Path = UIBezierPath()
        bezier69Path.move(to: CGPoint(x: 1195.5, y: 1115.5))
        bezier69Path.addLine(to: CGPoint(x: 1159.5, y: 1128.5))
        UIColor.darkGray.setStroke()
        bezier69Path.lineWidth = 2
        bezier69Path.stroke()


        //// Bezier 70 Drawing
        let bezier70Path = UIBezierPath()
        bezier70Path.move(to: CGPoint(x: 1210.5, y: 1160.5))
        bezier70Path.addLine(to: CGPoint(x: 1174.5, y: 1173.5))
        UIColor.darkGray.setStroke()
        bezier70Path.lineWidth = 2
        bezier70Path.stroke()


        //// Bezier 71 Drawing
        let bezier71Path = UIBezierPath()
        bezier71Path.move(to: CGPoint(x: 1218.5, y: 1182.5))
        bezier71Path.addLine(to: CGPoint(x: 1182.5, y: 1195.5))
        UIColor.darkGray.setStroke()
        bezier71Path.lineWidth = 2
        bezier71Path.stroke()


        //// Bezier 72 Drawing
        let bezier72Path = UIBezierPath()
        bezier72Path.move(to: CGPoint(x: 1226.5, y: 1205))
        bezier72Path.addLine(to: CGPoint(x: 1191.5, y: 1217.5))
        UIColor.darkGray.setStroke()
        bezier72Path.lineWidth = 2
        bezier72Path.stroke()


        //// Bezier 73 Drawing
        let bezier73Path = UIBezierPath()
        bezier73Path.move(to: CGPoint(x: 1274.5, y: 1187.5))
        bezier73Path.addLine(to: CGPoint(x: 1238.5, y: 1200.5))
        UIColor.darkGray.setStroke()
        bezier73Path.lineWidth = 2
        bezier73Path.stroke()


        //// Bezier 74 Drawing
        let bezier74Path = UIBezierPath()
        bezier74Path.move(to: CGPoint(x: 1265.5, y: 1165.5))
        bezier74Path.addLine(to: CGPoint(x: 1231.5, y: 1177.5))
        UIColor.darkGray.setStroke()
        bezier74Path.lineWidth = 2
        bezier74Path.stroke()


        //// Bezier 75 Drawing
        let bezier75Path = UIBezierPath()
        bezier75Path.move(to: CGPoint(x: 1259.5, y: 1142.5))
        bezier75Path.addLine(to: CGPoint(x: 1223.5, y: 1155.5))
        UIColor.darkGray.setStroke()
        bezier75Path.lineWidth = 2
        bezier75Path.stroke()


        //// Bezier 76 Drawing
        let bezier76Path = UIBezierPath()
        bezier76Path.move(to: CGPoint(x: 1251.5, y: 1120.5))
        bezier76Path.addLine(to: CGPoint(x: 1215.5, y: 1133.5))
        UIColor.darkGray.setStroke()
        bezier76Path.lineWidth = 2
        bezier76Path.stroke()


        //// Bezier 77 Drawing
        let bezier77Path = UIBezierPath()
        bezier77Path.move(to: CGPoint(x: 1244.5, y: 1098.5))
        bezier77Path.addLine(to: CGPoint(x: 1208.5, y: 1111.5))
        UIColor.darkGray.setStroke()
        bezier77Path.lineWidth = 2
        bezier77Path.stroke()


        //// Bezier 78 Drawing
        let bezier78Path = UIBezierPath()
        bezier78Path.move(to: CGPoint(x: 1236.5, y: 1076.5))
        bezier78Path.addLine(to: CGPoint(x: 1200.5, y: 1089.5))
        UIColor.darkGray.setStroke()
        bezier78Path.lineWidth = 2
        bezier78Path.stroke()


        //// Bezier 79 Drawing
        let bezier79Path = UIBezierPath()
        bezier79Path.move(to: CGPoint(x: 1193.5, y: 1068.5))
        bezier79Path.addLine(to: CGPoint(x: 1169.5, y: 1001.5))
        UIColor.darkGray.setStroke()
        bezier79Path.lineWidth = 2
        bezier79Path.stroke()


        //// Bezier 80 Drawing
        let bezier80Path = UIBezierPath()
        bezier80Path.move(to: CGPoint(x: 1145.5, y: 1088.5))
        bezier80Path.addLine(to: CGPoint(x: 1137, y: 1063.5))
        bezier80Path.addLine(to: CGPoint(x: 1088.5, y: 1080.5))
        bezier80Path.addLine(to: CGPoint(x: 1096.5, y: 1103.5))
        UIColor.darkGray.setStroke()
        bezier80Path.lineWidth = 2
        bezier80Path.lineCapStyle = .round
        bezier80Path.lineJoinStyle = .round
        bezier80Path.stroke()


        //// Bezier 81 Drawing
        let bezier81Path = UIBezierPath()
        bezier81Path.move(to: CGPoint(x: 1111.5, y: 1022.5))
        bezier81Path.addLine(to: CGPoint(x: 1119.5, y: 1045))
        bezier81Path.addLine(to: CGPoint(x: 1081.5, y: 1058.5))
        bezier81Path.addLine(to: CGPoint(x: 1073.5, y: 1035.5))
        UIColor.darkGray.setStroke()
        bezier81Path.lineWidth = 2
        bezier81Path.lineCapStyle = .round
        bezier81Path.lineJoinStyle = .round
        bezier81Path.stroke()


        //// Bezier 82 Drawing
        let bezier82Path = UIBezierPath()
        bezier82Path.move(to: CGPoint(x: 1158.5, y: 1005.5))
        bezier82Path.addLine(to: CGPoint(x: 1166.5, y: 1028.5))
        bezier82Path.addLine(to: CGPoint(x: 1130, y: 1041.5))
        bezier82Path.addLine(to: CGPoint(x: 1121.5, y: 1017.5))
        UIColor.darkGray.setStroke()
        bezier82Path.lineWidth = 2
        bezier82Path.lineCapStyle = .round
        bezier82Path.lineJoinStyle = .round
        bezier82Path.stroke()


        //// Bezier 83 Drawing
        let bezier83Path = UIBezierPath()
        bezier83Path.move(to: CGPoint(x: 662.5, y: 856))
        bezier83Path.addLine(to: CGPoint(x: 698.5, y: 843))
        bezier83Path.addLine(to: CGPoint(x: 684.5, y: 806.5))
        UIColor.darkGray.setStroke()
        bezier83Path.lineWidth = 2
        bezier83Path.lineCapStyle = .round
        bezier83Path.lineJoinStyle = .round
        bezier83Path.stroke()


        //// Bezier 84 Drawing
        let bezier84Path = UIBezierPath()
        bezier84Path.move(to: CGPoint(x: 670.5, y: 877.5))
        bezier84Path.addLine(to: CGPoint(x: 707.5, y: 864.5))
        bezier84Path.addLine(to: CGPoint(x: 739.5, y: 950.5))
        bezier84Path.addLine(to: CGPoint(x: 703.5, y: 963.5))
        UIColor.darkGray.setStroke()
        bezier84Path.lineWidth = 2
        bezier84Path.lineCapStyle = .round
        bezier84Path.lineJoinStyle = .round
        bezier84Path.stroke()


        //// Bezier 85 Drawing
        let bezier85Path = UIBezierPath()
        bezier85Path.move(to: CGPoint(x: 719.5, y: 896.5))
        bezier85Path.addLine(to: CGPoint(x: 683.5, y: 909.5))
        UIColor.darkGray.setStroke()
        bezier85Path.lineWidth = 2
        bezier85Path.lineCapStyle = .round
        bezier85Path.stroke()


        //// Bezier 86 Drawing
        let bezier86Path = UIBezierPath()
        bezier86Path.move(to: CGPoint(x: 731.5, y: 929.5))
        bezier86Path.addLine(to: CGPoint(x: 695.5, y: 942.5))
        UIColor.darkGray.setStroke()
        bezier86Path.lineWidth = 2
        bezier86Path.lineCapStyle = .round
        bezier86Path.stroke()


        //// Bezier 87 Drawing
        let bezier87Path = UIBezierPath()
        bezier87Path.move(to: CGPoint(x: 789.5, y: 932.8))
        bezier87Path.addLine(to: CGPoint(x: 752.2, y: 945.7))
        bezier87Path.addLine(to: CGPoint(x: 720, y: 859.9))
        bezier87Path.addLine(to: CGPoint(x: 707.5, y: 864.5))
        UIColor.darkGray.setStroke()
        bezier87Path.lineWidth = 2
        bezier87Path.lineCapStyle = .round
        bezier87Path.lineJoinStyle = .round
        bezier87Path.stroke()


        //// Bezier 88 Drawing
        let bezier88Path = UIBezierPath()
        bezier88Path.move(to: CGPoint(x: 781.5, y: 911.5))
        bezier88Path.addLine(to: CGPoint(x: 745.5, y: 924.5))
        UIColor.darkGray.setStroke()
        bezier88Path.lineWidth = 2
        bezier88Path.lineCapStyle = .round
        bezier88Path.stroke()


        //// Bezier 89 Drawing
        let bezier89Path = UIBezierPath()
        bezier89Path.move(to: CGPoint(x: 773.5, y: 889.5))
        bezier89Path.addLine(to: CGPoint(x: 737.5, y: 902.5))
        UIColor.darkGray.setStroke()
        bezier89Path.lineWidth = 2
        bezier89Path.lineCapStyle = .round
        bezier89Path.stroke()


        //// Bezier 90 Drawing
        let bezier90Path = UIBezierPath()
        bezier90Path.move(to: CGPoint(x: 771.5, y: 881.5))
        bezier90Path.addLine(to: CGPoint(x: 766.5, y: 867.9))
        bezier90Path.addLine(to: CGPoint(x: 729.5, y: 881.5))
        UIColor.darkGray.setStroke()
        bezier90Path.lineWidth = 2
        bezier90Path.lineCapStyle = .round
        bezier90Path.lineJoinStyle = .round
        bezier90Path.stroke()


        //// Bezier 91 Drawing
        let bezier91Path = UIBezierPath()
        bezier91Path.move(to: CGPoint(x: 758.5, y: 846.5))
        bezier91Path.addLine(to: CGPoint(x: 766.7, y: 868.5))
        UIColor.darkGray.setStroke()
        bezier91Path.lineWidth = 2
        bezier91Path.lineCapStyle = .round
        bezier91Path.stroke()


        //// Bezier 92 Drawing
        let bezier92Path = UIBezierPath()
        bezier92Path.move(to: CGPoint(x: 707.8, y: 668.5))
        bezier92Path.addLine(to: CGPoint(x: 782.3, y: 875.5))
        UIColor.darkGray.setStroke()
        bezier92Path.lineWidth = 2
        bezier92Path.lineCapStyle = .round
        bezier92Path.stroke()


        //// Bezier 93 Drawing
        let bezier93Path = UIBezierPath()
        bezier93Path.move(to: CGPoint(x: 695.8, y: 674.5))
        bezier93Path.addLine(to: CGPoint(x: 749.5, y: 824.6))
        bezier93Path.addLine(to: CGPoint(x: 711.4, y: 838.5))
        bezier93Path.addLine(to: CGPoint(x: 696.8, y: 800.5))
        UIColor.darkGray.setStroke()
        bezier93Path.lineWidth = 2
        bezier93Path.lineCapStyle = .round
        bezier93Path.lineJoinStyle = .round
        bezier93Path.stroke()


        //// Bezier 95 Drawing
        let bezier95Path = UIBezierPath()
        bezier95Path.move(to: CGPoint(x: 724.5, y: 756.5))
        bezier95Path.addLine(to: CGPoint(x: 686.5, y: 770.5))
        UIColor.darkGray.setStroke()
        bezier95Path.lineWidth = 2
        bezier95Path.lineCapStyle = .round
        bezier95Path.stroke()


        //// Bezier 96 Drawing
        let bezier96Path = UIBezierPath()
        bezier96Path.move(to: CGPoint(x: 715.5, y: 733.5))
        bezier96Path.addLine(to: CGPoint(x: 677.5, y: 747.5))
        UIColor.darkGray.setStroke()
        bezier96Path.lineWidth = 2
        bezier96Path.lineCapStyle = .round
        bezier96Path.stroke()


        //// Bezier 97 Drawing
        let bezier97Path = UIBezierPath()
        bezier97Path.move(to: CGPoint(x: 707.5, y: 710.5))
        bezier97Path.addLine(to: CGPoint(x: 669.5, y: 724.5))
        UIColor.darkGray.setStroke()
        bezier97Path.lineWidth = 2
        bezier97Path.lineCapStyle = .round
        bezier97Path.stroke()


        //// Bezier 98 Drawing
        let bezier98Path = UIBezierPath()
        bezier98Path.move(to: CGPoint(x: 759.5, y: 691.5))
        bezier98Path.addLine(to: CGPoint(x: 721.5, y: 705.5))
        UIColor.darkGray.setStroke()
        bezier98Path.lineWidth = 2
        bezier98Path.stroke()


        //// Bezier 99 Drawing
        let bezier99Path = UIBezierPath()
        bezier99Path.move(to: CGPoint(x: 767.5, y: 714.5))
        bezier99Path.addLine(to: CGPoint(x: 729.5, y: 728.5))
        UIColor.darkGray.setStroke()
        bezier99Path.lineWidth = 2
        bezier99Path.stroke()


        //// Bezier 100 Drawing
        let bezier100Path = UIBezierPath()
        bezier100Path.move(to: CGPoint(x: 774.5, y: 738.5))
        bezier100Path.addLine(to: CGPoint(x: 738.5, y: 751.5))
        UIColor.darkGray.setStroke()
        bezier100Path.lineWidth = 2
        bezier100Path.lineCapStyle = .round
        bezier100Path.stroke()


        //// Bezier 101 Drawing
        let bezier101Path = UIBezierPath()
        bezier101Path.move(to: CGPoint(x: 782.5, y: 761.5))
        bezier101Path.addLine(to: CGPoint(x: 746.5, y: 774.5))
        UIColor.darkGray.setStroke()
        bezier101Path.lineWidth = 2
        bezier101Path.lineCapStyle = .round
        bezier101Path.stroke()


        //// Bezier 102 Drawing
        let bezier102Path = UIBezierPath()
        bezier102Path.move(to: CGPoint(x: 790.5, y: 783.5))
        bezier102Path.addLine(to: CGPoint(x: 754.5, y: 796.5))
        UIColor.darkGray.setStroke()
        bezier102Path.lineWidth = 2
        bezier102Path.lineCapStyle = .round
        bezier102Path.stroke()


        //// Bezier 103 Drawing
        let bezier103Path = UIBezierPath()
        bezier103Path.move(to: CGPoint(x: 798.5, y: 806.5))
        bezier103Path.addLine(to: CGPoint(x: 762.5, y: 819.5))
        UIColor.darkGray.setStroke()
        bezier103Path.lineWidth = 2
        bezier103Path.lineCapStyle = .round
        bezier103Path.stroke()


        //// Bezier 104 Drawing
        let bezier104Path = UIBezierPath()
        bezier104Path.move(to: CGPoint(x: 806.5, y: 828.5))
        bezier104Path.addLine(to: CGPoint(x: 771.5, y: 841.5))
        UIColor.darkGray.setStroke()
        bezier104Path.lineWidth = 2
        bezier104Path.lineCapStyle = .round
        bezier104Path.stroke()


        //// Bezier 105 Drawing
        let bezier105Path = UIBezierPath()
        bezier105Path.move(to: CGPoint(x: 741.5, y: 801.5))
        bezier105Path.addLine(to: CGPoint(x: 702.5, y: 815.5))
        UIColor.darkGray.setStroke()
        bezier105Path.lineWidth = 2
        bezier105Path.stroke()


        //// Bezier 106 Drawing
        let bezier106Path = UIBezierPath()
        bezier106Path.move(to: CGPoint(x: 348.5, y: 295.5))
        bezier106Path.addLine(to: CGPoint(x: 360.5, y: 291.5))
        UIColor.darkGray.setStroke()
        bezier106Path.lineWidth = 2
        bezier106Path.stroke()


        //// Bezier 133 Drawing
        context.saveGState()
        context.translateBy(x: 982.26, y: 1018.25)
        context.rotate(by: -154 * CGFloat.pi/180)
        context.scaleBy(x: 2.5, y: 2.5)

        let bezier133Path = UIBezierPath()
        bezier133Path.move(to: CGPoint(x: -0.2, y: 6))
        bezier133Path.addLine(to: CGPoint(x: -0.2, y: 1))
        bezier133Path.addLine(to: CGPoint(x: 4.8, y: 1))
        bezier133Path.addLine(to: CGPoint(x: -0.2, y: 6))
        UIColor.darkGray.setFill()
        bezier133Path.fill()
        UIColor.darkGray.setStroke()
        bezier133Path.lineWidth = 0.5
        bezier133Path.lineCapStyle = .round
        bezier133Path.lineJoinStyle = .round
        bezier133Path.stroke()

        context.restoreGState()


        //// Bezier 131 Drawing
        context.saveGState()
        context.translateBy(x: 1045.27, y: 1123.01)
        context.rotate(by: 25.7 * CGFloat.pi/180)
        context.scaleBy(x: 2.5, y: 2.5)

        let bezier131Path = UIBezierPath()
        bezier131Path.move(to: CGPoint(x: -0.2, y: 6))
        bezier131Path.addLine(to: CGPoint(x: -0.2, y: 1))
        bezier131Path.addLine(to: CGPoint(x: 4.8, y: 1))
        bezier131Path.addLine(to: CGPoint(x: -0.2, y: 6))
        UIColor.darkGray.setFill()
        bezier131Path.fill()
        UIColor.darkGray.setStroke()
        bezier131Path.lineWidth = 0.5
        bezier131Path.lineCapStyle = .round
        bezier131Path.lineJoinStyle = .round
        bezier131Path.stroke()

        context.restoreGState()


        //// Bezier 126 Drawing
        context.saveGState()
        context.translateBy(x: 1067.21, y: 1115.03)
        context.rotate(by: 25.7 * CGFloat.pi/180)
        context.scaleBy(x: 2.5, y: 2.5)

        let bezier126Path = UIBezierPath()
        bezier126Path.move(to: CGPoint(x: 0, y: 6))
        bezier126Path.addLine(to: CGPoint(x: 0, y: 1))
        bezier126Path.addLine(to: CGPoint(x: 5, y: 1))
        bezier126Path.addLine(to: CGPoint(x: 0, y: 6))
        UIColor.darkGray.setFill()
        bezier126Path.fill()
        UIColor.darkGray.setStroke()
        bezier126Path.lineWidth = 0.5
        bezier126Path.lineCapStyle = .round
        bezier126Path.lineJoinStyle = .round
        bezier126Path.stroke()

        context.restoreGState()


        //// Bezier 127 Drawing
        context.saveGState()
        context.translateBy(x: 839.81, y: 1194.77)
        context.rotate(by: 25.7 * CGFloat.pi/180)
        context.scaleBy(x: 1.6, y: 1.6)

        let bezier127Path = UIBezierPath()
        bezier127Path.move(to: CGPoint(x: -0.5, y: 6))
        bezier127Path.addLine(to: CGPoint(x: -0.5, y: 1))
        bezier127Path.addLine(to: CGPoint(x: 4.5, y: 1))
        bezier127Path.addLine(to: CGPoint(x: -0.5, y: 6))
        UIColor.darkGray.setFill()
        bezier127Path.fill()
        UIColor.darkGray.setStroke()
        bezier127Path.lineWidth = 0.5
        bezier127Path.lineCapStyle = .round
        bezier127Path.lineJoinStyle = .round
        bezier127Path.stroke()

        context.restoreGState()


        //// Bezier 128 Drawing
        context.saveGState()
        context.translateBy(x: 200.27, y: 212.5)
        context.rotate(by: -154.3 * CGFloat.pi/180)
        context.scaleBy(x: 2.5, y: 2.5)

        let bezier128Path = UIBezierPath()
        bezier128Path.move(to: CGPoint(x: -0.2, y: 6))
        bezier128Path.addLine(to: CGPoint(x: -0.2, y: 1))
        bezier128Path.addLine(to: CGPoint(x: 4.8, y: 1))
        bezier128Path.addLine(to: CGPoint(x: -0.2, y: 6))
        UIColor.darkGray.setFill()
        bezier128Path.fill()
        UIColor.darkGray.setStroke()
        bezier128Path.lineWidth = 0.5
        bezier128Path.lineCapStyle = .round
        bezier128Path.lineJoinStyle = .round
        bezier128Path.stroke()

        context.restoreGState()


        //// Bezier 129 Drawing
        context.saveGState()
        context.translateBy(x: 222.21, y: 205.5)
        context.rotate(by: -154.3 * CGFloat.pi/180)
        context.scaleBy(x: 2.5, y: 2.5)

        let bezier129Path = UIBezierPath()
        bezier129Path.move(to: CGPoint(x: 0, y: 6))
        bezier129Path.addLine(to: CGPoint(x: 0, y: 1))
        bezier129Path.addLine(to: CGPoint(x: 5, y: 1))
        bezier129Path.addLine(to: CGPoint(x: 0, y: 6))
        UIColor.darkGray.setFill()
        bezier129Path.fill()
        UIColor.darkGray.setStroke()
        bezier129Path.lineWidth = 0.5
        bezier129Path.lineCapStyle = .round
        bezier129Path.lineJoinStyle = .round
        bezier129Path.stroke()

        context.restoreGState()


        //// Bezier 130 Drawing
        context.saveGState()
        context.translateBy(x: 477.93, y: 118)
        context.rotate(by: -154.3 * CGFloat.pi/180)
        context.scaleBy(x: 2.5, y: 2.5)

        let bezier130Path = UIBezierPath()
        bezier130Path.move(to: CGPoint(x: 0, y: 6))
        bezier130Path.addLine(to: CGPoint(x: 0, y: 1))
        bezier130Path.addLine(to: CGPoint(x: 5, y: 1))
        bezier130Path.addLine(to: CGPoint(x: 0, y: 6))
        UIColor.darkGray.setFill()
        bezier130Path.fill()
        UIColor.darkGray.setStroke()
        bezier130Path.lineWidth = 0.5
        bezier130Path.lineCapStyle = .round
        bezier130Path.lineJoinStyle = .round
        bezier130Path.stroke()

        context.restoreGState()


        //// Bezier 132 Drawing
        context.saveGState()
        context.translateBy(x: 241.36, y: 423.48)
        context.rotate(by: 30.5 * CGFloat.pi/180)
        context.scaleBy(x: 2.5, y: 2.5)

        let bezier132Path = UIBezierPath()
        bezier132Path.move(to: CGPoint(x: 0, y: 6))
        bezier132Path.addLine(to: CGPoint(x: 0, y: 1))
        bezier132Path.addLine(to: CGPoint(x: 5, y: 1))
        bezier132Path.addLine(to: CGPoint(x: 0, y: 6))
        UIColor.darkGray.setFill()
        bezier132Path.fill()
        UIColor.darkGray.setStroke()
        bezier132Path.lineWidth = 0.5
        bezier132Path.lineCapStyle = .round
        bezier132Path.lineJoinStyle = .round
        bezier132Path.stroke()

        context.restoreGState()


        //// E3
        context.saveGState()
        context.translateBy(x: 718, y: 259)
        context.rotate(by: 0.6 * CGFloat.pi/180)
        context.scaleBy(x: 1.08, y: 1.08)



        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.move(to: CGPoint(x: 0, y: 34))
        bezier2Path.addLine(to: CGPoint(x: 95, y: 297.5))
        bezier2Path.addLine(to: CGPoint(x: 187, y: 264))
        bezier2Path.addLine(to: CGPoint(x: 123.64, y: 89.76))
        bezier2Path.addLine(to: CGPoint(x: 91, y: 0))
        bezier2Path.addLine(to: CGPoint(x: 0, y: 34))
        bezier2Path.close()
        color3.setFill()
        bezier2Path.fill()
        UIColor.darkGray.setStroke()
        bezier2Path.lineWidth = 2
        bezier2Path.lineCapStyle = .round
        bezier2Path.lineJoinStyle = .round
        bezier2Path.stroke()


        //// Bezier 107 Drawing
        let bezier107Path = UIBezierPath()
        bezier107Path.move(to: CGPoint(x: 123.5, y: 89.5))
        bezier107Path.addLine(to: CGPoint(x: 99.5, y: 98.5))
        bezier107Path.addLine(to: CGPoint(x: 108.5, y: 123.5))
        UIColor.darkGray.setStroke()
        bezier107Path.lineWidth = 2
        bezier107Path.lineCapStyle = .round
        bezier107Path.lineJoinStyle = .round
        bezier107Path.stroke()


        //// Bezier 108 Drawing
        let bezier108Path = UIBezierPath()
        bezier108Path.move(to: CGPoint(x: 144.5, y: 148.5))
        bezier108Path.addLine(to: CGPoint(x: 110.5, y: 160.5))
        bezier108Path.addLine(to: CGPoint(x: 136.5, y: 231.5))
        bezier108Path.addLine(to: CGPoint(x: 170.5, y: 219.5))
        UIColor.darkGray.setStroke()
        bezier108Path.lineWidth = 2
        bezier108Path.lineCapStyle = .round
        bezier108Path.lineJoinStyle = .round
        bezier108Path.stroke()


        //// Bezier 109 Drawing
        let bezier109Path = UIBezierPath()
        bezier109Path.move(to: CGPoint(x: 32.5, y: 22.5))
        bezier109Path.addLine(to: CGPoint(x: 73.5, y: 135.5))
        bezier109Path.addLine(to: CGPoint(x: 82.5, y: 132.5))
        bezier109Path.addLine(to: CGPoint(x: 96.5, y: 170.5))
        bezier109Path.addLine(to: CGPoint(x: 111.5, y: 165.5))
        UIColor.darkGray.setStroke()
        bezier109Path.lineWidth = 2
        bezier109Path.lineCapStyle = .round
        bezier109Path.lineJoinStyle = .round
        bezier109Path.stroke()


        //// Bezier 110 Drawing
        let bezier110Path = UIBezierPath()
        bezier110Path.move(to: CGPoint(x: 119.5, y: 183.5))
        bezier110Path.addLine(to: CGPoint(x: 152.5, y: 171.5))
        UIColor.darkGray.setStroke()
        bezier110Path.lineWidth = 2
        bezier110Path.stroke()


        //// Bezier 111 Drawing
        let bezier111Path = UIBezierPath()
        bezier111Path.move(to: CGPoint(x: 39.5, y: 141.5))
        bezier111Path.addLine(to: CGPoint(x: 59.5, y: 134.5))
        bezier111Path.addLine(to: CGPoint(x: 71.5, y: 168.5))
        bezier111Path.addLine(to: CGPoint(x: 91.5, y: 161.5))
        UIColor.darkGray.setStroke()
        bezier111Path.lineWidth = 2
        bezier111Path.lineCapStyle = .round
        bezier111Path.lineJoinStyle = .round
        bezier111Path.stroke()


        //// Bezier 113 Drawing
        let bezier113Path = UIBezierPath()
        bezier113Path.move(to: CGPoint(x: 136.5, y: 231.5))
        bezier113Path.addLine(to: CGPoint(x: 78.8, y: 252.2))
        UIColor.darkGray.setStroke()
        bezier113Path.lineWidth = 2
        bezier113Path.lineCapStyle = .round
        bezier113Path.lineJoinStyle = .round
        bezier113Path.stroke()


        //// Bezier 114 Drawing
        let bezier114Path = UIBezierPath()
        bezier114Path.move(to: CGPoint(x: 127.5, y: 286.5))
        bezier114Path.addLine(to: CGPoint(x: 111, y: 240.5))
        UIColor.darkGray.setStroke()
        bezier114Path.lineWidth = 2
        bezier114Path.stroke()


        //// Bezier 116 Drawing
        let bezier116Path = UIBezierPath()
        bezier116Path.move(to: CGPoint(x: 120.5, y: 236.5))
        bezier116Path.addLine(to: CGPoint(x: 96.5, y: 170.5))
        UIColor.darkGray.setStroke()
        bezier116Path.lineWidth = 2
        bezier116Path.stroke()


        //// Bezier 112 Drawing
        let bezier112Path = UIBezierPath()
        bezier112Path.move(to: CGPoint(x: 58.5, y: 12.5))
        bezier112Path.addLine(to: CGPoint(x: 96.5, y: 118.5))
        bezier112Path.addLine(to: CGPoint(x: 71.5, y: 127.5))
        UIColor.darkGray.setStroke()
        bezier112Path.lineWidth = 2
        bezier112Path.lineCapStyle = .round
        bezier112Path.lineJoinStyle = .round
        bezier112Path.stroke()


        //// Bezier 115 Drawing
        let bezier115Path = UIBezierPath()
        bezier115Path.move(to: CGPoint(x: 99.5, y: 98.5))
        bezier115Path.addLine(to: CGPoint(x: 67.5, y: 9.5))
        UIColor.darkGray.setStroke()
        bezier115Path.lineWidth = 2
        bezier115Path.stroke()


        //// Bezier 117 Drawing
        let bezier117Path = UIBezierPath()
        bezier117Path.move(to: CGPoint(x: 87.5, y: 62.5))
        bezier117Path.addLine(to: CGPoint(x: 109.5, y: 54.5))
        UIColor.darkGray.setStroke()
        bezier117Path.lineWidth = 2
        bezier117Path.lineCapStyle = .round
        bezier117Path.lineJoinStyle = .round
        bezier117Path.stroke()


        //// Bezier 118 Drawing
        let bezier118Path = UIBezierPath()
        bezier118Path.move(to: CGPoint(x: 79.5, y: 38.5))
        bezier118Path.addLine(to: CGPoint(x: 101.5, y: 30.5))
        UIColor.darkGray.setStroke()
        bezier118Path.lineWidth = 2
        bezier118Path.lineCapStyle = .round
        bezier118Path.lineJoinStyle = .round
        bezier118Path.stroke()


        //// Bezier 119 Drawing
        let bezier119Path = UIBezierPath()
        bezier119Path.move(to: CGPoint(x: 42.5, y: 46.5))
        bezier119Path.addLine(to: CGPoint(x: 66.5, y: 37.8))
        UIColor.darkGray.setStroke()
        bezier119Path.lineWidth = 2
        bezier119Path.lineCapStyle = .round
        bezier119Path.lineJoinStyle = .round
        bezier119Path.stroke()


        //// Bezier 120 Drawing
        let bezier120Path = UIBezierPath()
        bezier120Path.move(to: CGPoint(x: 46.5, y: 58.5))
        bezier120Path.addLine(to: CGPoint(x: 70.5, y: 49.8))
        UIColor.darkGray.setStroke()
        bezier120Path.lineWidth = 2
        bezier120Path.lineCapStyle = .round
        bezier120Path.lineJoinStyle = .round
        bezier120Path.stroke()


        //// Bezier 121 Drawing
        let bezier121Path = UIBezierPath()
        bezier121Path.move(to: CGPoint(x: 57.5, y: 87.5))
        bezier121Path.addLine(to: CGPoint(x: 81.5, y: 78.8))
        UIColor.darkGray.setStroke()
        bezier121Path.lineWidth = 2
        bezier121Path.lineCapStyle = .round
        bezier121Path.lineJoinStyle = .round
        bezier121Path.stroke()


        //// Bezier 122 Drawing
        let bezier122Path = UIBezierPath()
        bezier122Path.move(to: CGPoint(x: 83.2, y: 122.5))
        bezier122Path.addLine(to: CGPoint(x: 79.5, y: 112.5))
        bezier122Path.addLine(to: CGPoint(x: 92.5, y: 107.9))
        UIColor.darkGray.setStroke()
        bezier122Path.lineWidth = 2
        bezier122Path.lineCapStyle = .round
        bezier122Path.lineJoinStyle = .round
        bezier122Path.stroke()


        //// Bezier 123 Drawing
        let bezier123Path = UIBezierPath()
        bezier123Path.move(to: CGPoint(x: 82.5, y: 132.5))
        bezier123Path.addLine(to: CGPoint(x: 79.5, y: 124.3))
        UIColor.darkGray.setStroke()
        bezier123Path.lineWidth = 2
        bezier123Path.stroke()


        //// Bezier 124 Drawing
        let bezier124Path = UIBezierPath()
        bezier124Path.move(to: CGPoint(x: 86.5, y: 89.5))
        bezier124Path.addLine(to: CGPoint(x: 94.5, y: 86.7))
        UIColor.darkGray.setStroke()
        bezier124Path.lineWidth = 2
        bezier124Path.stroke()


        //// Bezier 125 Drawing
        let bezier125Path = UIBezierPath()
        bezier125Path.move(to: CGPoint(x: 96.5, y: 118.5))
        bezier125Path.addLine(to: CGPoint(x: 104.5, y: 115.7))
        UIColor.darkGray.setStroke()
        bezier125Path.lineWidth = 2
        bezier125Path.lineCapStyle = .round
        bezier125Path.lineJoinStyle = .round
        bezier125Path.stroke()


        //// Bezier 134 Drawing
        context.saveGState()
        context.translateBy(x: 140.98, y: 134.41)
        context.rotate(by: -65 * CGFloat.pi/180)
        context.scaleBy(x: 2.5, y: 2.5)

        let bezier134Path = UIBezierPath()
        bezier134Path.move(to: CGPoint(x: 0, y: 6))
        bezier134Path.addLine(to: CGPoint(x: 0, y: 1))
        bezier134Path.addLine(to: CGPoint(x: 5, y: 1))
        bezier134Path.addLine(to: CGPoint(x: 0, y: 6))
        UIColor.darkGray.setFill()
        bezier134Path.fill()
        UIColor.darkGray.setStroke()
        bezier134Path.lineWidth = 0.5
        bezier134Path.lineCapStyle = .round
        bezier134Path.lineJoinStyle = .round
        bezier134Path.stroke()

        context.restoreGState()



        context.restoreGState()


        //// Bezier 135 Drawing
        context.saveGState()
        context.translateBy(x: 386.18, y: 815.27)
        context.rotate(by: 135.5 * CGFloat.pi/180)
        context.scaleBy(x: 2.5, y: 2.5)

        let bezier135Path = UIBezierPath()
        bezier135Path.move(to: CGPoint(x: 0, y: 6))
        bezier135Path.addLine(to: CGPoint(x: 0, y: 1))
        bezier135Path.addLine(to: CGPoint(x: 5, y: 1))
        bezier135Path.addLine(to: CGPoint(x: 0, y: 6))
        UIColor.darkGray.setFill()
        bezier135Path.fill()
        UIColor.darkGray.setStroke()
        bezier135Path.lineWidth = 0.5
        bezier135Path.lineCapStyle = .round
        bezier135Path.lineJoinStyle = .round
        bezier135Path.stroke()

        context.restoreGState()


        //// Bezier 136 Drawing
        context.saveGState()
        context.translateBy(x: 386.18, y: 878.27)
        context.rotate(by: 135.5 * CGFloat.pi/180)
        context.scaleBy(x: 2.5, y: 2.5)

        let bezier136Path = UIBezierPath()
        bezier136Path.move(to: CGPoint(x: 0, y: 6))
        bezier136Path.addLine(to: CGPoint(x: 0, y: 1))
        bezier136Path.addLine(to: CGPoint(x: 5, y: 1))
        bezier136Path.addLine(to: CGPoint(x: 0, y: 6))
        UIColor.darkGray.setFill()
        bezier136Path.fill()
        UIColor.darkGray.setStroke()
        bezier136Path.lineWidth = 0.5
        bezier136Path.lineCapStyle = .round
        bezier136Path.lineJoinStyle = .round
        bezier136Path.stroke()

        context.restoreGState()



        context.restoreGState()
        
        context.restoreGState()

    }

    //// Generated Images

    @objc dynamic public class var imageOfCanvas1: UIImage {
        if Cache.imageOfCanvas1 != nil {
            return Cache.imageOfCanvas1!
        }

        UIGraphicsBeginImageContextWithOptions(CGSize(width: 1343, height: 1308), false, 0)
            IZGroundfloor.drawCanvas1()

        Cache.imageOfCanvas1 = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return Cache.imageOfCanvas1!
    }

    //// Customization Infrastructure

    @objc @IBOutlet dynamic var canvas1Targets: [AnyObject]! {
        get { return Cache.canvas1Targets }
        set {
            Cache.canvas1Targets = newValue
            for target: AnyObject in newValue {
                let _ = target.perform(NSSelectorFromString("setImage:"), with: IZGroundfloor.imageOfCanvas1)
            }
        }
    }




    @objc(IZGroundfloorResizingBehavior)
    public enum ResizingBehavior: Int {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.

        public func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }

            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)

            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }

            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
}
