//
//  IZGroundfloor.swift
//  InfozentrumGuide
//
//  Created by RWTH on 17.01.18.
//  Copyright © 2018 RWTH. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//
//  This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
//



import UIKit

public class IZGroundfloor : NSObject {

    //// Cache

    private struct Cache {
        static var imageOfCanvas1: UIImage?
        static var canvas1Targets: [AnyObject]?
    }

    //// Drawing Methods

    @objc dynamic public class func drawCanvas1(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 1343, height: 1308), resizing: ResizingBehavior = .aspectFit) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        //// Resize to Target Frame
        context.saveGState()
        let resizedFrame: CGRect = resizing.apply(rect: CGRect(x: 0, y: 0, width: 1343, height: 1308), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 1343, y: resizedFrame.height / 1308)


        //// Color Declarations
        let color = UIColor(red: 0.706, green: 0.876, blue: 0.613, alpha: 1.000)
        let color3 = UIColor(red: 0.945, green: 0.945, blue: 0.945, alpha: 1.000)

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: 16.5, y: 242.5))
        bezierPath.addCurve(to: CGPoint(x: 136.5, y: 201.5), controlPoint1: CGPoint(x: 119.5, y: 207.5), controlPoint2: CGPoint(x: 136.5, y: 201.5))
        bezierPath.addLine(to: CGPoint(x: 152.5, y: 249.5))
        bezierPath.addLine(to: CGPoint(x: 330, y: 189))
        bezierPath.addLine(to: CGPoint(x: 293.5, y: 140.5))
        bezierPath.addLine(to: CGPoint(x: 317.5, y: 123.5))
        bezierPath.addLine(to: CGPoint(x: 349.5, y: 108.5))
        bezierPath.addLine(to: CGPoint(x: 382.5, y: 100.5))
        bezierPath.addLine(to: CGPoint(x: 416.5, y: 97.5))
        bezierPath.addLine(to: CGPoint(x: 417, y: 160))
        bezierPath.addLine(to: CGPoint(x: 508, y: 128))
        bezierPath.addLine(to: CGPoint(x: 479.5, y: 47.5))
        bezierPath.addLine(to: CGPoint(x: 578.5, y: 13.5))
        bezierPath.addLine(to: CGPoint(x: 627.5, y: 149.5))
        bezierPath.addLine(to: CGPoint(x: 606.5, y: 157.5))
        bezierPath.addLine(to: CGPoint(x: 646.5, y: 272.5))
        bezierPath.addLine(to: CGPoint(x: 384.5, y: 365.5))
        bezierPath.addLine(to: CGPoint(x: 521.5, y: 764.5))
        bezierPath.addLine(to: CGPoint(x: 537.5, y: 758.5))
        bezierPath.addLine(to: CGPoint(x: 561, y: 826))
        bezierPath.addLine(to: CGPoint(x: 537, y: 835))
        bezierPath.addLine(to: CGPoint(x: 550.5, y: 872.5))
        bezierPath.addLine(to: CGPoint(x: 679.5, y: 869.5))
        bezierPath.addLine(to: CGPoint(x: 665.5, y: 832.5))
        bezierPath.addLine(to: CGPoint(x: 713.5, y: 814.5))
        bezierPath.addLine(to: CGPoint(x: 672.5, y: 701.5))
        bezierPath.addLine(to: CGPoint(x: 724.5, y: 682.5))
        bezierPath.addLine(to: CGPoint(x: 719.5, y: 668.5))
        bezierPath.addLine(to: CGPoint(x: 757.5, y: 654.5))
        bezierPath.addLine(to: CGPoint(x: 835.5, y: 876.5))
        bezierPath.addLine(to: CGPoint(x: 787.5, y: 893.5))
        bezierPath.addLine(to: CGPoint(x: 834.5, y: 1024.5))
        bezierPath.addLine(to: CGPoint(x: 879.56, y: 1009.37))
        bezierPath.addLine(to: CGPoint(x: 971.5, y: 978.5))
        bezierPath.addLine(to: CGPoint(x: 990.5, y: 1036.5))
        bezierPath.addLine(to: CGPoint(x: 1075.5, y: 1007.5))
        bezierPath.addLine(to: CGPoint(x: 1052.18, y: 940.44))
        bezierPath.addLine(to: CGPoint(x: 1043.5, y: 915.5))
        bezierPath.addLine(to: CGPoint(x: 1129, y: 887))
        bezierPath.addLine(to: CGPoint(x: 1175, y: 1019))
        bezierPath.addLine(to: CGPoint(x: 1221.5, y: 1002.5))
        bezierPath.addLine(to: CGPoint(x: 1299.5, y: 1224.5))
        bezierPath.addLine(to: CGPoint(x: 1215.5, y: 1254.5))
        bezierPath.addLine(to: CGPoint(x: 1161.5, y: 1100.5))
        bezierPath.addLine(to: CGPoint(x: 1033.5, y: 1144.5))
        bezierPath.addLine(to: CGPoint(x: 1053.5, y: 1203.5))
        bezierPath.addLine(to: CGPoint(x: 1040.5, y: 1215.5))
        bezierPath.addLine(to: CGPoint(x: 1025.5, y: 1223.5))
        bezierPath.addLine(to: CGPoint(x: 1010.5, y: 1228.5))
        bezierPath.addLine(to: CGPoint(x: 994.5, y: 1230.5))
        bezierPath.addLine(to: CGPoint(x: 979.5, y: 1230.5))
        bezierPath.addLine(to: CGPoint(x: 986.5, y: 1250.5))
        bezierPath.addLine(to: CGPoint(x: 974.5, y: 1263.5))
        bezierPath.addLine(to: CGPoint(x: 957.5, y: 1275.5))
        bezierPath.addLine(to: CGPoint(x: 937.5, y: 1284.5))
        bezierPath.addLine(to: CGPoint(x: 924.82, y: 1287.49))
        bezierPath.addLine(to: CGPoint(x: 912.01, y: 1288.5))
        bezierPath.addLine(to: CGPoint(x: 901.37, y: 1288.08))
        bezierPath.addLine(to: CGPoint(x: 889.5, y: 1285.5))
        bezierPath.addLine(to: CGPoint(x: 862.5, y: 1203.5))
        bezierPath.addLine(to: CGPoint(x: 845.5, y: 1209.5))
        bezierPath.addLine(to: CGPoint(x: 854.5, y: 1235.5))
        bezierPath.addLine(to: CGPoint(x: 793.5, y: 1257.5))
        bezierPath.addLine(to: CGPoint(x: 740.5, y: 1094.5))
        bezierPath.addLine(to: CGPoint(x: 651.5, y: 1125.5))
        bezierPath.addLine(to: CGPoint(x: 629.5, y: 1060.5))
        bezierPath.addLine(to: CGPoint(x: 648.5, y: 1053.5))
        bezierPath.addLine(to: CGPoint(x: 594.5, y: 888.5))
        bezierPath.addLine(to: CGPoint(x: 483, y: 889))
        bezierPath.addLine(to: CGPoint(x: 483.5, y: 1029.5))
        bezierPath.addLine(to: CGPoint(x: 512, y: 1030))
        bezierPath.addLine(to: CGPoint(x: 512.5, y: 1112.5))
        bezierPath.addLine(to: CGPoint(x: 355.5, y: 1109.5))
        bezierPath.addLine(to: CGPoint(x: 354.5, y: 991.5))
        bezierPath.addLine(to: CGPoint(x: 403.5, y: 991.5))
        bezierPath.addLine(to: CGPoint(x: 404.5, y: 806.5))
        bezierPath.addLine(to: CGPoint(x: 399, y: 791))
        bezierPath.addLine(to: CGPoint(x: 411.5, y: 786.5))
        bezierPath.addLine(to: CGPoint(x: 378.97, y: 691.77))
        bezierPath.addLine(to: CGPoint(x: 287.5, y: 428.5))
        bezierPath.addLine(to: CGPoint(x: 117.5, y: 472.5))
        bezierPath.addLine(to: CGPoint(x: 103.5, y: 432.5))
        bezierPath.addLine(to: CGPoint(x: 81.5, y: 440.5))
        bezierPath.addLine(to: CGPoint(x: 16.5, y: 242.5))
        color3.setFill()
        bezierPath.fill()
        UIColor.darkGray.setStroke()
        bezierPath.lineWidth = 2
        bezierPath.lineCapStyle = .round
        bezierPath.lineJoinStyle = .round
        bezierPath.stroke()


        //// Bezier 94 Drawing
        let bezier94Path = UIBezierPath()
        bezier94Path.move(to: CGPoint(x: 686, y: 1091))
        bezier94Path.addLine(to: CGPoint(x: 617.5, y: 886.5))
        bezier94Path.addLine(to: CGPoint(x: 684.5, y: 886.5))
        bezier94Path.addLine(to: CGPoint(x: 753.5, y: 1067.5))
        bezier94Path.addLine(to: CGPoint(x: 686, y: 1091))
        bezier94Path.close()
        color.setFill()
        bezier94Path.fill()


        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.move(to: CGPoint(x: 707.5, y: 384.5))
        bezier2Path.addLine(to: CGPoint(x: 802.5, y: 648.5))
        bezier2Path.addLine(to: CGPoint(x: 894.5, y: 614.5))
        bezier2Path.addLine(to: CGPoint(x: 798.5, y: 350.5))
        bezier2Path.addLine(to: CGPoint(x: 707.5, y: 384.5))
        bezier2Path.close()
        color3.setFill()
        bezier2Path.fill()
        UIColor.darkGray.setStroke()
        bezier2Path.lineWidth = 2
        bezier2Path.lineCapStyle = .round
        bezier2Path.lineJoinStyle = .round
        bezier2Path.stroke()


        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.move(to: CGPoint(x: 397, y: 361))
        bezier3Path.addLine(to: CGPoint(x: 377, y: 305))
        bezier3Path.addLine(to: CGPoint(x: 561, y: 240))
        bezier3Path.addLine(to: CGPoint(x: 520, y: 124))
        bezier3Path.addLine(to: CGPoint(x: 508, y: 128))
        UIColor.darkGray.setStroke()
        bezier3Path.lineWidth = 2
        bezier3Path.lineCapStyle = .round
        bezier3Path.lineJoinStyle = .round
        bezier3Path.stroke()


        //// Bezier 4 Drawing
        let bezier4Path = UIBezierPath()
        bezier4Path.move(to: CGPoint(x: 277.5, y: 229))
        bezier4Path.addLine(to: CGPoint(x: 344, y: 206))
        bezier4Path.addLine(to: CGPoint(x: 354, y: 235))
        bezier4Path.addLine(to: CGPoint(x: 430, y: 209))
        bezier4Path.addLine(to: CGPoint(x: 420, y: 180))
        bezier4Path.addLine(to: CGPoint(x: 487, y: 156))
        bezier4Path.addLine(to: CGPoint(x: 515, y: 235))
        bezier4Path.addLine(to: CGPoint(x: 320, y: 304))
        bezier4Path.addLine(to: CGPoint(x: 277.5, y: 229))
        bezier4Path.close()
        color.setFill()
        bezier4Path.fill()
        UIColor.darkGray.setStroke()
        bezier4Path.lineWidth = 2
        bezier4Path.lineCapStyle = .round
        bezier4Path.lineJoinStyle = .round
        bezier4Path.stroke()


        //// Bezier 5 Drawing
        let bezier5Path = UIBezierPath()
        bezier5Path.move(to: CGPoint(x: 102, y: 433))
        bezier5Path.addLine(to: CGPoint(x: 203, y: 397))
        bezier5Path.addLine(to: CGPoint(x: 220, y: 446))
        UIColor.darkGray.setStroke()
        bezier5Path.lineWidth = 2
        bezier5Path.lineCapStyle = .round
        bezier5Path.lineJoinStyle = .round
        bezier5Path.stroke()


        //// Bezier 6 Drawing
        let bezier6Path = UIBezierPath()
        bezier6Path.move(to: CGPoint(x: 203, y: 397))
        bezier6Path.addLine(to: CGPoint(x: 152, y: 248))
        UIColor.darkGray.setStroke()
        bezier6Path.lineWidth = 2
        bezier6Path.lineCapStyle = .round
        bezier6Path.lineJoinStyle = .round
        bezier6Path.stroke()


        //// Bezier 7 Drawing
        let bezier7Path = UIBezierPath()
        bezier7Path.move(to: CGPoint(x: 344, y: 206))
        bezier7Path.addLine(to: CGPoint(x: 330, y: 189))
        UIColor.darkGray.setStroke()
        bezier7Path.lineWidth = 2
        bezier7Path.lineCapStyle = .round
        bezier7Path.lineJoinStyle = .round
        bezier7Path.stroke()


        //// Bezier 8 Drawing
        let bezier8Path = UIBezierPath()
        bezier8Path.move(to: CGPoint(x: 420, y: 180))
        bezier8Path.addLine(to: CGPoint(x: 417, y: 160))
        UIColor.red.setFill()
        bezier8Path.fill()
        UIColor.darkGray.setStroke()
        bezier8Path.lineWidth = 2
        bezier8Path.lineCapStyle = .round
        bezier8Path.lineJoinStyle = .round
        bezier8Path.stroke()


        //// Bezier 9 Drawing
        let bezier9Path = UIBezierPath()
        bezier9Path.move(to: CGPoint(x: 385, y: 367))
        bezier9Path.addLine(to: CGPoint(x: 358, y: 291))
        UIColor.darkGray.setStroke()
        bezier9Path.lineWidth = 2
        bezier9Path.lineCapStyle = .round
        bezier9Path.lineJoinStyle = .round
        bezier9Path.stroke()


        //// Bezier 10 Drawing
        let bezier10Path = UIBezierPath()
        bezier10Path.move(to: CGPoint(x: 212, y: 421))
        bezier10Path.addLine(to: CGPoint(x: 264.51, y: 407.42))
        bezier10Path.addLine(to: CGPoint(x: 281.6, y: 403))
        bezier10Path.addLine(to: CGPoint(x: 384, y: 367))
        UIColor.darkGray.setStroke()
        bezier10Path.lineWidth = 2
        bezier10Path.lineCapStyle = .round
        bezier10Path.lineJoinStyle = .round
        bezier10Path.stroke()


        //// Bezier 11 Drawing
        let bezier11Path = UIBezierPath()
        bezier11Path.move(to: CGPoint(x: 264, y: 408))
        bezier11Path.addLine(to: CGPoint(x: 270, y: 432))
        UIColor.darkGray.setStroke()
        bezier11Path.lineWidth = 2
        bezier11Path.lineCapStyle = .round
        bezier11Path.lineJoinStyle = .round
        bezier11Path.stroke()


        //// Bezier 12 Drawing
        let bezier12Path = UIBezierPath()
        bezier12Path.move(to: CGPoint(x: 278, y: 230))
        bezier12Path.addLine(to: CGPoint(x: 267, y: 211))
        UIColor.red.setFill()
        bezier12Path.fill()
        UIColor.darkGray.setStroke()
        bezier12Path.lineWidth = 2
        bezier12Path.lineCapStyle = .round
        bezier12Path.lineJoinStyle = .round
        bezier12Path.stroke()


        //// Bezier 13 Drawing
        let bezier13Path = UIBezierPath()
        bezier13Path.move(to: CGPoint(x: 526, y: 142))
        bezier13Path.addLine(to: CGPoint(x: 487, y: 156))
        bezier13Path.addLine(to: CGPoint(x: 481, y: 138))
        UIColor.darkGray.setStroke()
        bezier13Path.lineWidth = 2
        bezier13Path.lineCapStyle = .round
        bezier13Path.lineJoinStyle = .round
        bezier13Path.stroke()


        //// Bezier 14 Drawing
        let bezier14Path = UIBezierPath()
        bezier14Path.move(to: CGPoint(x: 533, y: 157))
        bezier14Path.addLine(to: CGPoint(x: 598, y: 134))
        bezier14Path.addLine(to: CGPoint(x: 607, y: 159))
        UIColor.darkGray.setStroke()
        bezier14Path.lineWidth = 2
        bezier14Path.lineCapStyle = .round
        bezier14Path.lineJoinStyle = .round
        bezier14Path.stroke()


        //// Bezier 15 Drawing
        let bezier15Path = UIBezierPath()
        bezier15Path.move(to: CGPoint(x: 170, y: 458))
        bezier15Path.addLine(to: CGPoint(x: 155, y: 414))
        UIColor.darkGray.setStroke()
        bezier15Path.lineWidth = 2
        bezier15Path.lineCapStyle = .round
        bezier15Path.lineJoinStyle = .round
        bezier15Path.stroke()


        //// Bezier 16 Drawing
        let bezier16Path = UIBezierPath()
        bezier16Path.move(to: CGPoint(x: 319, y: 390))
        bezier16Path.addLine(to: CGPoint(x: 402, y: 630))
        bezier16Path.addLine(to: CGPoint(x: 363, y: 644))
        UIColor.darkGray.setStroke()
        bezier16Path.lineWidth = 2
        bezier16Path.lineCapStyle = .round
        bezier16Path.lineJoinStyle = .round
        bezier16Path.stroke()


        //// Bezier 17 Drawing
        let bezier17Path = UIBezierPath()
        bezier17Path.move(to: CGPoint(x: 343, y: 381))
        bezier17Path.addLine(to: CGPoint(x: 419.32, y: 599.22))
        bezier17Path.addLine(to: CGPoint(x: 430.51, y: 595.7))
        bezier17Path.addLine(to: CGPoint(x: 454.93, y: 665.59))
        bezier17Path.addLine(to: CGPoint(x: 442.72, y: 669.61))
        bezier17Path.addLine(to: CGPoint(x: 459, y: 716.87))
        bezier17Path.addLine(to: CGPoint(x: 395.91, y: 739.5))
        UIColor.darkGray.setStroke()
        bezier17Path.lineWidth = 2
        bezier17Path.lineCapStyle = .round
        bezier17Path.lineJoinStyle = .round
        bezier17Path.stroke()


        //// Bezier 18 Drawing
        let bezier18Path = UIBezierPath()
        bezier18Path.move(to: CGPoint(x: 379, y: 691))
        bezier18Path.addLine(to: CGPoint(x: 419, y: 677))
        bezier18Path.addLine(to: CGPoint(x: 435, y: 724))
        UIColor.darkGray.setStroke()
        bezier18Path.lineWidth = 2
        bezier18Path.lineCapStyle = .round
        bezier18Path.lineJoinStyle = .round
        bezier18Path.stroke()


        //// Bezier 19 Drawing
        context.saveGState()
        context.translateBy(x: 288, y: 429)

        let bezier19Path = UIBezierPath()
        bezier19Path.move(to: CGPoint(x: -6.3, y: 1))
        bezier19Path.addLine(to: CGPoint(x: 39, y: -14))
        UIColor.darkGray.setStroke()
        bezier19Path.lineWidth = 2
        bezier19Path.lineCapStyle = .round
        bezier19Path.lineJoinStyle = .round
        bezier19Path.stroke()

        context.restoreGState()


        //// Bezier 20 Drawing
        let bezier20Path = UIBezierPath()
        bezier20Path.move(to: CGPoint(x: 295, y: 452))
        bezier20Path.addLine(to: CGPoint(x: 336, y: 438))
        UIColor.darkGray.setStroke()
        bezier20Path.lineWidth = 2
        bezier20Path.stroke()


        //// Bezier 21 Drawing
        let bezier21Path = UIBezierPath()
        bezier21Path.move(to: CGPoint(x: 320, y: 524))
        bezier21Path.addLine(to: CGPoint(x: 361, y: 510))
        UIColor.darkGray.setStroke()
        bezier21Path.lineWidth = 2
        bezier21Path.stroke()


        //// Bezier 22 Drawing
        context.saveGState()
        context.translateBy(x: 329, y: 534)
        context.scaleBy(x: 0.97, y: 0.97)

        let bezier22Path = UIBezierPath()
        bezier22Path.move(to: CGPoint(x: 0, y: 14))
        bezier22Path.addLine(to: CGPoint(x: 41, y: 0))
        UIColor.darkGray.setStroke()
        bezier22Path.lineWidth = 2
        bezier22Path.stroke()

        context.restoreGState()


        //// Bezier 23 Drawing
        let bezier23Path = UIBezierPath()
        bezier23Path.move(to: CGPoint(x: 337, y: 572))
        bezier23Path.addLine(to: CGPoint(x: 378, y: 558))
        UIColor.darkGray.setStroke()
        bezier23Path.lineWidth = 2
        bezier23Path.stroke()


        //// Bezier 24 Drawing
        context.saveGState()
        context.translateBy(x: 346, y: 582)
        context.scaleBy(x: 0.98, y: 0.98)

        let bezier24Path = UIBezierPath()
        bezier24Path.move(to: CGPoint(x: 0, y: 14))
        bezier24Path.addLine(to: CGPoint(x: 40, y: 0))
        UIColor.darkGray.setStroke()
        bezier24Path.lineWidth = 2
        bezier24Path.lineCapStyle = .round
        bezier24Path.stroke()

        context.restoreGState()


        //// Bezier 25 Drawing
        context.saveGState()
        context.translateBy(x: 354, y: 606)
        context.scaleBy(x: 0.96, y: 0.96)

        let bezier25Path = UIBezierPath()
        bezier25Path.move(to: CGPoint(x: 0, y: 14.6))
        bezier25Path.addLine(to: CGPoint(x: 41, y: 0))
        UIColor.darkGray.setStroke()
        bezier25Path.lineWidth = 2
        bezier25Path.lineCapStyle = .round
        bezier25Path.lineJoinStyle = .round
        bezier25Path.stroke()

        context.restoreGState()


        //// Bezier 26 Drawing
        let bezier26Path = UIBezierPath()
        bezier26Path.move(to: CGPoint(x: 411, y: 574))
        bezier26Path.addLine(to: CGPoint(x: 452, y: 560))
        UIColor.darkGray.setStroke()
        bezier26Path.lineWidth = 2
        bezier26Path.stroke()


        //// Bezier 27 Drawing
        let bezier27Path = UIBezierPath()
        bezier27Path.move(to: CGPoint(x: 402, y: 550))
        bezier27Path.addLine(to: CGPoint(x: 443, y: 536))
        UIColor.darkGray.setStroke()
        bezier27Path.lineWidth = 2
        bezier27Path.stroke()


        //// Bezier 28 Drawing
        let bezier28Path = UIBezierPath()
        bezier28Path.move(to: CGPoint(x: 394, y: 526))
        bezier28Path.addLine(to: CGPoint(x: 435, y: 512))
        UIColor.darkGray.setStroke()
        bezier28Path.lineWidth = 2
        bezier28Path.stroke()


        //// Bezier 29 Drawing
        let bezier29Path = UIBezierPath()
        bezier29Path.move(to: CGPoint(x: 385, y: 502))
        bezier29Path.addLine(to: CGPoint(x: 426, y: 488))
        UIColor.darkGray.setStroke()
        bezier29Path.lineWidth = 2
        bezier29Path.stroke()


        //// Bezier 30 Drawing
        let bezier30Path = UIBezierPath()
        bezier30Path.move(to: CGPoint(x: 361, y: 429))
        bezier30Path.addLine(to: CGPoint(x: 402, y: 415))
        UIColor.darkGray.setStroke()
        bezier30Path.lineWidth = 2
        bezier30Path.stroke()


        //// Bezier 31 Drawing
        context.saveGState()
        context.translateBy(x: 430, y: 585.5)
        context.scaleBy(x: 1.01, y: 1)

        let bezier31Path = UIBezierPath()
        bezier31Path.move(to: CGPoint(x: -1.98, y: 11))
        bezier31Path.addLine(to: CGPoint(x: 29, y: 0))
        UIColor.darkGray.setStroke()
        bezier31Path.lineWidth = 2
        bezier31Path.lineCapStyle = .round
        bezier31Path.stroke()

        context.restoreGState()


        //// Bezier 32 Drawing
        let bezier32Path = UIBezierPath()
        bezier32Path.move(to: CGPoint(x: 438, y: 618))
        bezier32Path.addLine(to: CGPoint(x: 467, y: 608))
        UIColor.darkGray.setStroke()
        bezier32Path.lineWidth = 2
        bezier32Path.stroke()


        //// Bezier 33 Drawing
        let bezier33Path = UIBezierPath()
        bezier33Path.move(to: CGPoint(x: 452, y: 666.5))
        bezier33Path.addLine(to: CGPoint(x: 483, y: 655.5))
        UIColor.darkGray.setStroke()
        bezier33Path.lineWidth = 2
        bezier33Path.lineCapStyle = .round
        bezier33Path.stroke()


        //// Bezier 34 Drawing
        let bezier34Path = UIBezierPath()
        bezier34Path.move(to: CGPoint(x: 523, y: 764))
        bezier34Path.addLine(to: CGPoint(x: 444, y: 792))
        bezier34Path.addLine(to: CGPoint(x: 467, y: 860))
        bezier34Path.addLine(to: CGPoint(x: 537, y: 835))
        UIColor.darkGray.setStroke()
        bezier34Path.lineWidth = 2
        bezier34Path.lineCapStyle = .round
        bezier34Path.stroke()


        //// Bezier 35 Drawing
        let bezier35Path = UIBezierPath()
        bezier35Path.move(to: CGPoint(x: 405, y: 806))
        bezier35Path.addLine(to: CGPoint(x: 444, y: 792))
        UIColor.darkGray.setStroke()
        bezier35Path.lineWidth = 2
        bezier35Path.stroke()


        //// Bezier 36 Drawing
        let bezier36Path = UIBezierPath()
        bezier36Path.move(to: CGPoint(x: 459, y: 717))
        bezier36Path.addLine(to: CGPoint(x: 480, y: 779))
        UIColor.darkGray.setStroke()
        bezier36Path.lineWidth = 2
        bezier36Path.stroke()


        //// Bezier 37 Drawing
        context.saveGState()
        context.translateBy(x: 467, y: 725.56)
        context.scaleBy(x: 0.96, y: 0.96)

        let bezier37Path = UIBezierPath()
        bezier37Path.move(to: CGPoint(x: 0, y: 15.04))
        bezier37Path.addLine(to: CGPoint(x: 42.71, y: -0.58))
        UIColor.darkGray.setStroke()
        bezier37Path.lineWidth = 2
        bezier37Path.lineCapStyle = .round
        bezier37Path.lineJoinStyle = .round
        bezier37Path.stroke()

        context.restoreGState()


        //// Bezier 38 Drawing
        let bezier38Path = UIBezierPath()
        bezier38Path.move(to: CGPoint(x: 482, y: 947))
        bezier38Path.addLine(to: CGPoint(x: 428, y: 947))
        bezier38Path.addLine(to: CGPoint(x: 428, y: 874))
        bezier38Path.addLine(to: CGPoint(x: 467, y: 860))
        UIColor.darkGray.setStroke()
        bezier38Path.lineWidth = 2
        bezier38Path.lineCapStyle = .round
        bezier38Path.lineJoinStyle = .round
        bezier38Path.stroke()


        //// Bezier 40 Drawing
        let bezier40Path = UIBezierPath()
        bezier40Path.move(to: CGPoint(x: 483, y: 904))
        bezier40Path.addLine(to: CGPoint(x: 483, y: 889))
        bezier40Path.addLine(to: CGPoint(x: 428, y: 889))
        UIColor.darkGray.setStroke()
        bezier40Path.lineWidth = 2
        bezier40Path.stroke()


        //// Bezier 41 Drawing
        let bezier41Path = UIBezierPath()
        bezier41Path.move(to: CGPoint(x: 427, y: 881))
        bezier41Path.addLine(to: CGPoint(x: 404, y: 881))
        UIColor.darkGray.setStroke()
        bezier41Path.lineWidth = 2
        bezier41Path.lineCapStyle = .round
        bezier41Path.lineJoinStyle = .round
        bezier41Path.stroke()


        //// Bezier 42 Drawing
        let bezier42Path = UIBezierPath()
        bezier42Path.move(to: CGPoint(x: 427, y: 907))
        bezier42Path.addLine(to: CGPoint(x: 404, y: 907))
        UIColor.darkGray.setStroke()
        bezier42Path.lineWidth = 2
        bezier42Path.lineCapStyle = .round
        bezier42Path.lineJoinStyle = .round
        bezier42Path.stroke()


        //// Bezier 39 Drawing
        let bezier39Path = UIBezierPath()
        bezier39Path.move(to: CGPoint(x: 753, y: 1068))
        bezier39Path.addLine(to: CGPoint(x: 686, y: 1091))
        bezier39Path.addLine(to: CGPoint(x: 617, y: 887))
        bezier39Path.addLine(to: CGPoint(x: 685, y: 886))
        bezier39Path.addLine(to: CGPoint(x: 753, y: 1068))
        bezier39Path.addLine(to: CGPoint(x: 815, y: 1046))
        bezier39Path.addLine(to: CGPoint(x: 846, y: 1136))
        bezier39Path.addLine(to: CGPoint(x: 1005, y: 1080))
        bezier39Path.addLine(to: CGPoint(x: 990, y: 1035))
        UIColor.darkGray.setStroke()
        bezier39Path.lineWidth = 2
        bezier39Path.lineCapStyle = .round
        bezier39Path.lineJoinStyle = .round
        bezier39Path.stroke()


        //// Bezier 43 Drawing
        let bezier43Path = UIBezierPath()
        bezier43Path.move(to: CGPoint(x: 736, y: 1096))
        bezier43Path.addLine(to: CGPoint(x: 800, y: 1074))
        bezier43Path.addLine(to: CGPoint(x: 847, y: 1214))
        UIColor.darkGray.setStroke()
        bezier43Path.lineWidth = 2
        bezier43Path.lineCapStyle = .round
        bezier43Path.lineJoinStyle = .round
        bezier43Path.stroke()


        //// Bezier 45 Drawing
        let bezier45Path = UIBezierPath()
        bezier45Path.move(to: CGPoint(x: 771, y: 1187))
        bezier45Path.addLine(to: CGPoint(x: 831, y: 1166))
        UIColor.darkGray.setStroke()
        bezier45Path.lineWidth = 2
        bezier45Path.stroke()


        //// Bezier 44 Drawing
        let bezier44Path = UIBezierPath()
        bezier44Path.move(to: CGPoint(x: 755, y: 1142))
        bezier44Path.addLine(to: CGPoint(x: 815, y: 1121))
        UIColor.darkGray.setStroke()
        bezier44Path.lineWidth = 2
        bezier44Path.stroke()


        //// Bezier 46 Drawing
        let bezier46Path = UIBezierPath()
        bezier46Path.move(to: CGPoint(x: 980, y: 1232))
        bezier46Path.addLine(to: CGPoint(x: 952, y: 1148))
        bezier46Path.addLine(to: CGPoint(x: 938, y: 1153))
        bezier46Path.addLine(to: CGPoint(x: 966, y: 1143))
        UIColor.darkGray.setStroke()
        bezier46Path.lineWidth = 2
        bezier46Path.lineCapStyle = .round
        bezier46Path.lineJoinStyle = .round
        bezier46Path.stroke()


        //// Bezier 47 Drawing
        let bezier47Path = UIBezierPath()
        bezier47Path.move(to: CGPoint(x: 860, y: 1196))
        bezier47Path.addLine(to: CGPoint(x: 1030, y: 1136))
        UIColor.darkGray.setStroke()
        bezier47Path.lineWidth = 2
        bezier47Path.stroke()


        //// Bezier 48 Drawing
        let bezier48Path = UIBezierPath()
        bezier48Path.move(to: CGPoint(x: 863, y: 1205))
        bezier48Path.addLine(to: CGPoint(x: 856, y: 1183))
        bezier48Path.addLine(to: CGPoint(x: 867, y: 1179))
        UIColor.darkGray.setStroke()
        bezier48Path.lineWidth = 2
        bezier48Path.lineCapStyle = .round
        bezier48Path.lineJoinStyle = .round
        bezier48Path.stroke()


        //// Bezier 49 Drawing
        let bezier49Path = UIBezierPath()
        bezier49Path.move(to: CGPoint(x: 1035, y: 1149))
        bezier49Path.addLine(to: CGPoint(x: 1026, y: 1122))
        bezier49Path.addLine(to: CGPoint(x: 1015, y: 1126))
        UIColor.darkGray.setStroke()
        bezier49Path.lineWidth = 2
        bezier49Path.lineCapStyle = .round
        bezier49Path.lineJoinStyle = .round
        bezier49Path.stroke()


        //// Bezier 50 Drawing
        let bezier50Path = UIBezierPath()
        bezier50Path.move(to: CGPoint(x: 836, y: 1024))
        bezier50Path.addLine(to: CGPoint(x: 780, y: 1043))
        bezier50Path.addLine(to: CGPoint(x: 784.5, y: 1056))
        UIColor.darkGray.setStroke()
        bezier50Path.lineWidth = 2
        bezier50Path.lineCapStyle = .round
        bezier50Path.lineJoinStyle = .round
        bezier50Path.stroke()


        //// Bezier 51 Drawing
        let bezier51Path = UIBezierPath()
        bezier51Path.move(to: CGPoint(x: 990, y: 1034))
        bezier51Path.addLine(to: CGPoint(x: 853, y: 1081))
        bezier51Path.addLine(to: CGPoint(x: 834, y: 1023))
        UIColor.darkGray.setStroke()
        bezier51Path.lineWidth = 2
        bezier51Path.lineCapStyle = .round
        bezier51Path.lineJoinStyle = .round
        bezier51Path.stroke()


        //// Bezier 52 Drawing
        let bezier52Path = UIBezierPath()
        bezier52Path.move(to: CGPoint(x: 880, y: 1009))
        bezier52Path.addLine(to: CGPoint(x: 899, y: 1065))
        UIColor.darkGray.setStroke()
        bezier52Path.lineWidth = 2
        bezier52Path.stroke()


        //// Bezier 53 Drawing
        let bezier53Path = UIBezierPath()
        bezier53Path.move(to: CGPoint(x: 1011, y: 1030))
        bezier53Path.addLine(to: CGPoint(x: 1025, y: 1072))
        bezier53Path.addLine(to: CGPoint(x: 1090, y: 1049))
        bezier53Path.addLine(to: CGPoint(x: 1075, y: 1006))
        UIColor.darkGray.setStroke()
        bezier53Path.lineWidth = 2
        bezier53Path.lineCapStyle = .round
        bezier53Path.lineJoinStyle = .round
        bezier53Path.stroke()


        //// Bezier 54 Drawing
        let bezier54Path = UIBezierPath()
        bezier54Path.move(to: CGPoint(x: 1090, y: 1049))
        bezier54Path.addLine(to: CGPoint(x: 1175, y: 1019))
        UIColor.darkGray.setStroke()
        bezier54Path.lineWidth = 2
        bezier54Path.stroke()


        //// Bezier 55 Drawing
        let bezier55Path = UIBezierPath()
        bezier55Path.move(to: CGPoint(x: 1082, y: 903))
        bezier55Path.addLine(to: CGPoint(x: 1128, y: 1036))
        UIColor.darkGray.setStroke()
        bezier55Path.lineWidth = 2
        bezier55Path.stroke()


        //// Bezier 56 Drawing
        let bezier56Path = UIBezierPath()
        bezier56Path.move(to: CGPoint(x: 1092, y: 899))
        bezier56Path.addLine(to: CGPoint(x: 1138, y: 1031))
        UIColor.darkGray.setStroke()
        bezier56Path.lineWidth = 2
        bezier56Path.stroke()


        //// Bezier 57 Drawing
        let bezier57Path = UIBezierPath()
        bezier57Path.move(to: CGPoint(x: 1089, y: 927))
        bezier57Path.addLine(to: CGPoint(x: 1052, y: 940))
        UIColor.darkGray.setStroke()
        bezier57Path.lineWidth = 2
        bezier57Path.lineCapStyle = .round
        bezier57Path.stroke()


        //// Bezier 58 Drawing
        let bezier58Path = UIBezierPath()
        bezier58Path.move(to: CGPoint(x: 1097, y: 950))
        bezier58Path.addLine(to: CGPoint(x: 1060, y: 963))
        UIColor.darkGray.setStroke()
        bezier58Path.lineWidth = 2
        bezier58Path.lineCapStyle = .round
        bezier58Path.stroke()


        //// Bezier 59 Drawing
        let bezier59Path = UIBezierPath()
        bezier59Path.move(to: CGPoint(x: 1105, y: 971))
        bezier59Path.addLine(to: CGPoint(x: 1068, y: 984))
        UIColor.darkGray.setStroke()
        bezier59Path.lineWidth = 2
        bezier59Path.stroke()


        //// Bezier 60 Drawing
        let bezier60Path = UIBezierPath()
        bezier60Path.move(to: CGPoint(x: 1112, y: 993))
        bezier60Path.addLine(to: CGPoint(x: 1075, y: 1006))
        UIColor.darkGray.setStroke()
        bezier60Path.lineWidth = 2
        bezier60Path.lineCapStyle = .round
        bezier60Path.stroke()


        //// Bezier 61 Drawing
        let bezier61Path = UIBezierPath()
        bezier61Path.move(to: CGPoint(x: 1120, y: 1014.5))
        bezier61Path.addLine(to: CGPoint(x: 1082, y: 1028))
        UIColor.darkGray.setStroke()
        bezier61Path.lineWidth = 2
        bezier61Path.stroke()


        //// Bezier 62 Drawing
        let bezier62Path = UIBezierPath()
        bezier62Path.move(to: CGPoint(x: 1152, y: 954.5))
        bezier62Path.addLine(to: CGPoint(x: 1116, y: 967))
        UIColor.darkGray.setStroke()
        bezier62Path.lineWidth = 2
        bezier62Path.stroke()


        //// Bezier 63 Drawing
        let bezier63Path = UIBezierPath()
        bezier63Path.move(to: CGPoint(x: 1145, y: 933.5))
        bezier63Path.addLine(to: CGPoint(x: 1109, y: 946))
        UIColor.darkGray.setStroke()
        bezier63Path.lineWidth = 2
        bezier63Path.stroke()


        //// Bezier 64 Drawing
        let bezier64Path = UIBezierPath()
        bezier64Path.move(to: CGPoint(x: 1159, y: 976.5))
        bezier64Path.addLine(to: CGPoint(x: 1123, y: 989))
        UIColor.darkGray.setStroke()
        bezier64Path.lineWidth = 2
        bezier64Path.stroke()


        //// Bezier 65 Drawing
        let bezier65Path = UIBezierPath()
        bezier65Path.move(to: CGPoint(x: 1167, y: 998))
        bezier65Path.addLine(to: CGPoint(x: 1131, y: 1011))
        UIColor.darkGray.setStroke()
        bezier65Path.lineWidth = 2
        bezier65Path.stroke()


        //// Bezier 66 Drawing
        let bezier66Path = UIBezierPath()
        bezier66Path.move(to: CGPoint(x: 1198, y: 1087))
        bezier66Path.addLine(to: CGPoint(x: 1251, y: 1241))
        UIColor.darkGray.setStroke()
        bezier66Path.lineWidth = 2
        bezier66Path.stroke()


        //// Bezier 67 Drawing
        let bezier67Path = UIBezierPath()
        bezier67Path.move(to: CGPoint(x: 1210, y: 1082))
        bezier67Path.addLine(to: CGPoint(x: 1264, y: 1237))
        UIColor.darkGray.setStroke()
        bezier67Path.lineWidth = 2
        bezier67Path.stroke()


        //// Bezier 68 Drawing
        let bezier68Path = UIBezierPath()
        bezier68Path.move(to: CGPoint(x: 1160, y: 1101))
        bezier68Path.addLine(to: CGPoint(x: 1245, y: 1070))
        UIColor.darkGray.setStroke()
        bezier68Path.lineWidth = 2
        bezier68Path.stroke()


        //// Bezier 69 Drawing
        let bezier69Path = UIBezierPath()
        bezier69Path.move(to: CGPoint(x: 1212, y: 1129))
        bezier69Path.addLine(to: CGPoint(x: 1176, y: 1142))
        UIColor.darkGray.setStroke()
        bezier69Path.lineWidth = 2
        bezier69Path.stroke()


        //// Bezier 70 Drawing
        let bezier70Path = UIBezierPath()
        bezier70Path.move(to: CGPoint(x: 1227, y: 1174))
        bezier70Path.addLine(to: CGPoint(x: 1191, y: 1187))
        UIColor.darkGray.setStroke()
        bezier70Path.lineWidth = 2
        bezier70Path.stroke()


        //// Bezier 71 Drawing
        let bezier71Path = UIBezierPath()
        bezier71Path.move(to: CGPoint(x: 1235, y: 1196))
        bezier71Path.addLine(to: CGPoint(x: 1199, y: 1209))
        UIColor.darkGray.setStroke()
        bezier71Path.lineWidth = 2
        bezier71Path.stroke()


        //// Bezier 72 Drawing
        let bezier72Path = UIBezierPath()
        bezier72Path.move(to: CGPoint(x: 1243, y: 1218.5))
        bezier72Path.addLine(to: CGPoint(x: 1208, y: 1231))
        UIColor.darkGray.setStroke()
        bezier72Path.lineWidth = 2
        bezier72Path.stroke()


        //// Bezier 73 Drawing
        let bezier73Path = UIBezierPath()
        bezier73Path.move(to: CGPoint(x: 1291, y: 1201))
        bezier73Path.addLine(to: CGPoint(x: 1255, y: 1214))
        UIColor.darkGray.setStroke()
        bezier73Path.lineWidth = 2
        bezier73Path.stroke()


        //// Bezier 74 Drawing
        let bezier74Path = UIBezierPath()
        bezier74Path.move(to: CGPoint(x: 1282, y: 1179))
        bezier74Path.addLine(to: CGPoint(x: 1248, y: 1191))
        UIColor.darkGray.setStroke()
        bezier74Path.lineWidth = 2
        bezier74Path.stroke()


        //// Bezier 75 Drawing
        let bezier75Path = UIBezierPath()
        bezier75Path.move(to: CGPoint(x: 1276, y: 1156))
        bezier75Path.addLine(to: CGPoint(x: 1240, y: 1169))
        UIColor.darkGray.setStroke()
        bezier75Path.lineWidth = 2
        bezier75Path.stroke()


        //// Bezier 76 Drawing
        let bezier76Path = UIBezierPath()
        bezier76Path.move(to: CGPoint(x: 1268, y: 1134))
        bezier76Path.addLine(to: CGPoint(x: 1232, y: 1147))
        UIColor.darkGray.setStroke()
        bezier76Path.lineWidth = 2
        bezier76Path.stroke()


        //// Bezier 77 Drawing
        let bezier77Path = UIBezierPath()
        bezier77Path.move(to: CGPoint(x: 1261, y: 1112))
        bezier77Path.addLine(to: CGPoint(x: 1225, y: 1125))
        UIColor.darkGray.setStroke()
        bezier77Path.lineWidth = 2
        bezier77Path.stroke()


        //// Bezier 78 Drawing
        let bezier78Path = UIBezierPath()
        bezier78Path.move(to: CGPoint(x: 1253, y: 1090))
        bezier78Path.addLine(to: CGPoint(x: 1217, y: 1103))
        UIColor.darkGray.setStroke()
        bezier78Path.lineWidth = 2
        bezier78Path.stroke()


        //// Bezier 79 Drawing
        let bezier79Path = UIBezierPath()
        bezier79Path.move(to: CGPoint(x: 1210, y: 1082))
        bezier79Path.addLine(to: CGPoint(x: 1186, y: 1015))
        UIColor.darkGray.setStroke()
        bezier79Path.lineWidth = 2
        bezier79Path.stroke()


        //// Bezier 80 Drawing
        let bezier80Path = UIBezierPath()
        bezier80Path.move(to: CGPoint(x: 1162, y: 1102))
        bezier80Path.addLine(to: CGPoint(x: 1153.5, y: 1077))
        bezier80Path.addLine(to: CGPoint(x: 1105, y: 1094))
        bezier80Path.addLine(to: CGPoint(x: 1113, y: 1117))
        UIColor.darkGray.setStroke()
        bezier80Path.lineWidth = 2
        bezier80Path.lineCapStyle = .round
        bezier80Path.lineJoinStyle = .round
        bezier80Path.stroke()


        //// Bezier 81 Drawing
        let bezier81Path = UIBezierPath()
        bezier81Path.move(to: CGPoint(x: 1128, y: 1036))
        bezier81Path.addLine(to: CGPoint(x: 1136, y: 1058.5))
        bezier81Path.addLine(to: CGPoint(x: 1098, y: 1072))
        bezier81Path.addLine(to: CGPoint(x: 1090, y: 1049))
        UIColor.darkGray.setStroke()
        bezier81Path.lineWidth = 2
        bezier81Path.lineCapStyle = .round
        bezier81Path.lineJoinStyle = .round
        bezier81Path.stroke()


        //// Bezier 82 Drawing
        let bezier82Path = UIBezierPath()
        bezier82Path.move(to: CGPoint(x: 1175, y: 1019))
        bezier82Path.addLine(to: CGPoint(x: 1183, y: 1042))
        bezier82Path.addLine(to: CGPoint(x: 1146.5, y: 1055))
        bezier82Path.addLine(to: CGPoint(x: 1138, y: 1031))
        UIColor.darkGray.setStroke()
        bezier82Path.lineWidth = 2
        bezier82Path.lineCapStyle = .round
        bezier82Path.lineJoinStyle = .round
        bezier82Path.stroke()


        //// Bezier 83 Drawing
        let bezier83Path = UIBezierPath()
        bezier83Path.move(to: CGPoint(x: 679, y: 870))
        bezier83Path.addLine(to: CGPoint(x: 715, y: 857))
        bezier83Path.addLine(to: CGPoint(x: 701, y: 820))
        UIColor.darkGray.setStroke()
        bezier83Path.lineWidth = 2
        bezier83Path.lineCapStyle = .round
        bezier83Path.lineJoinStyle = .round
        bezier83Path.stroke()


        //// Bezier 84 Drawing
        let bezier84Path = UIBezierPath()
        bezier84Path.move(to: CGPoint(x: 687, y: 891))
        bezier84Path.addLine(to: CGPoint(x: 724, y: 878))
        bezier84Path.addLine(to: CGPoint(x: 756, y: 964))
        bezier84Path.addLine(to: CGPoint(x: 720, y: 977))
        UIColor.darkGray.setStroke()
        bezier84Path.lineWidth = 2
        bezier84Path.stroke()


        //// Bezier 85 Drawing
        let bezier85Path = UIBezierPath()
        bezier85Path.move(to: CGPoint(x: 736, y: 910))
        bezier85Path.addLine(to: CGPoint(x: 700, y: 923))
        UIColor.darkGray.setStroke()
        bezier85Path.lineWidth = 2
        bezier85Path.lineCapStyle = .round
        bezier85Path.stroke()


        //// Bezier 86 Drawing
        let bezier86Path = UIBezierPath()
        bezier86Path.move(to: CGPoint(x: 748, y: 943))
        bezier86Path.addLine(to: CGPoint(x: 712, y: 956))
        UIColor.darkGray.setStroke()
        bezier86Path.lineWidth = 2
        bezier86Path.lineCapStyle = .round
        bezier86Path.stroke()


        //// Bezier 87 Drawing
        let bezier87Path = UIBezierPath()
        bezier87Path.move(to: CGPoint(x: 806, y: 947))
        bezier87Path.addLine(to: CGPoint(x: 769, y: 960))
        bezier87Path.addLine(to: CGPoint(x: 737, y: 873))
        bezier87Path.addLine(to: CGPoint(x: 713, y: 882))
        UIColor.darkGray.setStroke()
        bezier87Path.lineWidth = 2
        bezier87Path.lineCapStyle = .round
        bezier87Path.lineJoinStyle = .round
        bezier87Path.stroke()


        //// Bezier 88 Drawing
        let bezier88Path = UIBezierPath()
        bezier88Path.move(to: CGPoint(x: 797, y: 925))
        bezier88Path.addLine(to: CGPoint(x: 761, y: 938))
        UIColor.darkGray.setStroke()
        bezier88Path.lineWidth = 2
        bezier88Path.lineCapStyle = .round
        bezier88Path.stroke()


        //// Bezier 89 Drawing
        let bezier89Path = UIBezierPath()
        bezier89Path.move(to: CGPoint(x: 790, y: 903))
        bezier89Path.addLine(to: CGPoint(x: 754, y: 916))
        UIColor.darkGray.setStroke()
        bezier89Path.lineWidth = 2
        bezier89Path.lineCapStyle = .round
        bezier89Path.stroke()


        //// Bezier 90 Drawing
        let bezier90Path = UIBezierPath()
        bezier90Path.move(to: CGPoint(x: 788, y: 895))
        bezier90Path.addLine(to: CGPoint(x: 783, y: 882))
        bezier90Path.addLine(to: CGPoint(x: 746, y: 895))
        UIColor.darkGray.setStroke()
        bezier90Path.lineWidth = 2
        bezier90Path.lineCapStyle = .round
        bezier90Path.lineJoinStyle = .round
        bezier90Path.stroke()


        //// Bezier 91 Drawing
        let bezier91Path = UIBezierPath()
        bezier91Path.move(to: CGPoint(x: 775, y: 860))
        bezier91Path.addLine(to: CGPoint(x: 785, y: 887))
        UIColor.darkGray.setStroke()
        bezier91Path.lineWidth = 2
        bezier91Path.lineCapStyle = .round
        bezier91Path.stroke()


        //// Bezier 92 Drawing
        let bezier92Path = UIBezierPath()
        bezier92Path.move(to: CGPoint(x: 724.3, y: 682))
        bezier92Path.addLine(to: CGPoint(x: 798.8, y: 889))
        UIColor.darkGray.setStroke()
        bezier92Path.lineWidth = 2
        bezier92Path.lineCapStyle = .round
        bezier92Path.stroke()


        //// Bezier 93 Drawing
        let bezier93Path = UIBezierPath()
        bezier93Path.move(to: CGPoint(x: 712.3, y: 688))
        bezier93Path.addLine(to: CGPoint(x: 766, y: 838.5))
        bezier93Path.addLine(to: CGPoint(x: 727.5, y: 852))
        bezier93Path.addLine(to: CGPoint(x: 713.3, y: 814))
        UIColor.darkGray.setStroke()
        bezier93Path.lineWidth = 2
        bezier93Path.lineCapStyle = .round
        bezier93Path.lineJoinStyle = .round
        bezier93Path.stroke()


        //// Bezier 95 Drawing
        let bezier95Path = UIBezierPath()
        bezier95Path.move(to: CGPoint(x: 741, y: 770))
        bezier95Path.addLine(to: CGPoint(x: 703, y: 784))
        UIColor.darkGray.setStroke()
        bezier95Path.lineWidth = 2
        bezier95Path.lineCapStyle = .round
        bezier95Path.stroke()


        //// Bezier 96 Drawing
        let bezier96Path = UIBezierPath()
        bezier96Path.move(to: CGPoint(x: 732, y: 747))
        bezier96Path.addLine(to: CGPoint(x: 694, y: 761))
        UIColor.darkGray.setStroke()
        bezier96Path.lineWidth = 2
        bezier96Path.lineCapStyle = .round
        bezier96Path.stroke()


        //// Bezier 97 Drawing
        let bezier97Path = UIBezierPath()
        bezier97Path.move(to: CGPoint(x: 724, y: 724))
        bezier97Path.addLine(to: CGPoint(x: 686, y: 738))
        UIColor.darkGray.setStroke()
        bezier97Path.lineWidth = 2
        bezier97Path.lineCapStyle = .round
        bezier97Path.stroke()


        //// Bezier 98 Drawing
        let bezier98Path = UIBezierPath()
        bezier98Path.move(to: CGPoint(x: 776, y: 705))
        bezier98Path.addLine(to: CGPoint(x: 738, y: 719))
        UIColor.darkGray.setStroke()
        bezier98Path.lineWidth = 2
        bezier98Path.stroke()


        //// Bezier 99 Drawing
        let bezier99Path = UIBezierPath()
        bezier99Path.move(to: CGPoint(x: 784, y: 728))
        bezier99Path.addLine(to: CGPoint(x: 746, y: 742))
        UIColor.darkGray.setStroke()
        bezier99Path.lineWidth = 2
        bezier99Path.stroke()


        //// Bezier 100 Drawing
        let bezier100Path = UIBezierPath()
        bezier100Path.move(to: CGPoint(x: 791, y: 752))
        bezier100Path.addLine(to: CGPoint(x: 755, y: 765))
        UIColor.darkGray.setStroke()
        bezier100Path.lineWidth = 2
        bezier100Path.lineCapStyle = .round
        bezier100Path.stroke()


        //// Bezier 101 Drawing
        let bezier101Path = UIBezierPath()
        bezier101Path.move(to: CGPoint(x: 799, y: 775))
        bezier101Path.addLine(to: CGPoint(x: 763, y: 788))
        UIColor.darkGray.setStroke()
        bezier101Path.lineWidth = 2
        bezier101Path.lineCapStyle = .round
        bezier101Path.stroke()


        //// Bezier 102 Drawing
        let bezier102Path = UIBezierPath()
        bezier102Path.move(to: CGPoint(x: 807, y: 797))
        bezier102Path.addLine(to: CGPoint(x: 771, y: 810))
        UIColor.darkGray.setStroke()
        bezier102Path.lineWidth = 2
        bezier102Path.lineCapStyle = .round
        bezier102Path.stroke()


        //// Bezier 103 Drawing
        let bezier103Path = UIBezierPath()
        bezier103Path.move(to: CGPoint(x: 815, y: 820))
        bezier103Path.addLine(to: CGPoint(x: 779, y: 833))
        UIColor.darkGray.setStroke()
        bezier103Path.lineWidth = 2
        bezier103Path.lineCapStyle = .round
        bezier103Path.stroke()


        //// Bezier 104 Drawing
        let bezier104Path = UIBezierPath()
        bezier104Path.move(to: CGPoint(x: 823, y: 842))
        bezier104Path.addLine(to: CGPoint(x: 788, y: 855))
        UIColor.darkGray.setStroke()
        bezier104Path.lineWidth = 2
        bezier104Path.lineCapStyle = .round
        bezier104Path.stroke()


        //// Bezier 105 Drawing
        let bezier105Path = UIBezierPath()
        bezier105Path.move(to: CGPoint(x: 758, y: 815))
        bezier105Path.addLine(to: CGPoint(x: 719, y: 829))
        UIColor.darkGray.setStroke()
        bezier105Path.lineWidth = 2
        bezier105Path.stroke()


        //// Bezier 106 Drawing
        let bezier106Path = UIBezierPath()
        bezier106Path.move(to: CGPoint(x: 365, y: 309))
        bezier106Path.addLine(to: CGPoint(x: 377, y: 305))
        UIColor.darkGray.setStroke()
        bezier106Path.lineWidth = 2
        bezier106Path.stroke()
        
        context.restoreGState()

    }

    //// Generated Images

    @objc dynamic public class var imageOfCanvas1: UIImage {
        if Cache.imageOfCanvas1 != nil {
            return Cache.imageOfCanvas1!
        }

        UIGraphicsBeginImageContextWithOptions(CGSize(width: 1343, height: 1308), false, 0)
            IZGroundfloor.drawCanvas1()

        Cache.imageOfCanvas1 = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return Cache.imageOfCanvas1!
    }

    //// Customization Infrastructure

    @objc @IBOutlet dynamic var canvas1Targets: [AnyObject]! {
        get { return Cache.canvas1Targets }
        set {
            Cache.canvas1Targets = newValue
            for target: AnyObject in newValue {
                let _ = target.perform(NSSelectorFromString("setImage:"), with: IZGroundfloor.imageOfCanvas1)
            }
        }
    }




    @objc(IZGroundfloorResizingBehavior)
    public enum ResizingBehavior: Int {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.

        public func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }

            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)

            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }

            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
}
